[mypy]
python_version = 3.12
files = custom_nodes, docker, docs, scripts/lib, studio-ui, tests/python, tools
mypy_path = custom_nodes, docker, docker/pythonpath, scripts/lib, studio-ui, tests/python, docs
explicit_package_bases = True
namespace_packages = True
ignore_missing_imports = True
check_untyped_defs = True
exclude = (?x)(^|/)(site|coverage|\.venv|venv)/
