"""Author Cinema Rack JSON catalogs. Not imported by pytest.

Run from repo root:

  python3 tests/python/_build_cinema_catalogs.py
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[2]
OUT = ROOT / "custom_nodes" / "ez_prompt_enhance" / "cinema"


def _entry(
    tid: str,
    label: str,
    clause: str,
    *,
    still: str = "",
    wan: str = "",
    audio: str = "",
    still_ok: bool = True,
    motion_ok: bool = True,
    av_ok: bool = True,
    conflicts: tuple[str, ...] = (),
    tags: tuple[str, ...] = (),
) -> dict[str, Any]:
    row: dict[str, Any] = {
        "id": tid,
        "label": label,
        "clause": clause if clause.endswith(".") else f"{clause}.",
        "still": still,
        "wan_token": wan,
        "audio": audio,
        "still_ok": still_ok,
        "motion_ok": motion_ok,
        "av_ok": av_ok,
        "conflicts": list(conflicts),
        "tags": list(tags),
    }
    if still and not still.endswith("."):
        row["still"] = f"{still}."
    return row


def _dump(name: str, rows: list[dict[str, Any]]) -> None:
    path = OUT / name
    path.write_text(json.dumps(rows, indent=2) + "\n", encoding="utf-8")
    print(f"wrote {path.relative_to(ROOT)} ({len(rows)})")


def _move(
    tid: str,
    label: str,
    action: str,
    freeze: str,
    wan: str,
    tail: str,
    *conflicts: str,
    tags: tuple[str, ...] = ("support",),
) -> dict[str, Any]:
    return _entry(
        tid,
        label,
        f"The camera {action}, {tail}",
        still=f"Locked as if {freeze}, {tail}",
        wan=wan,
        conflicts=conflicts,
        tags=tags,
    )


def camera_movement() -> list[dict[str, Any]]:
    rows = [
        _move("move_pan_left", "Pan left", "pans left on a locked tripod head", "mid-pan-left", "pan left", "sweeping the unmarked street from the doorway toward the corner lamp", "move_whip_pan_left"),
        _move("move_pan_right", "Pan right", "pans right on a locked tripod head", "mid-pan-right", "pan right", "letting terrace lanterns drift across the bay slot", "move_whip_pan_right"),
        _move("move_slow_pan_left", "Slow pan left", "pans left at crawl speed on a geared head", "a crawl pan left frozen", "slow pan left", "clouds and distant towers sliding a finger-width at a time"),
        _move("move_slow_pan_right", "Slow pan right", "pans right at crawl speed on a geared head", "a crawl pan right frozen", "slow pan right", "a long colonnade revealing one column after another"),
        _move("move_whip_pan_left", "Whip pan left", "whips left in a blurred pan", "a whip-pan smear frozen mid-blur", "whip pan left", "streaking practicals into unreadable color bands", "move_pan_left", "move_locked_off", tags=("energy",)),
        _move("move_whip_pan_right", "Whip pan right", "whips right in a blurred pan", "a whip-pan smear frozen mid-blur", "whip pan right", "neon shopfronts collapsing into horizontal streaks", "move_pan_right", "move_locked_off", tags=("energy",)),
        _move("move_search_pan", "Search pan", "pans in a searching arc on a fluid head", "mid-search pan", "pan", "hunting a doorway then overshooting and correcting"),
        _move("move_tilt_up", "Tilt up", "tilts up from a locked tripod", "mid-tilt-up", "tilt up", "rising from pavement grit to the unmarked crown of the tower"),
        _move("move_tilt_down", "Tilt down", "tilts down from a locked tripod", "mid-tilt-down", "tilt down", "dropping from sky to the subject's hands and the teak deck"),
        _move("move_slow_tilt_up", "Slow tilt up", "tilts up at crawl speed", "a crawl tilt-up frozen", "slow tilt up", "a facade unrolling floor by floor"),
        _move("move_slow_tilt_down", "Slow tilt down", "tilts down at crawl speed", "a crawl tilt-down frozen", "slow tilt down", "a tree canopy giving way to roots and wet soil"),
        _move("move_snap_tilt_up", "Snap tilt up", "snaps tilt up in one accent", "a snap tilt frozen at the top", "tilt up", "punching from shoes to sky in a single jerk", tags=("energy",)),
        _move("move_nod_tilt", "Nod tilt", "tilts in a small nodding search", "a nodding tilt frozen", "tilt", "checking the subject's face then the object in their hands"),
        _move("move_dutch_roll", "Dutch roll", "rolls the horizon off-level while holding position", "a canted roll frozen", "roll", "the floor line tilting as if the room lost its balance", "move_locked_off", tags=("dutch",)),
        _move("move_level_out", "Level out", "rolls from a canted horizon back to level", "mid-level-out from a dutch", "roll", "the verticals of the tower standing up straight again", tags=("dutch",)),
        _move("move_dolly_in", "Dolly in", "dollies in on a locked wheeled support, tightening without zooming", "mid-dolly-in", "dolly in", "the subject's face growing while background geometry stays honest", "fx_crash_zoom", "opt_zoom_in"),
        _move("move_dolly_out", "Dolly out", "dollies out on a locked wheeled support, widening without zooming", "mid-dolly-out", "dolly out", "the room expanding around a still figure", "opt_zoom_out"),
        _move("move_slow_dolly_in", "Slow dolly in", "creeps in on silent dolly wheels", "a crawl dolly-in frozen", "dolly in", "breath and blinks becoming the only motion in a shrinking frame"),
        _move("move_slow_dolly_out", "Slow dolly out", "creeps out on silent dolly wheels", "a crawl dolly-out frozen", "dolly out", "isolation growing as walls recede"),
        _move("move_crash_dolly_in", "Crash dolly in", "crashes in on a fast dolly", "a crash dolly-in frozen on a tight face", "dolly in", "the background ripping past in a sudden close-up", "move_slow_dolly_in", tags=("energy",)),
        _move("move_dolly_zoom_in", "Dolly zoom in", "dollies in while zooming out so the subject size holds and space warps", "a dolly-zoom warp frozen", "dolly zoom", "the corridor stretching while the face stays the same size", "move_dolly_in", "opt_zoom_out", tags=("compound",)),
        _move("move_dolly_zoom_out", "Dolly zoom out", "dollies out while zooming in so the subject size holds and space crushes", "a reverse dolly-zoom frozen", "dolly zoom", "the world flattening behind a face that does not grow", "move_dolly_out", "opt_zoom_in", tags=("compound",)),
        _move("move_tracking_left", "Tracking left", "tracks left parallel to the subject", "mid-tracking-left", "tracking", "keeping pace beside a walk along a wet unmarked arcade"),
        _move("move_tracking_right", "Tracking right", "tracks right parallel to the subject", "mid-tracking-right", "tracking", "matching stride along a night rail over the bay"),
        _move("move_lead_tracking", "Lead tracking", "tracks ahead of the subject, looking back", "lead-tracking frozen", "tracking", "the walker advancing toward camera down a long hall"),
        _move("move_chase_tracking", "Chase tracking", "tracks behind the subject, following", "chase-tracking frozen", "tracking", "the back of a coat leading into an unmarked tunnel"),
        _move("move_lateral_truck_left", "Truck left", "trucks left on a perpendicular axis", "mid-truck-left", "tracking", "sliding past a row of columns that wipe the frame"),
        _move("move_lateral_truck_right", "Truck right", "trucks right on a perpendicular axis", "mid-truck-right", "tracking", "a storefront sequence wiping by like cards"),
        _move("move_pedestal_up", "Pedestal up", "pedestals straight up with no tilt", "mid-pedestal-up", "boom up", "the horizon staying level while the camera rises past a railing"),
        _move("move_pedestal_down", "Pedestal down", "pedestals straight down with no tilt", "mid-pedestal-down", "boom down", "sinking from standing height to the grain of the floorboards"),
        _move("move_crane_up", "Crane up", "cranes up on a jib arm", "mid-crane-up", "crane up", "the terrace shrinking as rooftops and bay enter the top of frame"),
        _move("move_crane_down", "Crane down", "cranes down on a jib arm", "mid-crane-down", "crane down", "descending from weather into a private face"),
        _move("move_crane_in", "Crane in", "cranes on an arc that also pushes in", "mid-crane-in", "crane in", "arriving from above into an intimate two-shot", tags=("compound",)),
        _move("move_crane_reveal", "Crane reveal", "cranes up and over a foreground occluder", "a crane-reveal frozen past the occluder", "crane up", "a parapet dropping away to show the whole unmarked plaza", tags=("reveal",)),
        _move("move_jib_sweep", "Jib sweep", "sweeps a short jib in a smiling arc", "mid-jib-sweep", "crane", "the camera scooping from low dirt to eye-level in one piece"),
        _move("move_arm_over", "Long arm over", "swings a long arm over the set", "a long-arm-over frozen", "crane", "looking down the dining table as if from a gallery"),
        _move("move_slider_left", "Slider left", "slides left on a short rail", "mid-slider-left", "tracking", "a product on a table gaining a new three-quarter"),
        _move("move_slider_right", "Slider right", "slides right on a short rail", "mid-slider-right", "tracking", "parallax shifting a bottle against a soft practical"),
        _move("move_slider_in", "Slider in", "slides in on a short rail aimed at the subject", "mid-slider-in", "dolly in", "a tabletop hero growing without a zoom"),
        _move("move_slider_push_low", "Low slider push", "slides in from ankle height", "a low slider-push frozen", "dolly in", "floorboards racing toward a seated figure"),
        _move("move_steadicam_follow", "Stabilized follow", "follows on a body-worn stabilizer", "a stabilized follow frozen", "tracking", "the operator floating through a doorway without foot-thud shake", tags=("stabilized",)),
        _move("move_steadicam_lead", "Stabilized lead", "leads on a body-worn stabilizer, walking backward", "a stabilized lead frozen", "tracking", "the subject walking toward a floating lens down a corridor", tags=("stabilized",)),
        _move("move_gimbal_orbit", "Gimbal orbit", "orbits on a handheld gimbal", "mid-gimbal-orbit", "orbit", "circling a standing figure while the horizon stays locked", tags=("stabilized",)),
        _move("move_gimbal_rise", "Gimbal rise", "rises on a handheld gimbal from kneel to stand", "a gimbal-rise frozen", "boom up", "the lens lifting with the operator's legs, horizon true", tags=("stabilized",)),
        _move("move_handheld_breathe", "Handheld breathe", "holds handheld with living micro-sway", "handheld breath frozen mid-sway", "handheld", "the frame inhaling with the operator, never locked", "move_locked_off", tags=("handheld",)),
        _move("move_handheld_walk", "Handheld walk", "walks handheld, documenting from inside the group", "a handheld walk frozen", "handheld", "shoulders and footsteps leaking into the frame edges", "move_locked_off", tags=("handheld",)),
        _move("move_handheld_run", "Handheld run", "runs handheld, horizon fighting to stay useful", "a running handheld frozen", "handheld", "pavement shock and pumping arms in a chase document", "move_locked_off", tags=("handheld", "energy")),
        _move("move_shoulder_doc", "Shoulder documentary", "rides a shoulder pad in observational mode", "shoulder-doc frozen", "handheld", "a slightly high documentary eyeline with organic drift", tags=("handheld",)),
        _move("move_bodycam_sprint", "Body-cam sprint", "sprints as a chest-mounted body-cam", "a chest-cam sprint frozen", "tracking", "only the wearer's sleeves along the bottom edge, landing filling the center", tags=("pov",)),
        _move("move_bodycam_lookdown", "Body-cam look-down", "looks down as a chest-mounted body-cam", "chest-cam looking down frozen", "tilt down", "gloves and the next foothold filling the lower frame", tags=("pov",)),
        _move("move_fpv_dive", "FPV dive", "dives as a first-person flyer", "an FPV dive frozen", "crane down", "the plaza rushing up, lens screaming toward a landing mark", tags=("drone", "energy")),
        _move("move_fpv_through", "FPV through", "threads a gap as a first-person flyer", "an FPV gap-thread frozen", "tracking", "a doorway or railing whipping past at the frame edges", tags=("drone",)),
        _move("move_drone_orbit", "Drone orbit", "orbits at mid altitude on a quiet multirotor", "a drone orbit frozen", "orbit", "the unmarked tower turning against the bay", tags=("drone",)),
        _move("move_drone_rise", "Drone rise", "rises on a quiet multirotor", "a drone rise frozen", "crane up", "the building shrinking into a city of unmarked glass", tags=("drone",)),
        _move("move_drone_descend", "Drone descend", "descends on a quiet multirotor", "a drone descend frozen", "crane down", "weather giving way to terrace furniture and palms", tags=("drone",)),
        _move("move_drone_reveal_ridge", "Drone ridge reveal", "flies up over a ridge or parapet", "a ridge-reveal frozen", "crane up", "the hidden plaza blooming into frame past stone", tags=("drone", "reveal")),
        _move("move_drone_topdown", "Drone top-down", "holds a nadir descent", "a nadir descent frozen", "crane down", "plan-view massing of roof and courtyard tightening", tags=("drone",)),
        _move("move_drone_push_in", "Drone push in", "pushes in from altitude toward a figure", "a high push-in frozen", "dolly in", "a person on a roof growing from a speck to a readable body", tags=("drone",)),
        _move("move_cable_traverse", "Cable traverse", "traverses on an overhead cable", "a cable-cam traverse frozen", "tracking", "the street sliding under a high centerline path", tags=("cable",)),
        _move("move_cable_descend", "Cable descend", "descends along a cable toward a crowd", "a cable descend frozen", "crane down", "faces rising to meet a falling overhead lens", tags=("cable",)),
        _move("move_vehicle_side", "Vehicle side mount", "rides a side-mounted vehicle camera", "a vehicle side-mount frozen", "tracking", "asphalt and lane lines streaking under a door-line lens", tags=("vehicle",)),
        _move("move_vehicle_hood", "Vehicle hood mount", "rides a hood-mounted camera looking aft", "a hood-mount frozen", "tracking", "the driver and windscreen filling the frame as city smears behind", tags=("vehicle",)),
        _move("move_vehicle_chase", "Vehicle chase", "chases from a second vehicle", "a vehicle chase frozen", "tracking", "the lead car framed through a windshield, road vibration alive", tags=("vehicle",)),
        _move("move_undercrank_handheld", "Undercranked handheld", "moves handheld with silent-era undercrank energy", "undercranked handheld frozen", "handheld", "jerky comic haste in every step", tags=("handheld", "time")),
        _move("move_locked_off", "Locked off", "holds a locked-off tripod, zero drift", "a perfectly locked still frame", "fixed camera", "architecture and body both pinned, only subject motion allowed", "move_handheld_breathe", "move_whip_pan_left", tags=("locked",)),
        _move("move_static_then_push", "Hold then push", "holds locked, then begins a late dolly in", "the hold-before-push frozen on the still beat", "dolly in", "a conversation beat then a slow tightening", tags=("compound",)),
        _move("move_push_then_hold", "Push then hold", "dollies in and lands on a locked close frame", "the landed hold after a push", "dolly in", "motion dying as the eyes fill the frame", tags=("compound",)),
        _move("move_orbit_left", "Orbit left", "orbits left around the subject at constant radius", "mid-orbit-left", "orbit", "background sliding the opposite way, face turning through three-quarter"),
        _move("move_orbit_right", "Orbit right", "orbits right around the subject at constant radius", "mid-orbit-right", "orbit", "a product or person rotating against a traveling city"),
        _move("move_arc_left", "Arc left", "arcs left on a shallow curve, not a full orbit", "mid-arc-left", "orbit", "a doorway opening into a new wall of the room"),
        _move("move_arc_right", "Arc right", "arcs right on a shallow curve, not a full orbit", "mid-arc-right", "orbit", "a window coming into play as the camera rounds a chair"),
        _move("move_circle_360", "Full circle", "completes a 360-degree orbit", "mid-360-orbit", "orbit", "every wall of the room passing once behind the subject"),
        _move("move_figure_eight", "Figure-eight", "traces a figure-eight on the floor around two marks", "a figure-eight path frozen", "orbit", "two subjects trading foreground as the path crosses", tags=("compound",)),
        _move("move_boom_up_track", "Boom up while tracking", "booms up while tracking beside the subject", "mid-boom-and-track", "tracking", "rising from hip to face without losing the walk", tags=("compound",)),
        _move("move_boom_down_track", "Boom down while tracking", "booms down while tracking beside the subject", "mid-boom-down-track", "tracking", "dropping to the feet without losing pace", tags=("compound",)),
        _move("move_reveal_wipe_by", "Wipe-by reveal", "lets a foreground passerby wipe the lens into a new composition", "a wipe-by reveal frozen on the new side", "tracking", "a shoulder or vehicle clearing to a changed scene", tags=("reveal",)),
        _move("move_reveal_focus_pull_in", "Focus-pull reveal in", "dollies in as focus throws from glass to the person beyond", "a focus-pull reveal frozen", "dolly in", "a dirty window going sharp on the figure inside", tags=("reveal", "compound")),
        _move("move_push_through_door", "Push through door", "pushes through a doorway on a stabilizer", "mid-door-push", "dolly in", "the frame catching both rooms for a beat of threshold"),
        _move("move_pull_out_door", "Pull out of door", "pulls backward through a doorway", "mid-door-pull", "dolly out", "the interior shrinking inside a dark jamb"),
        _move("move_around_corner", "Around the corner", "rounds a corner and discovers the next plane", "mid-corner-discover", "tracking", "a new hallway snapping into existence", tags=("reveal",)),
        _move("move_elevator_rise", "Elevator rise", "rises as if in an elevator cab, verticals true", "an elevator-rise frozen", "boom up", "floors of glass sliding down the frame like a count"),
        _move("move_elevator_drop", "Elevator drop", "drops as if in an elevator cab", "an elevator-drop frozen", "boom down", "the lobby floor rushing up to meet the boots"),
        _move("move_underwater_track", "Underwater track", "tracks underwater with a housed lens", "an underwater track frozen", "tracking", "caustics crawling over a body moving through blue", tags=("underwater",)),
        _move("move_underwater_rise", "Underwater rise", "rises underwater toward the sunlit surface", "an underwater rise frozen", "boom up", "the underside of the waves becoming a bright ceiling", tags=("underwater",)),
        _move("move_surface_breach", "Surface breach", "breaches from underwater into air", "a breach frozen at the waterline", "boom up", "droplets and a sudden dry world above the split", tags=("underwater", "reveal")),
        _move("move_macro_push", "Macro push", "pushes in at macro working distance", "a macro push frozen", "dolly in", "pores, weave, or condensation becoming landscape"),
        _move("move_probe_in", "Probe in", "slides a probe lens into a tight cavity", "a probe-in frozen", "dolly in", "a miniature interior opening around a tiny entrance"),
        _move("move_periscope_over", "Periscope over", "looks over a low wall with a periscope optic", "a periscope-over frozen", "boom up", "the far table appearing as if the camera had no body"),
        _move("move_tilt_up_dolly_in", "Tilt up while dollying in", "tilts up while dollying in", "mid-tilt-up-dolly-in", "dolly in", "rising attention and closer proximity in one move", tags=("compound",)),
        _move("move_pan_with_walk", "Pan with walk", "pans to keep a walker centered", "a pan-with-walk frozen", "pan", "background streaking while the stride stays planted in frame"),
        _move("move_counter_zoom_track", "Counter-zoom track", "tracks one way while a slow zoom opposes", "a counter-zoom track frozen", "tracking", "speed of background disagreeing with subject size", tags=("compound",)),
        _move("move_snorricam_body", "Body-mounted facing", "rides a rig facing the walker from their own chest", "a body-facing rig frozen", "tracking", "the world sliding behind a stable face and shoulders", tags=("pov",)),
        _move("move_low_mode_track", "Low-mode track", "tracks in low-mode with the lens near the floor", "a low-mode track frozen", "tracking", "shoes and dust kicking, ceiling running overhead"),
        _move("move_high_mode_track", "High-mode track", "tracks in high-mode above head height", "a high-mode track frozen", "tracking", "crowns and hats, the floor falling away"),
        _move("move_steeper_jib_up", "Steep jib up", "jibs up on a steep almost-vertical arc", "a steep jib-up frozen", "crane up", "going from worm's-eye to plan in one scoop"),
        _move("move_carousel_around_table", "Carousel around table", "circles a table at seated height", "a table carousel frozen", "orbit", "plates and faces trading the foreground chair by chair"),
        _move("move_reverse_crash_out", "Crash out", "crashes out on a fast dolly", "a crash-out frozen on a sudden wide", "dolly out", "the close face ripping to a wide isolation", tags=("energy",)),
        _move("move_zolly_horror", "Space-warp push", "combines a slow push with opposing zoom for dread", "a space-warp push frozen", "dolly zoom", "the hallway becoming a tunnel while the person does not grow", "move_dolly_in", tags=("compound",)),
        _move("move_timelapse_pan", "Timelapse pan", "pans across a long exposure sequence of the same place", "a timelapse pan frozen on one plate", "slow pan left", "clouds and crowds in streaks, architecture still", tags=("time",)),
        _move("move_hyperlapse_walk", "Hyperlapse walk", "advances in a hyperlapse along a path", "a hyperlapse frame frozen", "tracking", "the street jumping forward in stepped lockoffs", tags=("time",)),
        _move("move_orbit_and_rise", "Orbit and rise", "orbits while rising", "an orbit-and-rise frozen", "orbit", "the subject turning and shrinking as rooftops enter", tags=("compound", "drone")),
        _move("move_push_in_rack", "Push in with rack", "dollies in as focus racks from eyes to a foreground object", "a push-in-rack frozen", "dolly in", "the held object winning the plane as the face softens", tags=("compound",)),
        _move("move_pull_focus_track", "Track with follow-focus", "tracks while follow-focus holds the moving eyes", "a follow-focus track frozen", "tracking", "the walker sharp, background breathing in and out of plane", tags=("compound",)),
        _move("move_lock_off_then_whip", "Lock then whip", "holds locked, then whips to a new mark", "the pre-whip lock frozen", "whip pan right", "a still conversation then a violent redirect", "move_locked_off", tags=("compound", "energy")),
        _move("move_start_stop_dolly", "Start-stop dolly", "dollies in pulses, easing to dead stops", "a start-stop dolly frozen on a dead stop", "dolly in", "punctuation in the approach, not a constant glide", tags=("energy",)),
        _move("move_ease_in_pan", "Ease-in pan", "starts a pan from a dead stop with a long ease", "an ease-in pan frozen at the first inch", "pan left", "the street only just beginning to travel"),
        _move("move_ease_out_dolly", "Ease-out dolly", "ends a dolly with a long settle", "an ease-out dolly frozen on the settle", "dolly in", "the last inch of approach dying into a portrait"),
        _move("move_parallax_slide", "Parallax slide", "slides so near objects wipe faster than far towers", "a parallax slide frozen", "tracking", "a railing streaking, the bay almost still"),
        _move("move_vertigo_corridor", "Corridor stretch", "walks a long corridor with a slow opposing zoom", "a corridor-stretch frozen", "dolly zoom", "linoleum and doors receding unnaturally", tags=("compound",)),
        _move("move_helmet_cam", "Helmet cam", "rides a helmet-mounted lens", "a helmet-cam frozen", "tracking", "the visor edge and the next obstacle owning the frame", tags=("pov",)),
        _move("move_dash_forward", "Dash forward", "looks forward from a dash mount", "a dash-forward frozen", "tracking", "the road and wipers, city rushing the vanishing point", tags=("vehicle", "pov")),
        _move("move_bike_low", "Bike low mount", "rides a low bicycle or board mount", "a bike-low frozen", "tracking", "wheels, tar, and ankles at speed", tags=("vehicle",)),
        _move("move_wheelchair_smooth", "Chair-smooth track", "tracks from a wheelchair or doorway dolly, very smooth and low", "a chair-smooth track frozen", "tracking", "interior thresholds gliding at seated height"),
        _move("move_office_chair_whip", "Chair whip", "spins on a chair dolly for a fast orbit fragment", "a chair-whip orbit frozen", "orbit", "the room smearing around a seated subject", tags=("energy",)),
        _move("move_step_print_move", "Step-printed move", "moves with step-printed stutter on a simple pan", "a step-printed pan frozen", "pan left", "the street advancing in chopped increments", tags=("time",)),
        _move("move_drone_strafe", "Drone strafe", "strafes sideways at altitude without yawing", "a drone strafe frozen", "tracking", "facades sliding as if on a high slider", tags=("drone",)),
        _move("move_boom_over_bed", "Boom over bed", "booms over a bed or table from foot to overhead", "a boom-over-bed frozen", "crane up", "the recumbent figure going from profile to plan"),
        _move("move_entry_threshold", "Threshold enter", "crosses a threshold from dark exterior to lit interior", "a threshold-enter frozen", "dolly in", "exposure and color of the room blooming around the lens", tags=("reveal",)),
        _move("move_exit_threshold", "Threshold exit", "crosses from lit interior into night", "a threshold-exit frozen", "dolly out", "the warm room shrinking behind a dark street", tags=("reveal",)),
        _move("move_spiral_stair", "Spiral stair", "descends or climbs a spiral with the railing as a guide", "a spiral-stair move frozen", "tracking", "the well of the stair turning around a central void"),
        _move("move_crowd_part", "Crowd part", "pushes through a parting crowd on a stabilizer", "a crowd-part push frozen", "dolly in", "shoulders wiping either side of a path to a waiting face", tags=("reveal",)),
        _move("move_window_pass", "Window pass", "passes a window from outside, seeing in then out", "a window-pass frozen", "tracking", "interior lamp-light then reflection of the street", tags=("reveal",)),
        _move("move_mirror_slide", "Mirror slide", "slides along a mirror so the reflection rebuilds the room", "a mirror-slide frozen", "tracking", "the real room and its double trading dominance"),
        _move("move_over_shoulder_adjust", "Over-shoulder adjust", "makes a tiny lateral to dirty or clean an over-shoulder", "an OTS micro-adjust frozen", "tracking", "a cheek entering or leaving the foreground edge"),
        _move("move_push_to_insert", "Push to insert", "pushes from a medium into an insert of the hands", "a push-to-insert frozen on the hands", "dolly in", "the face leaving, the object becoming the scene"),
        _move("move_pull_to_wide", "Pull to wide", "pulls from a close face to a wide of the whole place", "a pull-to-wide frozen", "dolly out", "context arriving around a still expression"),
        _move("move_crane_kiss", "Crane kiss", "cranes down to a near-touch of a tabletop then stops", "a crane-kiss frozen above the surface", "crane down", "the last inch of air over glass or food"),
        _move("move_slider_vert", "Vertical slider", "slides vertically on a tower rail", "a vertical slider frozen", "boom up", "a poster or facade unrolling without a tilt"),
        _move("move_yaw_on_the_move", "Yaw while tracking", "yaws to a new subject while still tracking the first path", "a yaw-on-the-move frozen", "tracking", "attention leaving one walker for another without stopping", tags=("compound",)),
        _move("move_hidden_cut_move", "Hidden-cut move", "moves to a passing occluder meant to hide a join", "a hidden-cut move frozen on the occluder", "tracking", "a column or truck filling the frame as a seam", tags=("editing",)),
        _move("move_lock_off_breathing_iris", "Locked with breathing iris", "holds position while the iris breathes as a character", "a locked frame with a mid-iris breath", "fixed camera", "the world dimming and opening without a pan", tags=("locked",)),
        _move("move_mini_jib_food", "Mini-jib food", "scoops a tiny jib over a plate", "a mini-jib over food frozen", "crane down", "steam and garnish becoming the whole landscape"),
        _move("move_studio_ped_sit", "Studio pedestal sit", "sits a studio pedestal to seated eyeline", "a studio pedestal sit frozen", "boom down", "a talk setup dropping from standing host to guest height"),
        _move("move_studio_ped_stand", "Studio pedestal stand", "rises a studio pedestal to standing eyeline", "a studio pedestal stand frozen", "boom up", "the desk falling out as the host stands"),
        _move("move_remote_head_tilt", "Remote-head tilt", "tilts on a remote head at the end of a long arm", "a remote-head tilt frozen", "tilt down", "the operator nowhere near the lens, the view from a crane tongue"),
        _move("move_remote_head_pan_search", "Remote-head search", "pans a remote head hunting a mark from high up", "a remote-head search frozen", "pan left", "a high corner looking for a figure in a yard"),
        _move("move_slow_orbit_product", "Slow product orbit", "orbits a product at display speed", "a slow product orbit frozen", "orbit", "highlights walking around a bottle or device"),
        _move("move_snap_orbit_quarter", "Snap quarter orbit", "snaps a 90-degree orbit in one accent", "a snap quarter-orbit frozen", "orbit", "the three-quarter appearing as if cut, but moved", tags=("energy",)),
        _move("move_keep_horizon_run", "Horizon-locked run", "runs with a gimbal fighting to keep horizon", "a horizon-locked run frozen", "tracking", "legs pumping, skyline true, urgency without dutch", tags=("stabilized", "energy")),
        _move("move_drift_in_current", "Drift in current", "drifts with water current past a still subject", "a current-drift frozen", "tracking", "weeds and particles traveling while a rock or body holds", tags=("underwater",)),
        _move("move_boom_mic_avoid", "Boom-avoiding dip", "dips under an imagined boom then recovers", "a boom-avoid dip frozen", "tilt down", "the frame ducking then finding eyes again", tags=("compound",)),
        _move("move_call_and_answer_pan", "Call-and-answer pan", "pans from speaker to listener as a sentence lands", "a call-and-answer pan frozen on the listener", "pan right", "the first face leaving, the reaction arriving"),
        _move("move_match_speed_walk", "Match-speed walk", "matches walking speed exactly, background the only travel", "a match-speed walk frozen", "tracking", "the subject glued in frame, world sliding"),
        _move("move_under_speed_walk", "Under-speed walk", "tracks slower than the walk so the subject overtakes", "an under-speed walk frozen", "tracking", "the walker passing camera and receding", tags=("energy",)),
        _move("move_over_speed_walk", "Over-speed walk", "tracks faster than the walk so the camera overtakes", "an over-speed walk frozen", "tracking", "the lens pulling ahead and looking back"),
        _move("move_crane_sun_against", "Crane against sun", "cranes up into a backlit sun flare", "a crane-against-sun frozen", "crane up", "the figure going to silhouette as the sky floods", tags=("reveal",)),
        _move("move_night_practical_push", "Night practical push", "pushes toward a practical lamp that becomes the key", "a night practical push frozen", "dolly in", "a porch light blooming as the face enters its pool"),
        _move("move_rain_windshield", "Rain windshield", "looks through a rained windshield with wipers", "a rained windshield frozen", "tracking", "drops and arcs of the wiper as the road smears", tags=("vehicle",)),
        _move("move_two_shot_rebalance", "Two-shot rebalance", "slides to rebalance a two-shot as one person sits", "a two-shot rebalance frozen", "tracking", "empty air filling where a standing body just was"),
        _move("move_close_circle_face", "Close face circle", "orbits very close around a face", "a close face-circle frozen", "orbit", "pores and ear giving way to profile, background a ring of blur"),
        _move("move_god_view_drop", "God-view drop", "drops from a high plan toward a single person", "a god-view drop frozen", "crane down", "the crowd becoming one readable figure", tags=("drone",)),
        _move("move_exit_frame_hold", "Hold after exit", "holds locked after the subject leaves frame", "an empty-frame hold after an exit", "fixed camera", "the place continuing without them", tags=("locked",)),
        _move("move_enter_frame_hold", "Hold before enter", "holds locked on empty space until someone enters", "a pre-enter empty hold", "fixed camera", "the doorway waiting", tags=("locked",)),
        _move("move_snorricam_hands", "Hands-forward body rig", "points a body rig at the hands working", "hands-forward body rig frozen", "tracking", "tools in the lower frame, world sliding beyond the wrists", tags=("pov",)),
        _move("move_pocket_peek", "Pocket peek", "rises from a pocket or bag height to the street", "a pocket-peek rise frozen", "boom up", "fabric then sudden city", tags=("reveal", "pov")),
        _move("move_table_surface_slide", "Table-surface slide", "slides at tabletop height along a spread of objects", "a table-surface slide frozen", "tracking", "glassware and cards wiping the near field"),
        _move("move_bookshelf_track", "Bookshelf track", "tracks along a shelf of unmarked spines", "a bookshelf track frozen", "tracking", "wood and paper rhythm, a face waiting at the aisle end"),
        _move("move_industrial_catwalk", "Catwalk track", "tracks a high industrial catwalk", "a catwalk track frozen", "tracking", "grate floor and a drop to machinery on both sides"),
        _move("move_fog_in", "Push into fog", "pushes into thickening fog until the subject is a shape", "a push-into-fog frozen", "dolly in", "depth collapsing to tone", tags=("atmosphere",)),
        _move("move_fog_out", "Pull out of fog", "pulls out of fog into readable air", "a pull-out-of-fog frozen", "dolly out", "edges returning to the world", tags=("atmosphere", "reveal")),
        _move("move_sparkler_orbit", "Spark-orbit", "orbits a handheld sparkler or spark source", "a spark-orbit frozen", "orbit", "ember trails wrapping a silhouette", tags=("energy",)),
        _move("move_candle_approach", "Candle approach", "approaches a single candle until it floods the lens", "a candle approach frozen", "dolly in", "the flame becoming the whole exposure"),
        _move("move_stage_bow_out", "Stage bow-out", "dollies out down an aisle as if leaving a stage", "a stage bow-out frozen", "dolly out", "a figure shrinking in lights, rows entering the sides"),
        _move("move_aisle_procession", "Aisle procession", "tracks down a center aisle toward an altar or desk", "an aisle procession frozen", "tracking", "symmetry pulling the eye to the far plane"),
        _move("move_loading_dock_strafe", "Dock strafe", "strafes a loading dock at truck-bed height", "a dock strafe frozen", "tracking", "bumpers and bays counting off"),
        _move("move_mezzanine_slide", "Mezzanine slide", "slides a mezzanine railing looking down", "a mezzanine slide frozen", "tracking", "the floor below traveling under a banister"),
        _move("move_skater_low", "Skater low", "rides a very low board-height lens", "a skater-low frozen", "tracking", "coping and asphalt at cheek height", tags=("energy", "vehicle")),
        _move("move_float_invisible_stick", "Floating stick", "floats as if on a hidden selfie stick, no operator body", "a floating-stick frozen", "orbit", "the subject with empty air where a stick would be", tags=("viral", "stabilized")),
        _move("move_bullet_orbit_freeze", "Orbit freeze", "orbits while time feels frozen on the subject", "an orbit-freeze frozen", "orbit", "clothing and spray hanging while the background travels", tags=("time", "compound")),
        _move("move_crash_zoom_on_move", "Move then crash zoom", "tracks then crash-zooms the last beat", "a move-then-crash-zoom frozen on the punch", "crash zoom", "a walk landing in a sudden tight face", "move_dolly_in", "fx_crash_zoom", tags=("energy", "compound")),
        _move("move_locked_off_zoom", "Locked zoom", "zooms on a locked tripod, no body move", "a locked zoom frozen mid-magnify", "zoom in", "compression changing while the nodal point holds", "move_dolly_in", tags=("locked",)),
        _move("move_snap_zoom_in", "Snap zoom in", "snap-zooms in on a locked support", "a snap-zoom-in frozen", "crash zoom", "the face punching larger in one optical hit", "move_dolly_in", "fx_crash_zoom", tags=("energy",)),
        _move("move_snap_zoom_out", "Snap zoom out", "snap-zooms out on a locked support", "a snap-zoom-out frozen", "zoom out", "context slamming around a face", tags=("energy",)),
        _move("move_live_switcher_pan", "Switcher pan", "pans as if a live-event camera finding a mark", "a switcher pan frozen", "pan right", "a stage finding the next speaker from a house position"),
        _move("move_house_left_push", "House-left push", "pushes from house left toward a stage", "a house-left push frozen", "dolly in", "audience heads as foreground, a figure growing on stage"),
        _move("move_wings_reveal", "Wings reveal", "slides out from stage wings", "a wings reveal frozen", "tracking", "black masking giving way to lights and an audience", tags=("reveal",)),
        _move("move_follow_spotlight_feel", "Follow-spot feel", "tilts and pans as if chasing a follow-spot beam", "a follow-spot chase frozen", "pan", "the bright pool moving, the camera glued to it"),
        _move("move_security_pan", "Security pan", "pans slowly like a high-corner security head", "a security pan frozen", "slow pan left", "a room surveyed from the ceiling corner, slightly wide and cold", tags=("locked",)),
        _move("move_baby_mobile_orbit", "Over-crib orbit", "orbits slowly above a crib or small bed", "an over-crib orbit frozen", "orbit", "mobiles and a small recumbent figure in plan"),
        _move("move_kitchen_pass", "Kitchen pass", "tracks a pass-through from kitchen to dining", "a kitchen-pass frozen", "tracking", "steam and plates traveling into the next room"),
        _move("move_service_corridor", "Service corridor", "tracks a narrow service corridor", "a service-corridor track frozen", "tracking", "pipes, scuff, and a vanishing point of doors"),
        _move("move_garden_hedge_wipe", "Hedge wipe", "tracks behind a hedge that wipes to a lawn", "a hedge-wipe frozen", "tracking", "leaves then sudden open grass", tags=("reveal",)),
        _move("move_pier_out", "Pier dolly out", "dollies backward along a pier", "a pier dolly-out frozen", "dolly out", "the walker shrinking, water widening on both sides"),
        _move("move_pier_in", "Pier dolly in", "dollies in along a pier toward a waiting figure", "a pier dolly-in frozen", "dolly in", "planks rushing, a silhouette growing against the bay"),
        _move("move_switchback_drone", "Switchback drone", "follows a mountain switchback from above", "a switchback-drone frozen", "tracking", "hairpin road and a tiny traveler", tags=("drone",)),
        _move("move_wave_level", "Wave-level track", "tracks at the height of breaking water", "a wave-level track frozen", "tracking", "foam and a body in the same plane", tags=("underwater",)),
        _move("move_train_window", "Train window", "looks out a train window with passing world", "a train-window frozen", "tracking", "poles and fields strobing, interior reflection faint", tags=("vehicle",)),
        _move("move_subway_lurch", "Subway lurch", "handheld in a lurching subway car", "a subway lurch frozen", "handheld", "straps and poles, the floor not agreeing with the horizon", tags=("handheld", "vehicle")),
        _move("move_escalator_ride", "Escalator ride", "rides an escalator, looking with the rise", "an escalator-ride frozen", "boom up", "steps and a mall or station opening above"),
        _move("move_down_escalator", "Down escalator", "rides an escalator down", "a down-escalator frozen", "boom down", "a concourse rising to meet the lens"),
        _move("move_carousel_horse", "Fairground circle", "circles as if on a fairground ride", "a fairground circle frozen", "orbit", "lights smearing, a face returning every turn", tags=("energy",)),
        _move("move_ferris_rise", "Ferris rise", "rises on a long slow arc like a ferris chair", "a ferris-rise frozen", "crane up", "the fairground shrinking, wind and city arriving", tags=("compound",)),
        _move("move_locked_off_cloud", "Locked cloud", "locks off on sky so only clouds move", "a locked cloud still with streaked weather implied", "fixed camera", "architecture as a silhouette against traveling weather", tags=("locked", "time")),
        _move("move_push_into_eyes", "Push into eyes", "dollies until the eyes are the whole story", "a push-into-eyes frozen", "dolly in", "iris, catchlight, and almost no face left"),
        _move("move_pull_to_solitude", "Pull to solitude", "pulls until the person is small in a huge place", "a pull-to-solitude frozen", "dolly out", "architecture and weather dwarfing a single body"),
    ]
    if len(rows) < 100:
        raise SystemExit(f"camera_movement {len(rows)} < 100")
    return rows


def main() -> None:
    OUT.mkdir(parents=True, exist_ok=True)
    _dump("camera_movement.json", camera_movement())


if __name__ == "__main__":
    main()
