"""Creator pack 3: 100 shipped lab Apps for working content creators.

Not collected by pytest (leading underscore). Tests and the builder import
``PACK3``. Keep this module data-only.
"""

from __future__ import annotations

from dataclasses import dataclass


@dataclass(frozen=True)
class Pack3Spec:
    """One creator-pack graph.

    Attributes:
        rel: ``extra.lab_rel`` (``klein/creator/youtube-channel-icon``).
        kind: ``klein_single`` | ``klein_pack`` | ``wan_i2v`` | ``wan_loop`` | ``ltx_av``.
        group: Catalog section id.
        size: Width x height latent pixels.
        prefix: Primary SaveImage / VHS filename prefix.
        occupancy: ``klein`` | ``wan`` | ``ltx``.
        sample_catalog: Existing sample index id.
        title: One-line job for Notes and catalog.
        lock: Job-specific framing appended to the family identity.
        handoff: Downstream lab ids.
        enhance_pin: True pins Prompt Enhance off.
        template: Klein ``hero``/``draft``, or a video source rel.
        identity: ``creator`` | ``product`` | ``food`` | ``desk`` | ``stream``.
        prefixes: Pack SaveImage prefixes (klein_pack).
        shots: Pack (prefix, label, shot-card) rows.
        persist: ``view`` or ``state`` for packs.
        ltx_mode: ``i2v`` or ``t2v``.
        audio_hint: LTX world-SFX widget.
        portrait: True uses 9:16 Wan/LTX printers.
    """

    rel: str
    kind: str
    group: str
    size: tuple[int, int]
    prefix: str
    occupancy: str
    sample_catalog: str
    title: str
    lock: str
    handoff: tuple[str, ...] = ()
    enhance_pin: bool = False
    template: str = "hero"
    identity: str = "creator"
    prefixes: tuple[str, ...] = ()
    shots: tuple[tuple[str, str, str], ...] = ()
    persist: str = "view"
    ltx_mode: str = "i2v"
    audio_hint: str = "world SFX matching the shot, no score"
    portrait: bool = False


def _k(
    stem: str,
    w: int,
    h: int,
    prefix: str,
    group: str,
    title: str,
    lock: str,
    *,
    catalog: str = "klein_t2i",
    handoff: tuple[str, ...] = (),
    template: str | None = None,
    identity: str = "creator",
) -> Pack3Spec:
    """Klein single-plate spec."""
    if template is None:
        template = "draft" if h >= 960 or (h > w) else "hero"
    return Pack3Spec(
        rel=f"klein/creator/{stem}",
        kind="klein_single",
        group=group,
        size=(w, h),
        prefix=prefix,
        occupancy="klein",
        sample_catalog=catalog,
        title=title,
        lock=lock,
        handoff=handoff,
        template=template,
        identity=identity,
    )


def _pack(
    stem: str,
    w: int,
    h: int,
    prefix: str,
    group: str,
    title: str,
    shots: tuple[tuple[str, str, str], ...],
    *,
    persist: str = "view",
    identity: str = "creator",
    catalog: str = "klein_t2i",
    handoff: tuple[str, ...] = (),
) -> Pack3Spec:
    """Klein multi-save pack."""
    return Pack3Spec(
        rel=f"klein/creator/{stem}",
        kind="klein_pack",
        group=group,
        size=(w, h),
        prefix=prefix,
        occupancy="klein",
        sample_catalog=catalog,
        title=title,
        lock="",
        handoff=handoff,
        prefixes=tuple(row[0] for row in shots),
        shots=shots,
        persist=persist,
        identity=identity,
        template="hero",
    )


def _w(
    stem: str,
    w: int,
    h: int,
    prefix: str,
    group: str,
    title: str,
    lock: str,
    *,
    loop: bool = False,
    catalog: str | None = None,
    handoff: tuple[str, ...] = (),
) -> Pack3Spec:
    """Wan silent I2V or ping-pong loop."""
    portrait = h > w
    return Pack3Spec(
        rel=f"wan/creator/{stem}",
        kind="wan_loop" if loop else "wan_i2v",
        group=group,
        size=(w, h),
        prefix=prefix,
        occupancy="wan",
        sample_catalog=catalog or ("wan_loop" if loop else "wan_i2v"),
        title=title,
        lock=lock,
        handoff=handoff,
        enhance_pin=True,
        portrait=portrait,
        template="wan/gif-loop" if loop else ("wan/shorts-still-5s" if portrait else "wan/still-to-video-5s"),
    )


def _l(
    stem: str,
    w: int,
    h: int,
    prefix: str,
    group: str,
    title: str,
    lock: str,
    *,
    mode: str = "i2v",
    catalog: str | None = None,
    audio: str = "world SFX matching the shot, no score",
    handoff: tuple[str, ...] = (),
) -> Pack3Spec:
    """LTX AV ~5 s."""
    portrait = h > w
    if catalog is None:
        catalog = "ltx_broll" if mode == "t2v" else "ltx_i2v"
    src = "ltx/shorts-still-5s" if portrait else ("ltx/text-to-video-5s" if mode == "t2v" else "ltx/still-to-video-5s")
    return Pack3Spec(
        rel=f"ltx/creator/{stem}",
        kind="ltx_av",
        group=group,
        size=(w, h),
        prefix=prefix,
        occupancy="ltx",
        sample_catalog=catalog,
        title=title,
        lock=lock,
        handoff=handoff,
        ltx_mode=mode,
        audio_hint=audio,
        portrait=portrait,
        template=src,
    )


_CIRCLE = (
    "Subject centered in a circular safe area so corners may crop. Empty of lettering."
)
_UI_916 = (
    "Vertical 9:16. Keep the subject in the middle third; top and bottom stay quiet "
    "for platform UI. Empty of lettering."
)
_CTA = (
    "Generous empty lower-right for a button later. Empty of lettering and UI chrome."
)
_LEFT = (
    "Subject left-weighted; quiet right third for tiles later. Empty of lettering."
)
_CENTER_BAND = (
    "16:9 channel art. Keep the subject in the horizontal center band; top and bottom "
    "may crop on phones. Empty of lettering."
)
_OVERLAY = (
    "16:9 stream overlay. Right third empty for a webcam. Empty of lettering and chrome."
)
_WAVE = (
    "Quiet lower fifth for a waveform overlay later. Empty of lettering."
)
_TYPE = (
    "Quiet center for overlay type later. Empty of lettering."
)

_IG_CAROUSEL = (
    ("ez_ig_c01", "HOOK", "Opening still. Subject large, 35mm, eye level. Quiet edges."),
    ("ez_ig_c02", "BEAT", "Second beat. Step closer, 50mm. Same wardrobe and light."),
    ("ez_ig_c03", "DETAIL", "Detail still. Hands or prop, 85mm. Same place."),
    ("ez_ig_c04", "WIDE", "Wide establishing. 24mm, more terrace and towers."),
    ("ez_ig_c05", "CLOSE", "Close closer. Face and coat, 85mm, same golden hour."),
)
_IG_GRID = (
    ("ez_ig_g01", "LEFT", "Left grid tile. Subject on the right third of this square."),
    ("ez_ig_g02", "CENTER", "Center grid tile. Subject centered, same light."),
    ("ez_ig_g03", "RIGHT", "Right grid tile. Subject on the left third of this square."),
)
_LI_CAROUSEL = (
    ("ez_li_c01", "COVER", "Cover still. Subject large, quiet lower band for a title."),
    ("ez_li_c02", "POINT", "Point two. Same person, 35mm, a second gesture."),
    ("ez_li_c03", "PROOF", "Proof still. Prop or desk detail, 50mm."),
    ("ez_li_c04", "SCENE", "Scene still. Wider 24mm of the same terrace."),
    ("ez_li_c05", "CLOSE", "Close still. 85mm, same coat and light."),
)
_MOODBOARD = (
    ("ez_mood_c01", "HERO", "Hero still. 35mm, eye level, golden hour."),
    ("ez_mood_c02", "WIDE", "Wide world. 24mm, more city and bay."),
    ("ez_mood_c03", "DETAIL", "Wardrobe detail. 85mm on the coat seam."),
    ("ez_mood_c04", "PROP", "Prop still. Data-staff and glyph rings, 50mm."),
    ("ez_mood_c05", "PLACE", "Place still. Terrace palms, no person, 24mm."),
    ("ez_mood_c06", "CLOSE", "Portrait close. 85mm, same identity."),
)
_BRAND = (
    ("ez_brand_01", "KEY", "Canonical key-light plate. 35mm, warm key."),
    ("ez_brand_02", "COOL", "Same camera. Cooler window fill, same pose."),
    ("ez_brand_03", "NIGHT", "Same camera. Night practicals, same pose."),
    ("ez_brand_04", "HIGH", "Same camera. High-key noon, same pose."),
)

PACK3: tuple[Pack3Spec, ...] = (
    _k(
        "youtube-channel-icon",
        768,
        768,
        "ez_yt_icon",
        "youtube",
        "YouTube channel icon, circle-safe 1:1",
        _CIRCLE,
        template="hero",
    ),
    _k(
        "youtube-channel-art",
        1536,
        864,
        "ez_yt_art",
        "youtube",
        "YouTube channel art 16:9 with a mobile-safe center band",
        _CENTER_BAND,
        template="hero",
    ),
    _k(
        "youtube-shorts-thumb",
        576,
        1024,
        "ez_yt_shorts_thumb",
        "youtube",
        "YouTube Shorts thumbnail 9:16",
        _UI_916,
        handoff=("wan/creator/zoom-punch",),
    ),
    _k(
        "youtube-community",
        1024,
        1024,
        "ez_yt_community",
        "youtube",
        "YouTube Community post 1:1",
        "Square community still. Subject large, quiet edges. Empty of lettering.",
        template="hero",
    ),
    _k(
        "youtube-chapter-card",
        1280,
        720,
        "ez_yt_chapter",
        "youtube",
        "YouTube chapter plate 16:9",
        "Quiet lower band for a chapter title later. Empty of lettering.",
        template="hero",
    ),
    _k(
        "youtube-subscribe-plate",
        1280,
        720,
        "ez_yt_sub",
        "youtube",
        "Subscribe-safe end plate 16:9",
        _CTA,
        template="hero",
        handoff=("wan/creator/youtube-subscribe-bump",),
    ),
    _k(
        "youtube-end-screen",
        1280,
        720,
        "ez_yt_endscreen",
        "youtube",
        "YouTube end-screen plate, left-weighted",
        _LEFT,
        template="hero",
        handoff=("ltx/creator/youtube-outro-av",),
    ),
    _k(
        "instagram-portrait",
        1024,
        1280,
        "ez_ig_portrait",
        "instagram",
        "Instagram 4:5 feed still",
        "Instagram 4:5 portrait. Subject large, warm key. Empty of lettering.",
        handoff=("wan/creator/instagram-story-loop", "ltx/creator/instagram-reel-lifestyle"),
    ),
    _k(
        "instagram-landscape",
        1216,
        640,
        "ez_ig_land",
        "instagram",
        "Instagram landscape feed ~1.91:1",
        "Wide feed still. Horizon low, subject left-weighted. Empty of lettering.",
        template="hero",
    ),
    _k(
        "instagram-story",
        576,
        1024,
        "ez_ig_story",
        "instagram",
        "Instagram Story 9:16 with UI-safe edges",
        _UI_916,
        handoff=("wan/creator/instagram-story-loop",),
    ),
    _k(
        "instagram-reel-cover",
        576,
        1024,
        "ez_ig_reel",
        "instagram",
        "Instagram Reel cover, center-weighted for the grid crop",
        "Vertical 9:16 Reel cover. Subject centered vertically so a 3:4 grid crop keeps the face.",
        handoff=("ltx/creator/instagram-reel-lifestyle",),
    ),
    _k(
        "instagram-highlight",
        768,
        768,
        "ez_ig_highlight",
        "instagram",
        "Instagram Highlight cover, circle-safe",
        _CIRCLE,
        template="hero",
    ),
    _k(
        "instagram-profile",
        768,
        768,
        "ez_ig_profile",
        "instagram",
        "Instagram profile photo, circle-safe",
        _CIRCLE,
        template="hero",
    ),
    _pack(
        "instagram-carousel-5",
        1024,
        1280,
        "ez_ig_c01",
        "instagram",
        "Instagram 4:5 carousel, five slides",
        _IG_CAROUSEL,
        handoff=("wan/creator/paper-flip",),
    ),
    _pack(
        "instagram-grid-3up",
        1024,
        1024,
        "ez_ig_g01",
        "instagram",
        "Instagram 1:1 three-tile grid row",
        _IG_GRID,
    ),
    _k(
        "tiktok-cover",
        576,
        1024,
        "ez_tt_cover",
        "tiktok",
        "TikTok cover 9:16",
        _UI_916,
        handoff=("wan/creator/tiktok-hook", "ltx/creator/tiktok-broll"),
    ),
    _k(
        "tiktok-shop",
        1024,
        1024,
        "ez_tt_shop",
        "tiktok",
        "TikTok Shop packshot 1:1",
        "Clean product on a seamless light-gray cyclorama, soft studio key, unmarked.",
        catalog="klein_product",
        identity="product",
        template="hero",
        handoff=("wan/creator/product-spin",),
    ),
    _k(
        "x-post",
        1280,
        720,
        "ez_x_post",
        "x",
        "X in-stream still 16:9",
        "Landscape in-feed still. Subject large, readable at small sizes. Empty of lettering.",
        template="hero",
        handoff=("wan/creator/x-post-5s",),
    ),
    _k(
        "x-header",
        1536,
        512,
        "ez_x_header",
        "x",
        "X header 3:1",
        "Ultra-wide header. Horizon low, empty sky band. Empty of lettering.",
        template="hero",
    ),
    _k(
        "x-card",
        1216,
        640,
        "ez_x_card",
        "x",
        "X link-card still ~1.91:1",
        "Wide card still. Subject left-weighted, quiet right third. Empty of lettering.",
        template="hero",
    ),
    _k(
        "linkedin-post",
        1024,
        1024,
        "ez_li_post",
        "linkedin",
        "LinkedIn square post 1:1",
        "Square professional still. Subject large, clean light. Empty of lettering.",
        template="hero",
    ),
    _k(
        "linkedin-landscape",
        1216,
        640,
        "ez_li_land",
        "linkedin",
        "LinkedIn landscape post ~1.91:1",
        "Wide professional still. Quiet right third for a headline later.",
        template="hero",
    ),
    _k(
        "linkedin-banner",
        1536,
        384,
        "ez_li_banner",
        "linkedin",
        "LinkedIn personal banner 4:1",
        "Ultra-wide 4:1 banner. Subject in the right half; left stays simple.",
        template="hero",
    ),
    _k(
        "linkedin-article",
        1216,
        640,
        "ez_li_article",
        "linkedin",
        "LinkedIn article cover ~1.91:1",
        "Article hero. Subject left-weighted, quiet right third. Empty of lettering.",
        template="hero",
    ),
    _pack(
        "linkedin-carousel-5",
        1024,
        1024,
        "ez_li_c01",
        "linkedin",
        "LinkedIn document carousel, five squares",
        _LI_CAROUSEL,
    ),
    _k(
        "pinterest-pin",
        768,
        1152,
        "ez_pin",
        "pinterest",
        "Pinterest standard pin 2:3",
        "Tall 2:3 pin. Subject in the upper two-thirds, quiet lower band. Empty of lettering.",
    ),
    _k(
        "pinterest-story",
        576,
        1024,
        "ez_pin_story",
        "pinterest",
        "Pinterest Idea Pin 9:16",
        _UI_916,
    ),
    _k(
        "facebook-post",
        1216,
        640,
        "ez_fb_post",
        "meta",
        "Facebook shared-image still ~1.91:1",
        "Wide shared-image still. Subject large, quiet edges. Empty of lettering.",
        template="hero",
    ),
    _k(
        "threads-portrait",
        1024,
        1280,
        "ez_threads",
        "meta",
        "Threads 4:5 still",
        "Threads 4:5 portrait. Subject large, warm key. Empty of lettering.",
    ),
    _k(
        "twitch-offline",
        1280,
        720,
        "ez_tw_off",
        "twitch",
        "Twitch offline screen 16:9",
        _TYPE,
        template="hero",
        identity="stream",
    ),
    _k(
        "twitch-starting",
        1280,
        720,
        "ez_tw_start",
        "twitch",
        "Twitch starting-soon screen 16:9",
        _TYPE,
        template="hero",
        identity="stream",
        handoff=("wan/creator/twitch-starting-loop", "ltx/creator/twitch-starting-av"),
    ),
    _k(
        "twitch-brb",
        1280,
        720,
        "ez_tw_brb",
        "twitch",
        "Twitch BRB screen 16:9",
        _TYPE,
        template="hero",
        identity="stream",
        handoff=("wan/creator/twitch-brb-loop",),
    ),
    _k(
        "twitch-ending",
        1280,
        720,
        "ez_tw_end",
        "twitch",
        "Twitch stream-ending screen 16:9",
        _TYPE,
        template="hero",
        identity="stream",
    ),
    _k(
        "twitch-overlay",
        1280,
        720,
        "ez_tw_overlay",
        "twitch",
        "Twitch webcam-hole overlay 16:9",
        _OVERLAY,
        template="hero",
        identity="stream",
    ),
    _k(
        "twitch-panel",
        768,
        1024,
        "ez_tw_panel",
        "twitch",
        "Twitch about-panel art",
        "Tall panel still. Subject in the upper half, quiet lower band. Empty of lettering.",
        identity="stream",
    ),
    _k(
        "twitch-profile",
        768,
        768,
        "ez_tw_profile",
        "twitch",
        "Twitch profile photo, circle-safe",
        _CIRCLE,
        template="hero",
        identity="stream",
    ),
    _k(
        "twitch-banner",
        1536,
        512,
        "ez_tw_banner",
        "twitch",
        "Twitch channel banner ~3:1",
        "Ultra-wide banner. Horizon low, empty sky band. Empty of lettering.",
        template="hero",
        identity="stream",
    ),
    _k(
        "spotify-playlist",
        1024,
        1024,
        "ez_spot_pl",
        "spotify",
        "Spotify playlist cover 1:1",
        "Square playlist cover. Bold subject, quiet corners. Empty of lettering.",
        template="hero",
    ),
    _k(
        "spotify-canvas-still",
        576,
        1024,
        "ez_spot_still",
        "spotify",
        "Spotify Canvas still 9:16 (silent JPG stand-in)",
        "Vertical 9:16 Canvas still. No talking, no lettering. Subject in the middle third.",
        handoff=("wan/creator/spotify-canvas",),
    ),
    _k(
        "album-cover",
        1024,
        1024,
        "ez_album",
        "spotify",
        "Release / album cover 1:1",
        "Square album cover. Bold subject, unmarked surfaces. Empty of lettering.",
        template="hero",
    ),
    _k(
        "lyric-card",
        1024,
        1024,
        "ez_lyric",
        "spotify",
        "Lyric-card background 1:1",
        _TYPE,
        template="hero",
        handoff=("wan/creator/lyric-bg-loop",),
    ),
    _k(
        "audiogram-wide",
        1280,
        720,
        "ez_ag_wide",
        "podcast",
        "Audiogram background 16:9",
        _WAVE,
        template="hero",
        identity="desk",
    ),
    _k(
        "audiogram-vert",
        576,
        1024,
        "ez_ag_vert",
        "podcast",
        "Audiogram background 9:16",
        "Vertical audiogram. Quiet lower third for a waveform. Empty of lettering.",
        identity="desk",
    ),
    _k(
        "episode-art",
        1024,
        1024,
        "ez_episode",
        "podcast",
        "Per-episode podcast art 1:1",
        "Square episode art. One prop story, unmarked. Empty of lettering.",
        template="hero",
        identity="desk",
    ),
    _k(
        "merch-tee",
        1024,
        1024,
        "ez_tee",
        "merch",
        "Unmarked tee mock 1:1",
        "Photoreal tee on a hanger against seamless gray. Unmarked fabric, no logos.",
        catalog="klein_product",
        identity="product",
        template="hero",
    ),
    _k(
        "merch-mug",
        1024,
        1024,
        "ez_mug_merch",
        "merch",
        "Merch mug mock 1:1",
        "Photoreal ceramic mug three-quarter view on seamless gray. Unmarked, no logos.",
        catalog="klein_product",
        identity="product",
        template="hero",
    ),
    _k(
        "poster-portrait",
        768,
        1152,
        "ez_poster",
        "merch",
        "Print poster 2:3",
        "Tall poster still. Subject in the upper two-thirds, quiet lower band for type.",
    ),
    _k(
        "slide-title",
        1280,
        720,
        "ez_slide",
        "slides",
        "Course / webinar title plate 16:9",
        _TYPE,
        template="hero",
    ),
    _k(
        "zoom-bg",
        1280,
        720,
        "ez_zoom",
        "slides",
        "Webcam-safe Zoom / Meet background 16:9",
        "16:9 background. Center stays simple for a webcam. Empty of lettering.",
        template="hero",
        identity="desk",
    ),
    _k(
        "email-header",
        1216,
        640,
        "ez_email",
        "web",
        "Newsletter / email header ~1.91:1",
        "Wide email header. Subject left-weighted, quiet right third. Empty of lettering.",
        template="hero",
    ),
    _k(
        "substack-hero",
        1216,
        640,
        "ez_substack",
        "web",
        "Substack / blog hero ~1.91:1",
        "Wide blog hero. Subject left-weighted, quiet right third. Empty of lettering.",
        template="hero",
    ),
    _k(
        "patreon-post",
        1024,
        1280,
        "ez_patreon",
        "web",
        "Membership post still 4:5",
        "4:5 membership still. Subject large, warm key. Empty of lettering.",
    ),
    _k(
        "product-lifestyle",
        1024,
        1280,
        "ez_lifestyle",
        "production",
        "In-use product lifestyle 4:5",
        "Lifestyle still of an unmarked ceramic mug in use on a sunlit table. No cyclorama.",
        catalog="klein_product",
        identity="product",
        handoff=("wan/creator/unbox-hands",),
    ),
    _k(
        "desk-setup",
        1280,
        720,
        "ez_desk",
        "production",
        "Workspace establishing still 16:9",
        "Photoreal desk setup, oak and linen, unmarked screens. Empty of lettering.",
        template="hero",
        identity="desk",
        handoff=("wan/creator/screen-bg-loop", "ltx/creator/desk-work"),
    ),
    _pack(
        "moodboard-6up",
        768,
        432,
        "ez_mood_c01",
        "production",
        "Six-still moodboard of one identity",
        _MOODBOARD,
    ),
    _pack(
        "brand-kit-4",
        768,
        432,
        "ez_brand_01",
        "production",
        "Four brand plates, same camera, different lights",
        _BRAND,
        persist="state",
    ),
    _k(
        "coming-soon",
        1280,
        720,
        "ez_soon",
        "production",
        "Launch / coming-soon plate 16:9",
        _TYPE,
        template="hero",
    ),
    _w(
        "youtube-subscribe-bump",
        832,
        480,
        "ez_yt_bump",
        "wan",
        "Silent YouTube subscribe bumper loop",
        "Tiny cyclic shimmer on the subject. Ping-pong friendly. No walk, no dolly.",
        loop=True,
    ),
    _w(
        "instagram-story-loop",
        480,
        832,
        "ez_ig_loop",
        "wan",
        "Silent Instagram Story loop 9:16",
        "Locked-camera breeze in fabric and palms. Ping-pong friendly. No walk.",
        loop=True,
        handoff=("ltx/creator/instagram-reel-lifestyle",),
    ),
    _w(
        "tiktok-hook",
        480,
        832,
        "ez_tt_hook",
        "wan",
        "Silent TikTok hook punch 9:16",
        "Fast push-in toward the start-image face. One continuous take. No cut.",
        handoff=("ltx/creator/tiktok-broll",),
    ),
    _w(
        "x-post-5s",
        832,
        480,
        "ez_x_video",
        "wan",
        "Silent X clip ~5 s 16:9",
        "Gentle push-in. Fabric and foliage drift. One continuous five-second take.",
    ),
    _w(
        "twitch-starting-loop",
        832,
        480,
        "ez_tw_start_loop",
        "wan",
        "Silent starting-soon loop 16:9",
        "Slow cyclic light pulse on a quiet set. Ping-pong friendly. No walk.",
        loop=True,
        handoff=("ltx/creator/twitch-starting-av",),
    ),
    _w(
        "twitch-brb-loop",
        832,
        480,
        "ez_tw_brb_loop",
        "wan",
        "Silent BRB loop 16:9",
        "Soft looping idle on a quiet set. Ping-pong friendly. No walk.",
        loop=True,
    ),
    _w(
        "spotify-canvas",
        480,
        832,
        "ez_spot_canvas",
        "wan",
        "Silent Spotify Canvas rebound 9:16",
        "Seamless rebound loop. No talking, no singing, no lettering. Locked camera.",
        loop=True,
    ),
    _w(
        "lyric-bg-loop",
        832,
        480,
        "ez_lyric_loop",
        "wan",
        "Silent lyric-background loop 16:9",
        "Slow drift of light on a quiet scene. Ping-pong friendly. Center stays simple.",
        loop=True,
    ),
    _w(
        "product-spin",
        832,
        480,
        "ez_spin",
        "wan",
        "Silent product orbit ~5 s",
        "Slow orbit around the start-image product. Table holds. No cut.",
        handoff=("ltx/product-hero",),
    ),
    _w(
        "unbox-hands",
        832,
        480,
        "ez_unbox",
        "wan",
        "Silent unbox / hands motion ~5 s",
        "Hands ease a box open. Slow, locked identity. One continuous take.",
        handoff=("ltx/creator/product-unbox-av",),
    ),
    _w(
        "steam-loop",
        832,
        480,
        "ez_steam",
        "wan",
        "Silent steam / kettle loop",
        "Soft steam rises from a mug. Locked camera. Ping-pong friendly.",
        loop=True,
    ),
    _w(
        "candle-loop",
        832,
        480,
        "ez_candle",
        "wan",
        "Silent candle-flicker loop",
        "A candle flame loops. Locked camera. Ping-pong friendly.",
        loop=True,
    ),
    _w(
        "light-leak-loop",
        832,
        480,
        "ez_leak",
        "wan",
        "Silent light-leak overlay loop",
        "Warm light leak drifts across the frame. Ping-pong friendly. No subject walk.",
        loop=True,
    ),
    _w(
        "logo-sting",
        832,
        480,
        "ez_sting",
        "wan",
        "Silent logo sting ~5 s",
        "A short push-in toward the start-image mark. No lettering. One take.",
    ),
    _w(
        "ken-burns",
        832,
        480,
        "ez_kenburns",
        "wan",
        "Silent Ken Burns pan/zoom ~5 s",
        "Slow Ken Burns zoom on the start still. Identity locked. No cut.",
    ),
    _w(
        "tilt-reveal",
        832,
        480,
        "ez_tilt",
        "wan",
        "Silent tilt reveal ~5 s",
        "Slow tilt down to reveal the subject. One continuous take. No cut.",
    ),
    _w(
        "handheld-vlog",
        480,
        832,
        "ez_vlog",
        "wan",
        "Silent handheld vlog micro-shake 9:16",
        "Subtle handheld micro-shake. Keep identity locked. No whip pan.",
    ),
    _w(
        "macro-product",
        832,
        480,
        "ez_macro",
        "wan",
        "Silent macro product crawl ~5 s",
        "Slow macro crawl across the start-image surface. Identity locked.",
    ),
    _w(
        "fabric-breeze",
        832,
        480,
        "ez_breeze",
        "wan",
        "Silent fabric/hair breeze ~5 s",
        "A warm breeze moves coat hem and hair. Locked camera otherwise.",
    ),
    _w(
        "city-night",
        832,
        480,
        "ez_night",
        "wan",
        "Silent night-drive / city-lights ~5 s",
        "Slow dolly past city lights. Keep the start-image identity locked.",
    ),
    _w(
        "zoom-punch",
        480,
        832,
        "ez_punch",
        "wan",
        "Silent 9:16 hook zoom punch",
        "Punch-in toward the start-image subject in the first second, then hold.",
        handoff=("ltx/shorts-still-5s",),
    ),
    _w(
        "screen-bg-loop",
        832,
        480,
        "ez_screen",
        "wan",
        "Silent desk/screen loop",
        "Soft screen glow and dust motes. Locked camera. Ping-pong friendly.",
        loop=True,
    ),
    _w(
        "confetti-loop",
        832,
        480,
        "ez_confetti",
        "wan",
        "Silent celebration loop",
        "Soft falling paper motes, looping. Ping-pong friendly. No flash.",
        loop=True,
    ),
    _w(
        "paper-flip",
        832,
        480,
        "ez_flip",
        "wan",
        "Silent page / carousel flip ~5 s",
        "A page or card turns once. Keep identity locked. One take.",
    ),
    _w(
        "pan-left",
        832,
        480,
        "ez_pan",
        "wan",
        "Silent locked-identity pan ~5 s",
        "Slow pan left. Keep every object from the start image. No cut.",
    ),
    _l(
        "youtube-outro-av",
        1280,
        704,
        "ez_yt_outro",
        "ltx",
        "YouTube outro AV ~5 s with room tone",
        "Locked-camera outro. Room tone, a chair creak, distant city. No score. Five seconds.",
        mode="t2v",
        catalog="ltx_broll",
        audio="room tone, chair creak, no score",
    ),
    _l(
        "instagram-reel-lifestyle",
        768,
        1280,
        "ez_ig_reel_av",
        "ltx",
        "Instagram lifestyle reel AV 9:16",
        "Slow lifestyle take from the start still. Fabric breeze, distant city. No score.",
        audio="breeze, distant city, no score",
    ),
    _l(
        "tiktok-broll",
        768,
        1280,
        "ez_tt_broll",
        "ltx",
        "TikTok B-roll AV 9:16",
        "Vertical B-roll from the start still. World SFX only. No score. Five seconds.",
        audio="world SFX, no score",
    ),
    _l(
        "twitch-starting-av",
        1280,
        704,
        "ez_tw_start_av",
        "ltx",
        "Twitch starting-soon AV ~5 s",
        "Quiet set, a soft whoosh of air, no score. Locked camera. Five seconds.",
        mode="t2v",
        catalog="ltx_broll",
        audio="soft whoosh, room tone, no score",
    ),
    _l(
        "music-visual",
        1280,
        704,
        "ez_music_vis",
        "ltx",
        "Light / particle visualizer bed AV ~5 s",
        "Abstract warm particles over a dark unmarked set. Soft fizz, no score, no lyrics.",
        mode="t2v",
        catalog="ltx_broll",
        audio="soft fizz, no score",
    ),
    _l(
        "recipe-pour",
        768,
        1280,
        "ez_pour",
        "ltx",
        "Recipe pour AV 9:16",
        "Slow pour into an unmarked bowl. Liquid, ceramic clink. No score. Five seconds.",
        audio="pour, ceramic clink, no score",
    ),
    _l(
        "product-unbox-av",
        1280,
        704,
        "ez_unbox_av",
        "ltx",
        "Unbox AV with paper SFX ~5 s",
        "Hands ease a box. Paper rustle, cardboard. No score. Keep the start image.",
        audio="paper rustle, cardboard, no score",
    ),
    _l(
        "desk-work",
        1280,
        704,
        "ez_desk_av",
        "ltx",
        "Desk / keyboard room-tone AV ~5 s",
        "Locked desk. Soft keycaps, a mug set down. No score. Five seconds.",
        mode="t2v",
        catalog="ltx_broll",
        audio="keycaps, mug, no score",
    ),
    _l(
        "travel-establishing",
        1280,
        704,
        "ez_travel",
        "ltx",
        "Travel establishing AV ~5 s",
        "Slow establishing of a coastal city terrace. Wind, distant traffic. No score.",
        mode="t2v",
        catalog="ltx_broll",
        audio="wind, distant traffic, no score",
    ),
    _l(
        "interior-walk",
        1280,
        704,
        "ez_walk",
        "ltx",
        "Interior walk-through AV ~5 s",
        "Slow walk through an unmarked interior. Footfalls, room tone. No score.",
        mode="t2v",
        catalog="ltx_broll",
        audio="footfalls, room tone, no score",
    ),
    _l(
        "fashion-turn",
        768,
        1280,
        "ez_turn",
        "ltx",
        "Fashion turn AV 9:16",
        "Slow turn from the start still. Cloth rustle. No score. Five seconds.",
        audio="cloth rustle, no score",
    ),
    _l(
        "workout-rep",
        768,
        1280,
        "ez_rep",
        "ltx",
        "One exercise-rep AV 9:16",
        "One athletic rep from the start still. Breath, shoe squeak. No score.",
        audio="breath, shoe squeak, no score",
    ),
    _l(
        "asmr-macro",
        1280,
        704,
        "ez_asmr",
        "ltx",
        "Quiet macro foley AV ~5 s",
        "Macro of an unmarked surface. Soft taps, close mic. No score. Five seconds.",
        audio="soft taps, close mic, no score",
    ),
    _l(
        "rain-window",
        1280,
        704,
        "ez_rain",
        "ltx",
        "Rain-on-glass AV ~5 s",
        "Rain on a dark window. Drops, distant thunder hush. No score. Five seconds.",
        mode="t2v",
        catalog="ltx_broll",
        audio="rain on glass, no score",
    ),
    _l(
        "fireplace",
        1280,
        704,
        "ez_fire",
        "ltx",
        "Fireplace AV ~5 s",
        "A small unmarked fireplace. Soft crackle. No score. Five seconds.",
        mode="t2v",
        catalog="ltx_broll",
        audio="fire crackle, no score",
    ),
    _l(
        "podcast-set",
        1280,
        704,
        "ez_pod_set",
        "ltx",
        "Podcast-set AV ~5 s",
        "Two unmarked mics on oak. Room tone, a chair. No score. Five seconds.",
        mode="t2v",
        catalog="ltx_broll",
        audio="room tone, chair, no score",
    ),
    _l(
        "workshop-tools",
        1280,
        704,
        "ez_tools",
        "ltx",
        "Workshop tools AV ~5 s",
        "Unmarked hand tools on a bench. Soft clink, wood. No score. Five seconds.",
        mode="t2v",
        catalog="ltx_broll",
        audio="tool clink, wood, no score",
    ),
    _l(
        "crowd-ambience",
        1280,
        704,
        "ez_crowd",
        "ltx",
        "Distant crowd bed AV ~5 s",
        "Distant unmarked crowd under a terrace. Murmur, no score. Five seconds.",
        mode="t2v",
        catalog="ltx_broll",
        audio="distant crowd murmur, no score",
    ),
)

if len(PACK3) != 100:
    raise RuntimeError(f"PACK3 must have 100 specs, got {len(PACK3)}")


def pack3_pin_off() -> frozenset[str]:
    """Return lab_rel ids that pin Prompt Enhance off."""
    return frozenset(spec.rel for spec in PACK3 if spec.enhance_pin)


def pack3_stamp_rows() -> tuple[tuple[str, str, tuple[str, ...], bool], ...]:
    """Return (rel, occupancy, handoff, enhance_off_identity) for STAMP_SPECS."""
    return tuple(
        (spec.rel, spec.occupancy, spec.handoff, spec.enhance_pin) for spec in PACK3
    )
