"""Fill remaining Cinema Rack axes. Not imported by pytest."""

from __future__ import annotations

import json
from pathlib import Path

OUT = Path(__file__).resolve().parents[2] / "custom_nodes" / "ez_prompt_enhance" / "cinema"


def e(
    tid: str,
    label: str,
    clause: str,
    *,
    still: str = "",
    wan: str = "",
    audio: str = "",
    still_ok: bool = True,
    motion_ok: bool = True,
    av_ok: bool = True,
    conflicts: tuple[str, ...] = (),
    tags: tuple[str, ...] = (),
) -> dict:
    if not clause.endswith("."):
        clause += "."
    if still and not still.endswith("."):
        still += "."
    return {
        "id": tid,
        "label": label,
        "clause": clause,
        "still": still,
        "wan_token": wan,
        "audio": audio,
        "still_ok": still_ok,
        "motion_ok": motion_ok,
        "av_ok": av_ok,
        "conflicts": list(conflicts),
        "tags": list(tags),
    }


def dump(name: str, rows: list[dict]) -> None:
    path = OUT / name
    path.write_text(json.dumps(rows, indent=2) + "\n", encoding="utf-8")
    print(name, len(rows))


def composition() -> list[dict]:
    rows = [
        e("cmp_thirds_right", "Thirds right", "Park the subject on the right vertical third with looking room to the left", tags=("thirds",)),
        e("cmp_thirds_left", "Thirds left", "Park the subject on the left vertical third with looking room to the right", tags=("thirds",)),
        e("cmp_thirds_upper", "Thirds upper", "Pin eyes on the upper horizontal third so the lower frame holds body or ground", tags=("thirds",)),
        e("cmp_thirds_lower", "Thirds lower", "Sit the figure on the lower third so sky or ceiling dominates the top two-thirds", tags=("thirds",)),
        e("cmp_center_punch", "Center punch", "Bullseye the face dead center, symmetry of the room echoing both sides", tags=("center",)),
        e("cmp_center_vertical", "Center axis vertical", "Hold the body on the vertical midline of a 9:16 plate, depth receding behind", tags=("vertical",)),
        e("cmp_short_side", "Short side", "Short-side the look: eyes close to the frame edge they face, tension in the leftover air", tags=("tension",)),
        e("cmp_long_side", "Long side", "Give generous looking room so the gaze travels across empty architecture", tags=("space",)),
        e("cmp_diagonal", "Diagonal", "Build a diagonal from lower left ground to upper right face, energy climbing the frame", tags=("line",)),
        e("cmp_counter_diagonal", "Counter diagonal", "Slash a diagonal from upper left lamp to lower right hands", tags=("line",)),
        e("cmp_leading_road", "Leading road", "Let a road, rail, or corridor lines suck the eye to a small figure", tags=("line",)),
        e("cmp_leading_hands", "Leading hands", "Use outstretched arms or a pointed tool as a vector into the face", tags=("line",)),
        e("cmp_vanishing", "Vanishing point", "Place the subject at a one-point vanishing point of a hall or nave", tags=("depth",)),
        e("cmp_two_point", "Two-point", "Stand a building on two-point perspective, verticals true, mass on the near corner", tags=("depth",)),
        e("cmp_frame_in_frame", "Frame in frame", "Shoot through a doorway, window, or arch so a second rectangle cages the person", tags=("layers",)),
        e("cmp_dirty_fg", "Dirty foreground", "Hang an out-of-focus shoulder, plant, or glass in the near field, subject readable beyond", tags=("layers",)),
        e("cmp_clean_graphic", "Clean graphic", "Empty the near field, subject against a simple wall or sky, poster-flat", tags=("graphic",)),
        e("cmp_layers_three", "Three planes", "Occupy foreground, mid, and far with distinct masses so depth is stacked", tags=("layers",)),
        e("cmp_negative_left", "Negative left", "Leave the left two-thirds empty so a small figure on the right feels isolated", tags=("space",)),
        e("cmp_negative_top", "Negative top", "Crush the figure to the bottom with a huge empty sky or ceiling", tags=("space",)),
        e("cmp_figure_ground", "Figure ground", "Cut a sharp silhouette against a much brighter or darker field", tags=("graphic",)),
        e("cmp_isolation", "Isolation", "Float one person in a huge readable place, tiny in the geography", tags=("scale",)),
        e("cmp_cluster", "Cluster", "Pack a group into one dense knot, leftover frame empty", tags=("group",)),
        e("cmp_pattern_break", "Pattern break", "Repeat a rhythm of windows or trees, then break it with the subject", tags=("rhythm",)),
        e("cmp_repetition", "Repetition", "March identical objects across the frame so the eye counts them", tags=("rhythm",)),
        e("cmp_juxtapose_scale", "Scale juxtapose", "Stand a small person against a huge unmarked machine or facade", tags=("scale",)),
        e("cmp_overlap", "Overlapping forms", "Overlap bodies and furniture so nearer shapes hide farther ones", tags=("depth",)),
        e("cmp_aerial_perspective", "Aerial perspective", "Let distant planes go cooler and softer while the near subject stays crisp", tags=("depth",)),
        e("cmp_size_diminution", "Size diminution", "Same object type near and far, the far one tiny, proving distance", tags=("depth",)),
        e("cmp_tele_stack", "Telephoto stack", "Compress a crowd or street into a flat stack of overlapping faces", tags=("depth",)),
        e("cmp_wide_near_far", "Wide near far", "A huge near object and a tiny far figure in one ultra-wide plate", tags=("depth",)),
        e("cmp_formal_balance", "Formal balance", "Mirror masses left and right of a central axis", tags=("balance",)),
        e("cmp_informal_balance", "Informal balance", "A large dark mass on one side answered by a small bright practical on the other", tags=("balance",)),
        e("cmp_radial", "Radial", "Arrange lines and gazes as spokes into a central face", tags=("balance",)),
        e("cmp_triangle", "Triangle block", "Block three heads or lamps as a stable triangle", tags=("balance",)),
        e("cmp_sit_stand", "Sit stand contrast", "One seated, one standing, heights arguing in the same frame", tags=("block",)),
        e("cmp_enter_left", "Enter from left", "Leave left-edge air so a body can enter from that wing", tags=("motion",)),
        e("cmp_exit_right", "Exit right", "Aim the walk at the right edge with space to leave", tags=("motion",)),
        e("cmp_cross_frame", "Cross frame", "A walker crosses the entire width, path parallel to the sensor", tags=("motion",)),
        e("cmp_toward_lens", "Toward lens", "The subject walks straight at the glass, growing", tags=("motion",)),
        e("cmp_away_lens", "Away from lens", "The subject recedes down a path, shrinking", tags=("motion",)),
        e("cmp_headroom_tight", "Tight headroom", "Hair nearly kisses the top edge, no wasted sky", tags=("portrait",)),
        e("cmp_headroom_open", "Open headroom", "Generous air above the crown, a vertical 9:16 that can take captions later in edit not in-camera", tags=("portrait",)),
        e("cmp_ground_plane", "Ground plane", "Show a lot of floor so the body is planted, not floating", tags=("space",)),
        e("cmp_ceiling_crush", "Ceiling crush", "A low ceiling presses down, the head close to architecture", tags=("space",)),
        e("cmp_s_curve", "S-curve", "A river, path, or body traces an S that the eye follows into depth", tags=("line",)),
        e("cmp_golden_triangle", "Golden triangle", "A diagonal divide with a perpendicular from the opposite corner, subject at the intersection", tags=("line",)),
        e("cmp_fibonacci_curve", "Attention spiral", "Compose so the eye spirals from a near object into the face", tags=("line",)),
        e("cmp_look_space", "Look space", "More air in the direction of the gaze than behind the head", tags=("portrait",)),
        e("cmp_over_shoulder_dirty", "Dirty over-shoulder", "A cheek and ear as a dark mass, the far face sharp in the remaining window", tags=("coverage",)),
        e("cmp_profile_line", "Profile line", "A full profile against a simple field, the nose pointing into space", tags=("portrait",)),
        e("cmp_top_heavy", "Top heavy", "Mass and detail in the upper third, the lower frame quiet", tags=("balance",)),
        e("cmp_bottom_heavy", "Bottom heavy", "Furniture and body weight the lower frame, sky simple", tags=("balance",)),
        e("cmp_left_weight", "Left weight", "Almost all mass on the left, the right a field of tone", tags=("balance",)),
        e("cmp_right_weight", "Right weight", "Almost all mass on the right, the left a field of tone", tags=("balance",)),
        e("cmp_corner_subject", "Corner subject", "Tuck the person in a corner of the frame, architecture claiming the rest", tags=("tension",)),
        e("cmp_edge_slice", "Edge slice", "Crop a face or object with the frame edge as a knife, part of it missing", tags=("tension",)),
        e("cmp_amputate_avoid", "Joint-safe crop", "Crop mid-torso or mid-thigh, never through a joint", tags=("portrait",)),
        e("cmp_full_body_grounded", "Full body grounded", "Head to shoes with floor visible, the person entirely in the world", tags=("portrait",)),
        e("cmp_insert_hands_center", "Hands center", "Hands and object dead center, face out", tags=("insert",)),
        e("cmp_product_hero_center", "Product hero", "A product on the optical axis, negative space a seamless field", tags=("insert",)),
        e("cmp_rule_of_odds", "Odds", "Group three lamps or three people, not two, so the eye rests on the middle", tags=("group",)),
        e("cmp_even_pair", "Even pair", "Two equal figures, a 50/50 split of the frame", tags=("group",)),
        e("cmp_crowd_flow", "Crowd flow", "Bodies as a current, one readable face against the stream", tags=("group",)),
        e("cmp_window_light_side", "Window as frame", "The window rectangle is the composition, the person a mass inside it", tags=("layers",)),
        e("cmp_mirror_split", "Mirror split", "Half real, half reflection, a vertical join down the glass", tags=("layers",)),
        e("cmp_reflection_puddle", "Puddle double", "A puddle doubles the world, the real figure standing on the join", tags=("layers",)),
        e("cmp_silhouette_arch", "Silhouette in arch", "A dark figure in a bright arch, the arch the only geometry", tags=("graphic",)),
        e("cmp_color_mass", "Color mass", "A large field of one hue balanced by a small complementary accent on the subject", tags=("color",)),
        e("cmp_high_horizon", "High horizon", "Horizon near the top, a lot of ground, the person walking a map", tags=("landscape",)),
        e("cmp_low_horizon", "Low horizon", "Horizon near the bottom, a lot of sky, the person a notch on the earth-line", tags=("landscape",)),
        e("cmp_no_horizon", "No horizon", "Deny the horizon: a wall, fog, or canopy so scale is uncertain", tags=("landscape",)),
        e("cmp_dutch_compose", "Canted masses", "The composition itself is a tilt: floors and lamps as diagonals", tags=("dutch",)),
        e("cmp_nested_rectangles", "Nested rectangles", "Picture frames, screens, and doors as rectangles inside rectangles", tags=("graphic",)),
        e("cmp_circle_motif", "Circle motif", "Wheels, lamps, or arches as repeating circles around a face", tags=("rhythm",)),
        e("cmp_verticals_only", "Verticals only", "A forest of verticals, almost no horizontals, the person a vertical too", tags=("graphic",)),
        e("cmp_horizontals_only", "Horizontals only", "Layers of land, water, cloud as stacked bands, a small figure on one band", tags=("landscape",)),
        e("cmp_grid", "Grid", "A facade or tiles as a grid, the subject breaking one cell", tags=("graphic",)),
        e("cmp_empty_center", "Empty center", "Action on the edges, the middle a void the eye keeps returning to", tags=("tension",)),
        e("cmp_busy_center", "Busy center", "All detail in the middle, edges fall to tone", tags=("center",)),
        e("cmp_occluder_left", "Left occluder", "A dark vertical mass on the left, the scene opening to the right", tags=("layers",)),
        e("cmp_occluder_right", "Right occluder", "A dark vertical mass on the right, the scene opening to the left", tags=("layers",)),
        e("cmp_over_table", "Over table", "Tabletop as a foreground plane, faces beyond the glasses", tags=("layers",)),
        e("cmp_under_object", "Under object", "Look under a table or car so the underside is a ceiling", tags=("angle",)),
        e("cmp_through_crowd", "Through crowd", "Bodies as a broken screen, one far face in a gap", tags=("layers",)),
        e("cmp_power_low", "Power from below", "Compose so the subject towers, the camera and masses looking up", tags=("power",)),
        e("cmp_power_high", "Power from above", "Compose so the subject is looked down on, the ground a map around them", tags=("power",)),
        e("cmp_equal_eyeline", "Equal eyeline", "Camera and subject share height, neither dominates", tags=("portrait",)),
        e("cmp_caption_safe_vert", "Caption-safe vertical", "Keep the lower fifth and upper fifth free of faces so later text can sit there, faces in the middle band", tags=("vertical",)),
        e("cmp_lower_third_clear", "Lower-third clear", "Keep the bottom fifth empty of important mass for a later graphic, not burned in", tags=("safe",)),
        e("cmp_square_center", "Square center", "A 1:1 plate with the subject centered and corners quiet", tags=("aspect",)),
        e("cmp_scope_empty_sides", "Scope side room", "A 2.39 plate with huge side room, the figure a small event in width", tags=("aspect",)),
        e("cmp_academy_tight", "Academy tight", "A 1.85 plate filled edge to edge with the conversation", tags=("aspect",)),
        e("cmp_ig_vertical_head", "Tall headroom portrait", "A 4:5 plate with extra air above the crown and a full torso", tags=("aspect",)),
        e("cmp_wide_lower_safe", "16:9 lower safe", "A 16:9 plate with the face in the upper half, lower half a quiet set", tags=("aspect",)),
        e("cmp_split_left_right", "Split left right", "A vertical line (door, wall, light cut) divides two worlds in one frame", tags=("graphic",)),
        e("cmp_split_up_down", "Split up down", "A horizon or railing splits the frame into two stacked stories", tags=("graphic",)),
        e("cmp_tiny_in_door", "Tiny in door", "A far figure in a distant doorway, the room huge around the dark rectangle", tags=("scale",)),
        e("cmp_fill_the_glass", "Fill the glass", "The face or product fills so much of the frame that context is only edges", tags=("portrait",)),
        e("cmp_environmental", "Environmental", "The place is the story, the person a detail of furniture scale", tags=("scale",)),
        e("cmp_over_shoulder_clean", "Clean single after OTS", "No foreground cheek, a clean single that still feels like coverage of a pair", tags=("coverage",)),
        e("cmp_group_wedge", "Group wedge", "A wedge of people pointing at one speaker", tags=("group",)),
        e("cmp_circle_around", "Circle around", "Bodies in a ring, camera outside looking in, or inside looking out", tags=("group",)),
        e("cmp_procession_line", "Procession line", "A line of people receding, each head a bead", tags=("group",)),
        e("cmp_one_against_many", "One against many", "A single distinct costume or stance against a uniform crowd", tags=("group",)),
        e("cmp_table_symmetry", "Table symmetry", "A long table as a centerline, faces in pairs", tags=("balance",)),
        e("cmp_stair_zigzag", "Stair zigzag", "A staircase as a zigzag graphic the figure climbs", tags=("line",)),
        e("cmp_bridge_span", "Bridge span", "A span as a horizontal bar, a small walker on it", tags=("landscape",)),
        e("cmp_window_grid_face", "Window grid face", "A face behind a grid of panes, one pane owning the eyes", tags=("layers",)),
        e("cmp_rain_streak_lines", "Rain as lines", "Rain streaks as composition lines leading to the figure", tags=("weather",)),
        e("cmp_shadow_as_mass", "Shadow as mass", "A cast shadow is a second character occupying a third of the frame", tags=("light",)),
        e("cmp_practical_as_anchor", "Practical as anchor", "A lamp or neon is the compositional anchor the face answers", tags=("light",)),
        e("cmp_hands_in_lower", "Hands in lower third", "Story in the hands, face in the upper, a split of labor in one still", tags=("insert",)),
        e("cmp_eyes_on_third_cross", "Eyes on the cross", "Eyes sit exactly on a thirds intersection, the rest of the face falling away", tags=("portrait",)),
        e("cmp_profile_into_dark", "Profile into dark", "A profile looking into a dark half, the lit half behind them", tags=("tension",)),
        e("cmp_back_to_camera", "Back to camera", "We see the back, the world they face, the face withheld", tags=("tension",)),
        e("cmp_over_the_hill", "Over the hill", "A ridge as a graphic, a small figure just breaking the skyline", tags=("landscape",)),
        e("cmp_tunnel_mouth", "Tunnel mouth", "The tunnel is a dark rectangle, the exit a bright postage stamp with a body in it", tags=("depth",)),
        e("cmp_crowd_part_center", "Parted crowd", "A path through bodies, the far person centered in the gap", tags=("group",)),
        e("cmp_desk_planes", "Desk planes", "Desktop, mid wall, far window as three parallel planes", tags=("layers",)),
        e("cmp_book_aisle", "Book aisle", "Two walls of unmarked shelves as leading planes, a figure at the vanishing point", tags=("depth",)),
        e("cmp_balcony_down", "Balcony down", "A railing as a near horizontal, the floor below a second composition", tags=("layers",)),
        e("cmp_mezzanine_split", "Mezzanine split", "Upper walkway and lower hall in one frame, two scales of people", tags=("scale",)),
        e("cmp_door_threshold", "Threshold split", "Interior warm and exterior cool meet at a jamb, the person on the line", tags=("layers",)),
        e("cmp_phone_center_axis", "Phone center axis", "Vertical centerline composition for a handheld 9:16, subject on the spine of the glass", tags=("vertical",)),
        e("cmp_z_axis_stack", "Z-axis stack", "Near object, subject, far city stacked on the lens axis, not spread sideways", tags=("depth",)),
        e("cmp_empty_chair", "Empty chair", "An empty chair as a composed mass implying a missing person", tags=("tension",)),
        e("cmp_occupied_and_empty", "Occupied and empty", "One side of a sofa lived-in, the other a blank cushion", tags=("tension",)),
        e("cmp_clock_as_circle", "Clock as circle", "A round clock or fan as the only circle in a rectangular room, drawing the eye", tags=("graphic",)),
        e("cmp_stripe_rhythm", "Stripe rhythm", "Blinds, siding, or a crosswalk as stripes the figure interrupts", tags=("rhythm",)),
        e("cmp_corner_escape", "Corner escape", "The subject in a corner with one exit path visible, the other wall a trap", tags=("tension",)),
        e("cmp_open_landscape_tiny", "Open landscape tiny", "A vast readable place, the person a speck with a clear stance", tags=("scale",)),
        e("cmp_claustrophobic_fill", "Claustrophobic fill", "Walls, ceiling, and furniture leave almost no air around the body", tags=("space",)),
    ]
    return rows


def lenses() -> list[dict]:
    rows = [
        e("opt_fisheye", "Fisheye", "A circular or strongly bowed fisheye, horizons smiling, the room wrapping the lens", tags=("wide",)),
        e("opt_rect_14", "14mm rectilinear", "Ultra-wide rectilinear 14mm-equivalent, verticals held, a huge near/far jump", tags=("wide",)),
        e("opt_18_establish", "18mm establish", "18mm-equivalent establishing wide, architecture readable, people small", tags=("wide",)),
        e("opt_24_wide", "24mm wide", "24mm-equivalent wide, environmental portrait with honest rooms", tags=("wide",)),
        e("opt_28_street", "28mm street", "28mm-equivalent street perspective, close enough to feel inside the walk", tags=("street",)),
        e("opt_35_classic", "35mm classic", "35mm-equivalent, the classic reportage view, moderate depth", tags=("normal",)),
        e("opt_40_normal", "40mm normal", "40mm-equivalent, near-normal, mild compression, documentary calm", tags=("normal",)),
        e("opt_50_normal", "50mm normal", "50mm-equivalent normal, how a standing person sees a conversation", tags=("normal",)),
        e("opt_65_portrait", "65mm portrait", "65mm-equivalent short portrait, faces kind, rooms still present", tags=("portrait",)),
        e("opt_85_portrait", "85mm portrait", "85mm-equivalent portrait, background melting, features flattered", tags=("portrait",)),
        e("opt_100_compress", "100mm compress", "100mm-equivalent, space stacking, a tight head with compressed street", tags=("long",)),
        e("opt_135_isolate", "135mm isolate", "135mm-equivalent isolation, a face or product cut out of the world", tags=("long",)),
        e("opt_200_sports", "200mm isolation", "200mm-equivalent, a figure pulled from a crowd, background a wash", tags=("long",)),
        e("opt_400_extreme", "400mm extreme", "400mm-equivalent extreme compression, heat shimmer and stacked planes", tags=("long",)),
        e("opt_spherical_clean", "Spherical clean", "Spherical glass, round highlights, no oval streak, honest geometry", tags=("spherical",)),
        e("opt_anamorphic_class", "Anamorphic-class", "Anamorphic-class oval highlights and a horizontal flare streak across lamps", tags=("anamorphic",)),
        e("opt_anamorphic_squeeze", "Widescreen oval bokeh", "Widescreen squeeze look: oval bokeh, slightly shallower sides, cinematic width in the glass itself", tags=("anamorphic",)),
        e("opt_split_diopter", "Split diopter", "A split diopter holds a near object and a far face both sharp, a seam of softness between", tags=("focus",)),
        e("opt_tilt_rake", "Tilt rake", "Tilt the focus plane so a table or street is sharp along its length, the rest falls", tags=("tilt",)),
        e("opt_swing_landscape", "Swing landscape", "Swing the lens so a receding fence line is the sharp plane", tags=("tilt",)),
        e("opt_tilt_miniature", "Tilt miniature", "A steep tilt that makes a real street read as a tiny model", tags=("tilt",)),
        e("opt_sweet_spot", "Sweet-spot optic", "A sweet-spot optic: a sharp island, the rest a swirling blur", tags=("specialty",)),
        e("opt_probe", "Probe", "A probe lens into a tight cavity, a miniature interior opening around the entrance", tags=("specialty",)),
        e("opt_periscope", "Periscope optic", "A periscope optic looking over a wall the camera body could not clear", tags=("specialty",)),
        e("opt_probe_miniature", "Probe through miniature", "A probe through a miniature set, forced perspective as if the room were full size", tags=("specialty",)),
        e("opt_shift_verticals", "Shift verticals", "Shift the lens to keep building verticals parallel, no keystone", tags=("architecture",)),
        e("opt_deep_focus", "Deep focus", "Deep focus from inches to infinity, every plane readable", tags=("focus",)),
        e("opt_shallow", "Shallow plane", "A shallow plane of focus on the eyes, everything else cream", tags=("focus",)),
        e("opt_razor", "Razor focus", "A razor-thin plane, even ears going, only lashes sharp", tags=("focus",)),
        e("opt_rack_forward", "Rack forward", "Rack focus from a far figure onto a near object in the hands", tags=("focus",)),
        e("opt_rack_back", "Rack back", "Rack focus from a near glass to the person beyond it", tags=("focus",)),
        e("opt_rumble_rack", "Rumble rack", "A searching rumble of focus that hunts then lands", tags=("focus",)),
        e("opt_locked_iris", "Locked iris", "Locked iris, no breathing, the world does not pulse", tags=("iris",)),
        e("opt_breathing_character", "Breathing iris", "Iris breathing as a character, the world dimming and opening", tags=("iris",)),
        e("opt_halation_diffusion", "Halation diffusion", "Mild diffusion so highlights bloom a soft halo, not a brand filter name", tags=("diffusion",)),
        e("opt_heavy_diffusion", "Heavy bloom", "Heavy bloom, lamps becoming globes, contrast gentle", tags=("diffusion",)),
        e("opt_net", "Net over lens", "A net or stocking over the lens, highlights catching a faint mesh glow", tags=("diffusion",)),
        e("opt_diopter_close", "Close diopter", "A close-up diopter on a tiny object, working distance inches", tags=("macro",)),
        e("opt_macro_extension", "Macro extension", "Macro extension, pores and weave as landscape", tags=("macro",)),
        e("opt_close_focus_wide", "Close-focus wide", "A wide lens at its minimum focus, a huge near object and a real room behind", tags=("wide",)),
        e("opt_rear_streak", "Rear-filter streak", "A rear streak filter throwing lamps into lines", tags=("effect",)),
        e("opt_zoom_in", "Zoom in", "Zoom in on a locked nodal point, magnification without the camera body moving", conflicts=("move_dolly_in",), tags=("zoom",)),
        e("opt_zoom_out", "Zoom out", "Zoom out on a locked nodal point, the world widening without a dolly", conflicts=("move_dolly_out",), tags=("zoom",)),
        e("opt_crash_zoom_optic", "Optical crash zoom", "A crash zoom on the glass, the face punching larger in one hit", conflicts=("move_dolly_in",), tags=("zoom",)),
        e("opt_slow_zoom_in", "Slow zoom in", "A crawl zoom, compression changing over a long sentence", tags=("zoom",)),
        e("opt_super_speed_cream", "Low-light cream", "A fast optic wide open, low-light cream, backgrounds dissolving", tags=("aperture",)),
        e("opt_stopped_down_bite", "Stopped-down bite", "Stopped down for bite and deep detail, highlights tight", tags=("aperture",)),
        e("opt_variable_nd_dark", "Dark ND world", "A dark ND world, shutter still cinematic, noon looking like dusk in exposure only", tags=("exposure",)),
        e("opt_dirty_close_diopter", "Dirty close diopter", "A dirty close diopter, dust and grease in the near glow", tags=("macro",)),
        e("opt_split_field_both", "Split-field both sharp", "Near and far both sharp with a split field, a visible focus seam", tags=("focus",)),
        e("opt_soft_edge_center_sharp", "Soft-edge center sharp", "Center sharp, edges dissolving as if the optic were a toy", tags=("specialty",)),
        e("opt_long_lens_smash", "Long-lens smash", "A long lens smash into a face from a distant camera, space crushed", tags=("long",)),
        e("opt_wide_hero_low", "Wide hero low", "A wide lens at belt height, legs huge, towers falling back", tags=("wide",)),
        e("opt_normal_doc", "Normal documentary", "A normal documentary optic, neither flattering nor accusing", tags=("normal",)),
        e("opt_portrait_long_night", "Long night portrait", "A long portrait optic at night, lamps as big discs behind a quiet face", tags=("portrait",)),
        e("opt_architecture_tilt_shift", "Architecture shift", "Shift for a facade, verticals true, the building a rectangle", tags=("architecture",)),
        e("opt_interior_24", "Interior 24", "24mm in a small room, walls present, no fisheye bow", tags=("wide",)),
        e("opt_interior_35", "Interior 35", "35mm in a room, a person and their furniture in honest scale", tags=("normal",)),
        e("opt_food_macro", "Food macro", "Macro on steam and garnish, the plate a landscape", tags=("macro",)),
        e("opt_product_85", "Product 85", "85mm on a product, wrap light, background a smooth falloff", tags=("portrait",)),
        e("opt_sports_follow", "Sports follow long", "A long sports follow, the athlete sharp, crowd a texture", tags=("long",)),
        e("opt_wildlife_distance", "Distance isolate", "Extreme distance isolation, a small creature large in frame, habitat stacked", tags=("long",)),
        e("opt_underwater_wide", "Underwater wide", "A wide underwater optic, dome port, caustics and a huge near hand", tags=("wide",)),
        e("opt_anamorphic_flare_night", "Night horizontal flare", "Night lamps throwing cool horizontal streaks, oval car lights", tags=("anamorphic",)),
        e("opt_spherical_night_round", "Night round bokeh", "Night spherical round bokeh, coins of practicals", tags=("spherical",)),
        e("opt_vintage_low_con", "Vintage low contrast", "Vintage low-contrast glass, veiling in the highlights, gentle microcontrast", tags=("vintage",)),
        e("opt_modern_bite", "Modern bite", "Modern high-microcontrast glass, edges crisp, coatings keeping flare down", tags=("modern",)),
        e("opt_uncoated_flare", "Uncoated flare", "Uncoated or lightly coated glass, flares taking over the highlights", tags=("vintage",)),
        e("opt_rear_anamorphic_look", "Rear anamorphic look", "Rear anamorphic-class look: oval bokeh with less side distortion than a front squeeze", tags=("anamorphic",)),
        e("opt_front_anamorphic_look", "Front anamorphic look", "Front anamorphic-class look: stronger oval, more barrel in the sides", tags=("anamorphic",)),
        e("opt_diopter_split_face", "Diopter on face", "A + diopter so a close face is sharp at a distance the taking lens could not", tags=("macro",)),
        e("opt_extension_tube", "Extension tube close", "Extension-tube close focus, a ring or label filling the plate", tags=("macro",)),
        e("opt_teleconverter_reach", "Teleconverter reach", "Teleconverter reach, a distant face large, a little extra softness and compression", tags=("long",)),
        e("opt_wide_converter_room", "Wide converter room", "A wide converter making a small room huge, some edge stretch", tags=("wide",)),
        e("opt_isf_shift_rise", "Rise shift", "Rise the lens to include a ceiling without tilting the camera", tags=("architecture",)),
        e("opt_isf_shift_fall", "Fall shift", "Fall the lens to include a floor without tilting", tags=("architecture",)),
        e("opt_lock_focus_infinity", "Infinity lock", "Focus locked at infinity, near objects as blur, the far city sharp", tags=("focus",)),
        e("opt_lock_focus_near", "Near lock", "Focus locked on a near object, the world beyond a wash", tags=("focus",)),
        e("opt_follow_focus_walk", "Follow-focus walk", "Follow-focus holds eyes on a walker, background breathing", tags=("focus",)),
        e("opt_no_follow_miss", "Missed focus as grammar", "A missed focus that hunts, then finds, as a documentary beat", tags=("focus",)),
        e("opt_deep_night_fast", "Deep night fast glass", "Fast glass wide open at night, a thin plane, lamps huge", tags=("aperture",)),
        e("opt_day_stopped_deep", "Day stopped deep", "Daylight stopped down, deep focus, hard sun detail", tags=("aperture",)),
        e("opt_diffusion_black_promist_class", "Black-diffusion class", "Black-diffusion-class look: bloomed highlights, blacks staying black", tags=("diffusion",)),
        e("opt_white_diffusion_class", "White-diffusion class", "White-diffusion-class look: veiling, lifted blacks, dream air", tags=("diffusion",)),
        e("opt_low_con_filter_class", "Low-con class", "Low-con class: contrast down, highlights taking on a glow without a product name", tags=("diffusion",)),
        e("opt_clear_zero", "Clear zero", "No taking filter, maximum bite and contrast", tags=("clean",)),
        e("opt_polarize_sky", "Polarized sky", "A polarizer deepening sky and cutting glare on glass and water", tags=("filter",)),
        e("opt_polarize_shop", "Polarized shop glass", "A polarizer killing window reflections so the interior reads", tags=("filter",)),
        e("opt_grad_nd_sky", "Graduated sky", "A graduated ND holding a bright sky while the ground stays open", tags=("filter",)),
        e("opt_warming_glass", "Warming glass", "A warming glass, daylight going amber without a grade", tags=("filter",)),
        e("opt_cooling_glass", "Cooling glass", "A cooling glass, tungsten rooms going cleaner without a grade", tags=("filter",)),
        e("opt_cross_star", "Star spikes", "Point sources throwing star spikes, a night street of asterisks", tags=("effect",)),
        e("opt_soft_spot", "Center soft spot", "A center soft-spot, edges sharper than the middle, dream portrait", tags=("specialty",)),
        e("opt_pinhole_look", "Pinhole look", "Pinhole look: infinite depth, glow, long exposure smear if anything moves", tags=("specialty",)),
        e("opt_zone_plate_glow", "Zone-plate glow", "Zone-plate-class glow, highlights as concentric rings", tags=("specialty",)),
        e("opt_lensbaby_class_edge", "Edge whirl", "A whirl of blur around a sharp sweet spot, the street spinning", tags=("specialty",)),
        e("opt_macro_stack", "Macro stack implied", "A macro so shallow only a letter of a label is sharp", tags=("macro",)),
        e("opt_copy_stand", "Copy-stand flat", "A copy-stand flat optic, no distortion, a document or drawing true", tags=("specialty",)),
        e("opt_shift_stitch_wide", "Shift-stitch wide", "A shift-stitch ultra-wide, high resolution, no fisheye bow", tags=("architecture",)),
        e("opt_tilt_table_food", "Tilt table food", "Tilt so a long table of dishes is sharp from near garnish to far glass", tags=("tilt",)),
        e("opt_anamorphic_day_oval", "Day oval bokeh", "Daylight anamorphic-class ovals in foliage behind a portrait", tags=("anamorphic",)),
        e("opt_spherical_85_open", "85 open spherical", "85mm spherical wide open, round cream, no oval", tags=("portrait",)),
        e("opt_24_open_env", "24 open environmental", "24mm wide open, the room still mostly sharp, only the far street going", tags=("wide",)),
        e("opt_50_open_talk", "50 open talk", "50mm wide open on a talk, the far wall a gentle melt", tags=("normal",)),
        e("opt_135_open_stage", "135 open stage", "135mm wide open on a stage figure, house a wash of discs", tags=("long",)),
        e("opt_zoom_parfocal_hold", "Parfocal zoom hold", "A parfocal zoom that holds focus while magnifying", tags=("zoom",)),
        e("opt_zoom_breathe_varifocal", "Varifocal breathe", "A varifocal zoom that breathes focus as it magnifies, old-school", tags=("zoom",)),
        e("opt_crash_out_optic", "Optical crash out", "A crash zoom out, context slamming around a face", tags=("zoom",)),
        e("opt_punch_in_optic", "Optical punch in", "A punch-in zoom to an insert of the eyes or a label", tags=("zoom",)),
        e("opt_probe_liquid", "Probe in liquid", "A probe in liquid, droplets on the barrel, a tiny world", tags=("specialty",)),
        e("opt_endoscope_tunnel", "Tunnel optic", "An endoscope-adjacent tunnel, a pipe or throat as architecture", tags=("specialty",)),
        e("opt_security_wide", "Security wide", "A high-corner security wide, slight barrel, cold coverage", tags=("wide",)),
        e("opt_dash_wide", "Dash wide", "A dash-cam wide, road and wipers, barrel at the edges", tags=("wide",)),
        e("opt_bodycam_wide", "Body-cam wide", "A chest-cam wide, sleeves in the bottom, landing huge", tags=("wide",)),
        e("opt_drone_wide_rect", "Drone wide rectilinear", "A drone wide rectilinear, the city a map without a fisheye ball", tags=("wide",)),
        e("opt_drone_medium", "Drone medium", "A drone medium, a roof figure readable, not a plan", tags=("normal",)),
        e("opt_imax_class_deep", "Large-format deep", "Large-format-class deep: more height in the frame, gentle falloff, huge places", tags=("format",)),
        e("opt_16mm_class_grain_glass", "Small-format grit glass", "Small-format-class grit: more depth, a harder wide, less cream", tags=("format",)),
        e("opt_35_class_cinema", "35-class cinema", "35mm-motion-picture-class perspective, the default dramatic room", tags=("format",)),
        e("opt_65_class_scope_feel", "65-class scope feel", "65-class presence: more air around a face even in a close-up", tags=("format",)),
        e("opt_super_16_doc", "Super16-class doc", "Super16-class documentary: a bit more depth, a slightly harder wide", tags=("format",)),
        e("opt_closed_iris_sunstar", "Sunstar iris", "A closed iris turning the sun or a practical into a sunstar", tags=("aperture",)),
        e("opt_open_iris_ghost", "Open iris ghost", "Wide open, a veiling ghost of the lamp rather than a star", tags=("aperture",)),
        e("opt_focus_throw_long", "Long focus throw", "A long focus throw, the rack taking time, the hunt visible", tags=("focus",)),
        e("opt_focus_throw_snap", "Snap focus", "A snap focus throw, the plane jumping in one beat", tags=("focus",)),
        e("opt_bokeh_busy", "Busy bokeh", "Busy, noisy bokeh from foliage, the background a fidget", tags=("bokeh",)),
        e("opt_bokeh_smooth", "Smooth bokeh", "Smooth creamy bokeh, the background a quiet wash", tags=("bokeh",)),
        e("opt_cat_eye_bokeh", "Cat-eye bokeh", "Cat-eye ovals toward the edges, a vintage spherical tell", tags=("bokeh",)),
        e("opt_soap_bubble_bokeh", "Soap-bubble bokeh", "Soap-bubble bokeh, bright rings around discs", tags=("bokeh",)),
        e("opt_swirly_bokeh", "Swirly bokeh", "Swirly Petzval-class bokeh, the street rotating around a sharp face", tags=("bokeh",)),
        e("opt_anamorphic_blue_streak", "Cool horizontal streak", "A cool horizontal streak through a night lamp, anamorphic-class, no brand", tags=("anamorphic",)),
        e("opt_no_streak_night", "Night no streak", "Night lamps as rounds, no horizontal streak, spherical discipline", tags=("spherical",)),
        e("opt_macro_insect_plane", "Macro insect plane", "A macro plane so thin a label's serif is the only sharp line", tags=("macro",)),
        e("opt_wide_group", "Wide group", "A wide that holds a whole group without lining them on a 50", tags=("wide",)),
        e("opt_long_group_compress", "Long group compress", "A long lens on a group, faces stacked, space between them denied", tags=("long",)),
        e("opt_normal_two_shot", "Normal two-shot", "A normal two-shot, both heads honest, neither giant", tags=("normal",)),
        e("opt_portrait_two_shot", "Portrait two-shot", "A short-tele two-shot, both faces kind, the room falling", tags=("portrait",)),
        e("opt_insert_macro_label", "Insert macro label", "A macro insert of a label or screen, letters as architecture", tags=("macro",)),
        e("opt_roomtone_35_locked", "Locked 35 room", "A locked 35mm-equivalent on a room, the default coverage lens", tags=("normal",)),
        e("opt_coverage_85_single", "Coverage 85 single", "An 85mm-equivalent single for coverage, dirty OTS going clean", tags=("portrait",)),
        e("opt_establishing_drone_24", "Establishing 24 aerial", "A 24mm-equivalent aerial establish, the place as a model you could walk", tags=("wide",)),
    ]
    return rows


def color() -> list[dict]:
    rows = [
        e("col_color_neg_warm", "Color-negative warmth", "Warm color-negative look: honey highlights, gentle cyan in shadows, organic dye", tags=("capture",)),
        e("col_tungsten_day_cool", "Tungsten-balanced daylight", "Daylight shot as if tungsten-balanced: the world goes cold cyan, skin holds a bit of warmth", tags=("capture",)),
        e("col_cross_process", "Cross-process shift", "Cross-process shift: skews greens and magentas, contrast up, skies odd", tags=("capture",)),
        e("col_bleach_bypass", "Bleach-bypass silver", "Bleach-bypass: retained silver, crushed color, harsh contrast, metallic skin", conflicts=("col_pastel_candy",), tags=("process",)),
        e("col_retained_silver", "Retained silver", "ENR-class retained silver: color still there but contrast and grain bite", tags=("process",)),
        e("col_three_strip", "Three-strip primaries", "Three-strip-adjacent primaries: rich red, green, blue, almost poster separations", tags=("process",)),
        e("col_two_strip", "Two-strip red cyan", "Two-strip-adjacent: reds and cyans, missing true yellow-green", tags=("process",)),
        e("col_ortho_skies", "Ortho dark skies", "Orthochromatic-adjacent: skies go dark, lips pale, foliage odd", tags=("mono",)),
        e("col_infrared_foliage", "Infrared foliage", "Infrared-adjacent: foliage glows pale, skies dark, skin porcelain", tags=("capture",)),
        e("col_print_density", "Print-film density", "Print-film density: rich blacks, rolled highlights, a theatrical print", tags=("print",)),
        e("col_faded_print", "Faded print", "A faded print: magentas lingering, cyans gone, contrast tired", tags=("print",)),
        e("col_complementary_grade", "Complementary grade", "Shadows a cool teal, skin and practicals warm, a complementary grade without a meme name", tags=("grade",)),
        e("col_pastel_candy", "Pastel candy", "Pastel candy: lifted blacks, sweet hues, low contrast", conflicts=("col_bleach_bypass",), tags=("grade",)),
        e("col_crushed_shadow", "Crushed shadow", "Crushed shadows, no secret in the blacks, graphic night", tags=("grade",)),
        e("col_super_white", "Super-white highlight", "Super-white highlights, windows blowing, HDR-display energy", tags=("grade",)),
        e("col_sdr_print_roll", "SDR print roll-off", "SDR print roll-off: highlights gently compress, no HDR glitter", tags=("grade",)),
        e("col_mono_panchro", "Panchromatic mono", "Panchromatic black-and-white, even tones, honest skies", tags=("mono",)),
        e("col_mono_red_filter", "Red-filter mono", "Red-filter mono: dark skies, pale skin, dramatic clouds", tags=("mono",)),
        e("col_mono_green_filter", "Green-filter mono", "Green-filter mono: skin with bite, foliage separated", tags=("mono",)),
        e("col_mono_blue_filter", "Blue-filter mono", "Blue-filter mono: skies pale, skin darker, a harsher face", tags=("mono",)),
        e("col_split_tone_warm_cool", "Split-tone warm cool", "Split tone: warm highlights, cool shadows", tags=("grade",)),
        e("col_split_tone_sepia_blue", "Split-tone sepia blue", "Sepia highlights, blue shadows, a period postcard", tags=("grade",)),
        e("col_analogous_amber", "Analogous amber", "An analogous amber palette: honey, rust, cream, almost no blue", tags=("palette",)),
        e("col_analogous_sea", "Analogous sea", "An analogous sea palette: teal, foam, slate", tags=("palette",)),
        e("col_triadic_circus", "Triadic circus", "Triadic primaries in costume and paint, a circus of hue", tags=("palette",)),
        e("col_muted_earth", "Muted earth", "Muted earth: clay, olive, dust, desaturated", tags=("palette",)),
        e("col_neon_night", "Neon night", "Neon night: magenta and cyan signs, wet street mixing them", tags=("palette",)),
        e("col_sodium_street", "Sodium street", "Sodium-vapor street: monochrome orange air, faces pumpkin", tags=("palette",)),
        e("col_fluorescent_office", "Fluorescent office", "Fluorescent office: green-magenta hum, sick skin, greenish walls", tags=("palette",)),
        e("col_candle_tungsten", "Candle tungsten", "Candle tungsten: deep amber, falloff to black, no cyan", tags=("palette",)),
        e("col_overcast_cyan", "Overcast cyan", "Overcast cyan: cool neutrals, open shadows, no gold", tags=("palette",)),
        e("col_golden_amber", "Golden amber", "Golden-hour amber: honey rims, long warm shadows", tags=("palette",)),
        e("col_magenta_hour", "Magenta hour", "Magenta hour: the sky a rose, faces catching it", tags=("palette",)),
        e("col_fine_grain", "Fine grain", "Fine grain, almost a clean scan, texture in the shadows only", tags=("grain",)),
        e("col_heavy_grain", "Heavy grain", "Heavy grain, dye clouds, a pushed stock look without a stock name", tags=("grain",)),
        e("col_dye_cloud", "Dye cloud", "Dye-cloud grain, color blotches in the midtones", tags=("grain",)),
        e("col_gate_weave", "Mild gate weave", "Mild gate-weave instability, the frame breathing in registration", tags=("texture",)),
        e("col_halation_red", "Red halation", "Red halation around practicals, a photochemical glow", tags=("texture",)),
        e("col_optical_vignette", "Optical vignette", "A mild optical vignette, corners a stop down, not a social-app darken", tags=("texture",)),
        e("col_no_vignette", "Even field", "An even field, no corner darkening, modern coated evenness", tags=("texture",)),
        e("col_hdr_display", "HDR display punch", "HDR display punch: speculars that hurt, deep but open shadows", tags=("display",)),
        e("col_theatrical_xenon", "Theatrical xenon", "Theatrical xenon print: a cool white, dense blacks, projection punch", tags=("print",)),
        e("col_dci_p3_rich", "Wide-gamut rich", "Wide-gamut rich: reds and greens more than a consumer display", tags=("display",)),
        e("col_rec709_safe", "Broadcast-safe", "Broadcast-safe: hues that survive a phone, no illegal primaries", tags=("display",)),
        e("col_skip_bleach_warm_print", "Skip-bleach warm print", "Skip-bleach then a warm print: silver bite with amber highlights", tags=("process",)),
        e("col_day_for_night_blue", "Day-for-night blue", "Day-for-night: underexposed daylight, a blue cast, crushed skies", tags=("grade",)),
        e("col_night_for_night", "Night-for-night", "Night-for-night: true dark, practicals as the only color, no blue wash", tags=("grade",)),
        e("col_warm_key_cool_fill_grade", "Warm key cool fill grade", "Grade as if warm key and cool fill: faces honey, rooms teal", tags=("grade",)),
        e("col_monochrome_split_gold", "Gold split mono", "Monochrome with gold split in the highlights only", tags=("mono",)),
        e("col_selene_blue_mono", "Selene blue mono", "Monochrome with a cold blue overall, moonlight implied", tags=("mono",)),
        e("col_sepia_full", "Full sepia", "Full sepia, no remaining cool, a uniform brown world", tags=("mono",)),
        e("col_cyanotype", "Cyanotype", "Cyanotype: a blue-and-white world, no brown", tags=("mono",)),
        e("col_high_key_color", "High-key color", "High-key color: pastels, open shadows, almost no black", tags=("grade",)),
        e("col_low_key_color", "Low-key color", "Low-key color: hue only in the small lit areas, the rest void", tags=("grade",)),
        e("col_saturated_theatrical", "Saturated theatrical", "Saturated theatrical: costumes and gels at eleven, still photochemical", tags=("palette",)),
        e("col_desat_almost_mono", "Almost mono color", "Almost mono: a whisper of hue, mostly silver", tags=("grade",)),
        e("col_only_red_accent", "Only red accent", "A grey world with one red accent (a lamp, a coat)", tags=("palette",)),
        e("col_only_green_accent", "Only green accent", "A grey world with one green practical or exit glow", tags=("palette",)),
        e("col_oppen_orange_teal_soft", "Soft complementary", "A soft complementary: not a meme crush, just warm skin vs cool rooms", tags=("grade",)),
        e("col_green_matrix_office", "Matrix-adjacent office", "Office green-black, monitors the only other hue - grammar, not a titled film", tags=("palette",)),
        e("col_amber_period", "Amber period", "Amber period: tobacco, varnish, no modern cool LEDs", tags=("palette",)),
        e("col_steel_winter", "Steel winter", "Steel winter: blue-grey, no gold, breath visible in the grade", tags=("palette",)),
        e("col_tropical_click", "Tropical click", "Tropical click: greens extra, cyans in water, skin sun-warm", tags=("palette",)),
        e("col_desert_bleach", "Desert bleach", "Desert bleach: yellow-white, color boiled out, hard sun", tags=("palette",)),
        e("col_jungle_moss", "Jungle moss", "Jungle moss: deep greens, little sky, brown-black shadows", tags=("palette",)),
        e("col_arctic_white", "Arctic white", "Arctic white: almost no saturation, blue in open shade, skin windburn red", tags=("palette",)),
        e("col_urban_sodium_mix", "Urban mix", "Urban mix: sodium orange plus cool shop LEDs in the same street", tags=("palette",)),
        e("col_club_gel", "Club gel", "Club gel: magenta and cyan on faces, no daylight", tags=("palette",)),
        e("col_hospital_green", "Hospital green", "Hospital green-practical, fluorescent skin, cold tile", tags=("palette",)),
        e("col_submarine_red", "Submarine red", "Submarine red-practical: a red world, instruments the only other marks", tags=("palette",)),
        e("col_spacecraft_led", "Spacecraft LED", "Spacecraft LED: cool white panels, no earth sun, slight green in screens", tags=("palette",)),
        e("col_candle_only_grade", "Candle-only grade", "Candle-only: no fill, falloff to black, skin only where flame reaches", tags=("palette",)),
        e("col_overcast_no_grade", "Honest overcast", "Honest overcast: almost no grade, true neutrals", tags=("honest",)),
        e("col_golden_no_crush", "Honest golden", "Honest golden hour: warmth from the sun, not a LUT crush", tags=("honest",)),
        e("col_night_no_teal", "Honest night", "Honest night: mixed practicals, no forced teal", tags=("honest",)),
        e("col_push_process_grain", "Push-process grain", "Push-process: more grain, more contrast, shadows blocking", tags=("grain",)),
        e("col_pull_process_soft", "Pull-process soft", "Pull-process: finer grain, gentler contrast, a softer world", tags=("grain",)),
        e("col_expired_shift", "Expired shift", "Expired-stock shift: odd magentas, uneven dye, surprise hues", tags=("capture",)),
        e("col_e6_slide", "Slide-film snap", "Slide-film snap: high contrast, rich blacks, saturated but not candy", tags=("capture",)),
        e("col_negative_scan_flat", "Flat negative scan", "A flat negative scan: low contrast, all color still in the file, waiting", tags=("capture",)),
        e("col_print_through_window", "Print through window", "As if printed through a window: a little flare, a little lift", tags=("print",)),
        e("col_ib_dye_transfer", "Dye-transfer density", "Dye-transfer-class density: extraordinary blacks and separated primaries", tags=("print",)),
        e("col_techniscope_grit_grade", "2-perf grit grade", "2-perf-class grit in the grade: a bit more grain for the same look", tags=("grain",)),
        e("col_65_fine_grade", "65 fine grade", "65-class fine: huge resolution, grain almost gone, color still organic", tags=("grain",)),
        e("col_16_chunky", "16 chunky", "16-class chunky grain, color a little wild, documentary bite", tags=("grain",)),
        e("col_super8_weave", "Super8 weave", "Super8-class: heavy grain, weave, halation, small-format nostalgia", tags=("grain",)),
        e("col_digital_clean", "Clean digital", "Clean digital: no grain, tight highlights, modern sensor", tags=("digital",)),
        e("col_log_flat", "Log-flat", "Log-flat: grey world, all latitude visible, not a finished print", tags=("digital",)),
        e("col_rec709_punch", "Rec709 punch", "A finished Rec.709 punch: contrast in, saturation honest", tags=("digital",)),
        e("col_hlg_tv", "HLG television", "HLG television: brighter windows, still a TV, not a cinema print", tags=("display",)),
        e("col_dci_warm_print", "DCI warm print", "DCI warm print: a slightly warm white point, theatrical", tags=("print",)),
        e("col_cool_led_cinema", "Cool LED cinema", "Cool LED cinema white: a modern projection, slightly blue", tags=("print",)),
        e("col_sepia_highlight_only", "Sepia highlights only", "Sepia in the highlights, shadows stay silver", tags=("grade",)),
        e("col_blue_shadow_only", "Blue shadows only", "Blue only in the shadows, highlights stay neutral", tags=("grade",)),
        e("col_green_shadow_horror", "Green shadow horror", "Green in the shadows, a sick room, highlights still skin", tags=("grade",)),
        e("col_magenta_shadow_night", "Magenta night shadow", "Magenta in night shadows, neon implied even without signs", tags=("grade",)),
        e("col_yellow_highlight_sun", "Yellow sun highlights", "Yellow only in the sun side, shade stays grey", tags=("grade",)),
        e("col_no_orange_teal", "No complementary crush", "A grade that refuses complementary crush: hues stay where the lamps put them", tags=("honest",)),
        e("col_skin_priority", "Skin priority", "Skin hue locked, the room allowed to go odd around it", tags=("grade",)),
        e("col_product_true", "Product-true color", "Product-true: the object's color honest, the room secondary", tags=("honest",)),
        e("col_food_appetite", "Food appetite", "Food appetite: slightly warm, greens of garnish extra, steam catching light", tags=("palette",)),
        e("col_fashion_bleach", "Fashion bleach", "Fashion bleach: pale skin, crushed color in clothes except one accent", tags=("palette",)),
        e("col_news_honest", "News honest", "News honest: no cinematic grade, mixed lamps as they are", tags=("honest",)),
        e("col_sports_punch", "Sports punch", "Sports punch: extra saturation, extra contrast, grass extra green", tags=("grade",)),
        e("col_music_video_smear_color", "Music-video smear color", "Music-video smear: shutter-drag color, lights painting streaks", tags=("grade",)),
        e("col_commercial_wrap_clean", "Commercial wrap clean", "Commercial wrap: clean whites, product color true, a little pop", tags=("honest",)),
        e("col_doc_available_mix", "Doc available mix", "Documentary available mix: whatever the room lamps are, no unify", tags=("honest",)),
        e("col_period_gaslight", "Period gaslight", "Period gaslight: green-yellow flame, no LED white", tags=("palette",)),
        e("col_period_oil", "Period oil lamp", "Period oil lamp: deep amber, smoke in the air as color", tags=("palette",)),
        e("col_period_daylight_north", "North-daylight period", "North-daylight period: cool window, warm interior mix", tags=("palette",)),
        e("col_cyber_wet_neon_grade", "Wet neon grade", "Wet neon grade: cyan and magenta in the street, skin taking both", tags=("palette",)),
        e("col_solar_clear", "Solar clear", "Solar clear: high noon color, almost no grade, honest sun", tags=("honest",)),
        e("col_folk_overcast_mud", "Folk overcast mud", "Folk overcast: mud, wool, no candy, a little green in the grey", tags=("palette",)),
        e("col_prestige_shallow_complement", "Prestige complementary", "Prestige complementary: shallow cream bokeh plus a polite teal-warm split", tags=("grade",)),
        e("col_action_haze_sun", "Action haze sun", "Action haze sun: backlight gold, dust in the air as color", tags=("palette",)),
        e("col_horror_underexposed_green", "Horror underexposed green", "Horror underexposed: a green-black hall, almost no fill", tags=("palette",)),
        e("col_giallo_gel", "Giallo gel night", "Giallo gel night: primary gels on faces, a comic of color", tags=("palette",)),
        e("col_noir_silver_hint", "Noir silver hint", "Noir with a hint of remaining color in practicals, the rest silver", tags=("mono",)),
        e("col_western_dust_noon_color", "Western dust noon", "Western dust noon: yellow-white, sky hard, no lush green", tags=("palette",)),
        e("col_western_magic_amber", "Western magic amber", "Western magic-hour amber: dust as gold, long shadows", tags=("palette",)),
        e("col_heist_cool_tungsten", "Heist cool tungsten", "Heist cool tungsten: a little cyan in the practicals, night work", tags=("palette",)),
        e("col_romcom_bounce_beauty", "Rom-com bounce beauty", "Rom-com bounce beauty: open warm faces, pretty highlights, no grit", tags=("palette",)),
        e("col_kitchen_sink_overcast", "Kitchen-sink overcast", "Kitchen-sink overcast: leftover color, no glamour, true rooms", tags=("honest",)),
        e("col_melodrama_window", "Melodrama window", "Melodrama window: a shaft of colored sun, the rest brown-dark", tags=("palette",)),
        e("col_gothic_candle", "Gothic candle", "Gothic candle: small warm islands, stone going blue-black", tags=("palette",)),
        e("col_found_footage_auto", "Found-footage auto", "Found-footage auto-white: mixed, ugly, honest to a consumer camera", tags=("honest",)),
        e("col_bodycam_auto", "Body-cam auto", "Body-cam auto: green-magenta hunt, headlights clipping", tags=("honest",)),
        e("col_security_bw", "Security mono", "Security mono: a high-corner black-and-white, no grade romance", tags=("mono",)),
        e("col_phone_ccd_soft", "Soft digital sensor", "Soft early-digital sensor: slightly smeary color, highlight bloom, no brand", tags=("digital",)),
        e("col_phone_mist_bloom", "Phone mist bloom", "Phone-shot mist-filter bloom: highlights milky, still a vertical frame", tags=("diffusion",)),
        e("col_lut_refused", "No LUT crush", "No LUT crush: color from lamps and weather only", tags=("honest",)),
        e("col_print_emulation_gentle", "Gentle print emulation", "Gentle print emulation: a little density, a little roll-off, still digital-clean underneath", tags=("print",)),
        e("col_silver_retention_night", "Silver night", "Silver retention at night: street lamps biting, color thin", tags=("process",)),
        e("col_pastel_dawn", "Pastel dawn", "Pastel dawn: pink and blue, low contrast, no black", tags=("palette",)),
        e("col_harsh_noon_color", "Harsh noon color", "Harsh noon: color boiled, contrast from the sun not the grade", tags=("honest",)),
        e("col_blue_hour_hush", "Blue-hour hush color", "Blue-hour hush: residual daylight cyan, lamps just coming on amber", tags=("palette",)),
        e("col_black_wet_night", "Black-wet night color", "Black-wet night: speculars on asphalt, color only in reflections", tags=("palette",)),
        e("col_sodium_plus_moon", "Sodium plus moon", "Sodium orange plus a cool moon fill, two nights in one street", tags=("palette",)),
        e("col_led_mixed_ugly", "Mixed LED ugly", "Mixed LED ugly: green shop, magenta bar, no unify - documentary night", tags=("honest",)),
        e("col_unify_night_teal", "Unify night cool", "Unify the night to one cool, practicals still warm islands", tags=("grade",)),
        e("col_unify_day_warm", "Unify day warm", "Unify the day to one warm, shadows still a little cool", tags=("grade",)),
        e("col_offset_green", "Offset green", "A slight green offset in the mids, 1970s television adjacent without a stock name", tags=("grade",)),
        e("col_offset_magenta", "Offset magenta", "A slight magenta offset, shadows going rose", tags=("grade",)),
        e("col_lifted_blacks_fog", "Lifted blacks fog", "Lifted blacks as if fog were in the grade, even indoors", tags=("grade",)),
        e("col_inky_blacks", "Inky blacks", "Inky blacks, no lift, a print that can hide things", tags=("grade",)),
        e("col_highlight_amber_only", "Amber highlights only", "Only the highlights go amber, mids stay grey", tags=("grade",)),
        e("col_shadow_teal_only", "Teal shadows only", "Only the shadows go teal, mids stay grey", tags=("grade",)),
        e("col_skin_desat_room_sat", "Skin desat room sat", "Skin a little desaturated, the room extra colorful", tags=("grade",)),
        e("col_skin_sat_room_desat", "Skin sat room desat", "Skin rich, the room almost grey", tags=("grade",)),
        e("col_duotone_amber_ink", "Duotone amber ink", "Duotone: amber and ink, two inks only", tags=("grade",)),
        e("col_duotone_ice_ink", "Duotone ice ink", "Duotone: ice blue and ink", tags=("grade",)),
        e("col_tritone_earth", "Tritone earth", "Tritone earth: cream, clay, ink", tags=("grade",)),
        e("col_vhs_shift", "Tape-shift color", "Tape-shift: chroma bleed, a little delay on reds, not a brand", tags=("texture",)),
        e("col_broadcast_ntsc_soft", "Broadcast soft chroma", "Broadcast-soft chroma: hues a little smeared, contrast TV-like", tags=("texture",)),
        e("col_imax_class_color_depth", "Large-format color depth", "Large-format-class color depth: more separation in the mids, still organic", tags=("format",)),
    ]
    return rows


def main() -> None:
    dump("composition.json", composition())
    dump("lenses_optics.json", lenses())
    dump("color_film_look.json", color())
    for name, fn in (
        ("composition.json", composition),
        ("lenses_optics.json", lenses),
        ("color_film_look.json", color),
    ):
        n = len(fn())
        if n < 100:
            raise SystemExit(f"{name} {n}")


if __name__ == "__main__":
    main()
