"""Services pack: 200 lab Apps for monetizable content-creation jobs.

Not collected by pytest (leading underscore). Tests and the builder import
``SERVICES``. Keep this module data-only. No ``klein_pack`` kinds.
"""

from __future__ import annotations

from dataclasses import dataclass

# Printer-native canvases. Wan family max is 1024, so landscape stays 832×480
# (still-to-video-5s) rather than the LTX 1280×704 grid.
_K_HERO = (1280, 704)
_K_DRAFT = (768, 432)
_K_SQ = (1024, 1024)
_K_45 = (1024, 1280)
_K_916 = (576, 1024)
_K_WIDE = (1216, 640)
_K_BANNER = (1536, 864)
_W_LAND = (832, 480)
_W_PORT = (480, 832)
_W_LOOP = (768, 768)
_L_LAND = (1280, 704)
_L_PORT = (768, 1280)


@dataclass(frozen=True)
class ServiceSpec:
    """One services-pack graph.

    Attributes:
        rel: ``extra.lab_rel`` (``services/ecommerce/pdp-on-white``).
        kind: ``klein_single`` | ``wan_i2v`` | ``wan_loop`` | ``ltx_av``.
        group: Vertical folder / catalog section id.
        size: Width x height latent pixels.
        prefix: Primary SaveImage / VHS filename prefix.
        occupancy: ``klein`` | ``wan`` | ``ltx``.
        sample_catalog: Existing sample index id (reuse families only).
        title: One-line job for Notes and catalog.
        lock: Job-specific framing appended to the family identity.
        enhance_pin: True pins Prompt Enhance off.
        template: Klein ``hero``/``draft``, or a video source rel.
        identity: ``creator`` | ``product`` | ``food`` | ``desk`` | ``interior``.
        ltx_mode: ``i2v`` or ``t2v``.
        audio_hint: LTX world-SFX widget.
        portrait: True uses 9:16 Wan/LTX printers.
    """

    rel: str
    kind: str
    group: str
    size: tuple[int, int]
    prefix: str
    occupancy: str
    sample_catalog: str
    title: str
    lock: str
    enhance_pin: bool = False
    template: str = "hero"
    identity: str = "creator"
    ltx_mode: str = "i2v"
    audio_hint: str = "world SFX matching the shot, no score"
    portrait: bool = False


def _klein_template(width: int, height: int) -> str:
    """Return Klein printer id for a canvas.

    Arguments:
        width: Latent width.
        height: Latent height.
    Returns:
        ``draft`` or ``hero``.
    """
    if (width, height) in {_K_DRAFT, _K_45, _K_916}:
        return "draft"
    return "hero"


def _k(
    vertical: str,
    stem: str,
    size: tuple[int, int],
    prefix: str,
    title: str,
    lock: str,
    *,
    catalog: str = "klein_t2i",
    identity: str = "creator",
) -> ServiceSpec:
    """Klein single-plate spec."""
    width, height = size
    return ServiceSpec(
        rel=f"services/{vertical}/{stem}",
        kind="klein_single",
        group=vertical,
        size=size,
        prefix=prefix,
        occupancy="klein",
        sample_catalog=catalog,
        title=title,
        lock=lock,
        template=_klein_template(width, height),
        identity=identity,
    )


def _w(
    vertical: str,
    stem: str,
    size: tuple[int, int],
    prefix: str,
    title: str,
    lock: str,
    *,
    loop: bool = False,
) -> ServiceSpec:
    """Wan silent I2V or ping-pong loop."""
    width, height = size
    portrait = height > width
    return ServiceSpec(
        rel=f"services/{vertical}/{stem}",
        kind="wan_loop" if loop else "wan_i2v",
        group=vertical,
        size=size,
        prefix=prefix,
        occupancy="wan",
        sample_catalog="wan_loop" if loop else "wan_i2v",
        title=title,
        lock=lock,
        enhance_pin=True,
        portrait=portrait,
        template=(
            "motion/loops/gif-loop"
            if loop
            else (
                "motion/silent/shorts-still-5s"
                if portrait
                else "motion/silent/still-to-video-5s"
            )
        ),
    )


def _l(
    vertical: str,
    stem: str,
    size: tuple[int, int],
    prefix: str,
    title: str,
    lock: str,
    *,
    mode: str = "i2v",
    catalog: str | None = None,
    audio: str = "world SFX matching the shot, no score",
) -> ServiceSpec:
    """LTX AV clip."""
    width, height = size
    portrait = height > width
    if catalog is None:
        catalog = "ltx_broll" if mode == "t2v" else "ltx_i2v"
    src = (
        "motion/av/shorts-still-12s"
        if portrait
        else (
            "motion/av/text-to-video-12s"
            if mode == "t2v"
            else "motion/av/still-to-video-12s"
        )
    )
    return ServiceSpec(
        rel=f"services/{vertical}/{stem}",
        kind="ltx_av",
        group=vertical,
        size=size,
        prefix=prefix,
        occupancy="ltx",
        sample_catalog=catalog,
        title=title,
        lock=lock,
        ltx_mode=mode,
        audio_hint=audio,
        portrait=portrait,
        template=src,
    )


_E = " Empty of lettering."
_TAKE = " One continuous five-second take. No cut."
_LOOP = " Locked camera. Ping-pong friendly. No walk."
_NOSCORE = " No score."

SERVICES: tuple[ServiceSpec, ...] = (
    # --- ecommerce (20) ---
    _k(
        "ecommerce",
        "pdp-on-white",
        _K_SQ,
        "ez_svc_pdp_white",
        "PDP on-white packshot 1:1",
        "Seamless light-gray cyclorama, three-quarter product, soft studio key." + _E,
        catalog="klein_product",
        identity="product",
    ),
    _w(
        "ecommerce",
        "pdp-in-use",
        _W_LAND,
        "ez_svc_pdp_use",
        "Silent in-use product motion ~5 s",
        "Hands ease the start-image mug. Slow, locked identity." + _TAKE,
    ),
    _w(
        "ecommerce",
        "pdp-hand-scale",
        _W_LAND,
        "ez_svc_pdp_hand",
        "Silent hand-scale product motion ~5 s",
        "A hand turns the start-image product for scale. Table holds." + _TAKE,
    ),
    _k(
        "ecommerce",
        "pdp-texture-macro",
        _K_SQ,
        "ez_svc_pdp_macro",
        "PDP texture macro 1:1",
        "Macro of glaze and oak grain, 85mm, shallow depth. Unmarked." + _E,
        catalog="klein_product",
        identity="product",
    ),
    _k(
        "ecommerce",
        "pdp-pack-back",
        _K_SQ,
        "ez_svc_pdp_back",
        "PDP pack-back still 1:1",
        "Rear three-quarter of the unmarked mug on seamless gray." + _E,
        catalog="klein_product",
        identity="product",
    ),
    _k(
        "ecommerce",
        "collection-banner",
        _K_BANNER,
        "ez_svc_coll_ban",
        "Collection banner 16:9",
        "Wide row of unmarked ceramics on oak, horizon low, quiet sky band." + _E,
        catalog="klein_product",
        identity="product",
    ),
    _k(
        "ecommerce",
        "marketplace-square",
        _K_SQ,
        "ez_svc_mkt_sq",
        "Marketplace square packshot 1:1",
        "Clean product, soft key, unmarked seamless. Readable at small sizes." + _E,
        catalog="klein_product",
        identity="product",
    ),
    _w(
        "ecommerce",
        "marketplace-lifestyle",
        _W_LAND,
        "ez_svc_mkt_life",
        "Silent marketplace lifestyle ~5 s",
        "Gentle breeze on linen beside the start-image mug. Locked identity." + _TAKE,
    ),
    _k(
        "ecommerce",
        "bundle-flatlay",
        _K_SQ,
        "ez_svc_bundle",
        "Bundle flatlay 1:1",
        "Overhead unmarked gift bundle on linen, soft window light." + _E,
        catalog="klein_product",
        identity="product",
    ),
    _k(
        "ecommerce",
        "gift-set-still",
        _K_45,
        "ez_svc_gift",
        "Gift-set still 4:5",
        "Stacked unmarked box and mug on oak, warm key, quiet edges." + _E,
        catalog="klein_product",
        identity="product",
    ),
    _w(
        "ecommerce",
        "restock-story",
        _W_PORT,
        "ez_svc_restock",
        "Silent restock story 9:16",
        "A carton slides onto a shelf. Locked vertical framing." + _TAKE,
    ),
    _w(
        "ecommerce",
        "drop-tease",
        _W_LAND,
        "ez_svc_drop",
        "Silent drop-tease ~5 s",
        "Slow reveal of the start-image product from shadow into key." + _TAKE,
    ),
    _k(
        "ecommerce",
        "cart-upsell-bg",
        _K_916,
        "ez_svc_cart",
        "Cart upsell background 9:16",
        "Quiet vertical still of the product, middle third holds the subject." + _E,
        catalog="klein_product",
        identity="product",
    ),
    _w(
        "ecommerce",
        "turntable-loop",
        _W_LOOP,
        "ez_svc_turn",
        "Silent product turntable loop",
        "Slow cyclic orbit around the start-image product." + _LOOP,
        loop=True,
    ),
    _w(
        "ecommerce",
        "drape-loop",
        _W_LOOP,
        "ez_svc_drape",
        "Silent fabric drape loop",
        "Cloth settles and lifts in a tiny cycle." + _LOOP,
        loop=True,
    ),
    _w(
        "ecommerce",
        "pour-fill-loop",
        _W_LOOP,
        "ez_svc_pour",
        "Silent pour-fill loop",
        "Liquid rises in the unmarked mug, then settles." + _LOOP,
        loop=True,
    ),
    _l(
        "ecommerce",
        "table-unbox-av",
        _L_LAND,
        "ez_svc_unbox",
        "Table unbox AV ~5 s",
        "Hands ease a box on oak. Paper rustle, cardboard." + _NOSCORE + " Keep the start image.",
        audio="paper rustle, cardboard, no score",
    ),
    _l(
        "ecommerce",
        "wear-test-av",
        _L_PORT,
        "ez_svc_wear",
        "Wear-test AV 9:16",
        "Slow try-on from the start still. Cloth rustle." + _NOSCORE,
        audio="cloth rustle, no score",
    ),
    _l(
        "ecommerce",
        "assemble-av",
        _L_LAND,
        "ez_svc_asm",
        "Assemble AV ~5 s",
        "Hands fit unmarked parts on a bench. Soft clicks, wood." + _NOSCORE,
        audio="soft clicks, wood, no score",
    ),
    _l(
        "ecommerce",
        "shelf-scan-av",
        _L_LAND,
        "ez_svc_shelf",
        "Shelf-scan AV ~5 s",
        "Slow lateral move along an unmarked shelf. Soft room tone." + _NOSCORE,
        audio="room tone, no score",
    ),
    # --- performance-ads (20) ---
    _w(
        "performance-ads",
        "hook-face",
        _W_PORT,
        "ez_svc_hk_face",
        "Silent hook-face punch 9:16",
        "Punch-in toward the start-image face in the first second, then hold." + _TAKE,
    ),
    _k(
        "performance-ads",
        "hook-problem",
        _K_45,
        "ez_svc_hk_prob",
        "Problem-hook still 4:5",
        "Subject large, concerned eyeline, plain wall. Quiet edges." + _E,
        catalog="klein_identity",
        identity="creator",
    ),
    _w(
        "performance-ads",
        "hook-result",
        _W_LAND,
        "ez_svc_hk_res",
        "Silent result-hook ~5 s",
        "Reveal the start-image result. Gentle light lift." + _TAKE,
    ),
    _w(
        "performance-ads",
        "ugc-selfie",
        _W_PORT,
        "ez_svc_ugc_self",
        "Silent UGC selfie 9:16",
        "Handheld micro-shake. Keep the start-image face locked. No whip pan." + _TAKE,
    ),
    _k(
        "performance-ads",
        "testimonial-still",
        _K_45,
        "ez_svc_testi",
        "Testimonial still 4:5",
        "Talking-head still, plain wall, warm key, quiet lower band." + _E,
        catalog="klein_identity",
        identity="creator",
    ),
    _k(
        "performance-ads",
        "offer-bed",
        _K_HERO,
        "ez_svc_offer",
        "Offer-bed still 16:9",
        "Quiet center for overlay type later. Subject small at the edge." + _E,
    ),
    _k(
        "performance-ads",
        "split-board",
        _K_WIDE,
        "ez_svc_split",
        "Split-board still ~1.91:1",
        "Left-weighted subject, quiet right third for a second plate later." + _E,
    ),
    _k(
        "performance-ads",
        "talent-plain-wall",
        _K_45,
        "ez_svc_talent",
        "Talent on a plain wall 4:5",
        "Three-quarter portrait, unmarked plaster, soft key." + _E,
        catalog="klein_identity",
        identity="creator",
    ),
    _k(
        "performance-ads",
        "reaction-still",
        _K_SQ,
        "ez_svc_react",
        "Reaction still 1:1",
        "Close face, genuine beat, unmarked room behind." + _E,
        catalog="klein_identity",
        identity="creator",
    ),
    _w(
        "performance-ads",
        "stitch-setup",
        _W_PORT,
        "ez_svc_stitch",
        "Silent stitch-setup 9:16",
        "Talent steps into the start-image mark. Locked vertical." + _TAKE,
    ),
    _k(
        "performance-ads",
        "story-safe-ad",
        _K_916,
        "ez_svc_story",
        "Story-safe ad still 9:16",
        "Subject in the middle third; top and bottom stay quiet for UI." + _E,
        catalog="klein_identity",
        identity="creator",
    ),
    _k(
        "performance-ads",
        "square-ad",
        _K_SQ,
        "ez_svc_sq_ad",
        "Square ad still 1:1",
        "Bold subject, quiet corners, readable at small sizes." + _E,
    ),
    _k(
        "performance-ads",
        "wide-ad",
        _K_WIDE,
        "ez_svc_wide_ad",
        "Wide ad still ~1.91:1",
        "Landscape in-feed still. Subject large, quiet edges." + _E,
    ),
    _k(
        "performance-ads",
        "vertical-ad",
        _K_916,
        "ez_svc_vert_ad",
        "Vertical ad still 9:16",
        "Center-weighted vertical. Quiet top and bottom." + _E,
        catalog="klein_identity",
        identity="creator",
    ),
    _l(
        "performance-ads",
        "ugc-kitchen-av",
        _L_PORT,
        "ez_svc_ugc_kit",
        "UGC kitchen AV 9:16",
        "Handheld kitchen take from the start still. Ceramic clink, room tone." + _NOSCORE,
        catalog="ltx_hook",
        audio="ceramic clink, room tone, no score",
    ),
    _l(
        "performance-ads",
        "ugc-car-av",
        _L_PORT,
        "ez_svc_ugc_car",
        "UGC car AV 9:16",
        "Passenger-seat take from the start still. Soft road hush." + _NOSCORE,
        catalog="ltx_hook",
        audio="road hush, no score",
    ),
    _l(
        "performance-ads",
        "ugc-mirror-av",
        _L_PORT,
        "ez_svc_ugc_mir",
        "UGC mirror AV 9:16",
        "Mirror selfie take from the start still. Soft room tone." + _NOSCORE,
        catalog="ltx_hook",
        audio="room tone, no score",
    ),
    _l(
        "performance-ads",
        "demo-hands-av",
        _L_PORT,
        "ez_svc_demo",
        "Demo-hands AV 9:16",
        "Hands demonstrate the start-image product. Soft taps." + _NOSCORE,
        audio="soft taps, no score",
    ),
    _l(
        "performance-ads",
        "problem-spot-av",
        _L_PORT,
        "ez_svc_prob",
        "Problem-spot AV 9:16",
        "Quick problem beat from the start still. World SFX only." + _NOSCORE,
        catalog="ltx_hook",
        audio="world SFX, no score",
    ),
    _l(
        "performance-ads",
        "bumper-av",
        _L_PORT,
        "ez_svc_bumper",
        "Bumper AV 9:16",
        "Short punch-in bumper from the start still. Soft whoosh." + _NOSCORE,
        catalog="ltx_hook",
        audio="soft whoosh, no score",
    ),
    # --- local-business (20) ---
    _w(
        "local-business",
        "storefront-day",
        _W_LAND,
        "ez_svc_sf_day",
        "Silent storefront day ~5 s",
        "Gentle traffic and awning drift. Keep the start-image facade." + _TAKE,
    ),
    _k(
        "local-business",
        "storefront-night",
        _K_HERO,
        "ez_svc_sf_nite",
        "Storefront night still 16:9",
        "Unmarked shopfront, warm practicals, wet pavement. No neon logos." + _E,
        catalog="klein_place",
        identity="interior",
    ),
    _k(
        "local-business",
        "maps-cover",
        _K_WIDE,
        "ez_svc_maps_cv",
        "Local maps cover ~1.91:1",
        "Wide unmarked facade, sky band empty, no sign lettering." + _E,
        catalog="klein_place",
        identity="interior",
    ),
    _k(
        "local-business",
        "maps-post",
        _K_SQ,
        "ez_svc_maps_ps",
        "Local maps post 1:1",
        "Square facade still, subject large, unmarked." + _E,
        catalog="klein_place",
        identity="interior",
    ),
    _k(
        "local-business",
        "menu-item",
        _K_SQ,
        "ez_svc_menu",
        "Menu-item still 1:1",
        "Overhead plated dish on unmarked crockery, oak, window light." + _E,
        catalog="klein_food",
        identity="food",
    ),
    _w(
        "local-business",
        "plated-special",
        _W_PORT,
        "ez_svc_plated",
        "Silent plated-special 9:16",
        "Steam lifts from the start-image plate. Locked vertical." + _TAKE,
    ),
    _k(
        "local-business",
        "treatment-room",
        _K_HERO,
        "ez_svc_treat",
        "Treatment-room still 16:9",
        "Unmarked clinic room, linen and pale plaster, quiet." + _E,
        catalog="klein_place",
        identity="interior",
    ),
    _k(
        "local-business",
        "gym-floor",
        _K_HERO,
        "ez_svc_gymfl",
        "Gym-floor still 16:9",
        "Unmarked gym, rubber floor, empty of logos and screens." + _E,
        catalog="klein_place",
        identity="interior",
    ),
    _k(
        "local-business",
        "team-headshot",
        _K_SQ,
        "ez_svc_team",
        "Team headshot 1:1",
        "Circle-safe headshot, plain wall, soft key." + _E,
        catalog="klein_identity",
        identity="creator",
    ),
    _k(
        "local-business",
        "owner-portrait",
        _K_45,
        "ez_svc_owner",
        "Owner portrait 4:5",
        "Three-quarter portrait in an unmarked doorway, warm key." + _E,
        catalog="klein_identity",
        identity="creator",
    ),
    _w(
        "local-business",
        "hours-bed",
        _W_LAND,
        "ez_svc_hours",
        "Silent hours-bed ~5 s",
        "Soft light pulse on a quiet unmarked facade. Tiny cyclic motion." + _TAKE,
    ),
    _k(
        "local-business",
        "interior-wide",
        _K_HERO,
        "ez_svc_int_w",
        "Interior wide still 16:9",
        "Wide unmarked dining room, oak and plaster, empty of lettering." + _E,
        catalog="klein_place",
        identity="interior",
    ),
    _k(
        "local-business",
        "interior-detail",
        _K_SQ,
        "ez_svc_int_d",
        "Interior detail still 1:1",
        "Detail of unmarked millwork and a ceramic, 50mm." + _E,
        catalog="klein_place",
        identity="interior",
    ),
    _w(
        "local-business",
        "parking-approach",
        _W_LAND,
        "ez_svc_park",
        "Silent parking approach ~5 s",
        "Slow push toward the start-image lot and facade." + _TAKE,
    ),
    _l(
        "local-business",
        "walk-in-av",
        _L_PORT,
        "ez_svc_walkin",
        "Walk-in AV 9:16",
        "Door opens into the start-image interior. Bell, room tone." + _NOSCORE,
        audio="door bell, room tone, no score",
    ),
    _l(
        "local-business",
        "service-broll-av",
        _L_LAND,
        "ez_svc_svcbr",
        "Service B-roll AV ~5 s",
        "Ambient unmarked shop floor. Soft tools, room tone." + _NOSCORE,
        mode="t2v",
        catalog="ltx_broll",
        audio="soft tools, room tone, no score",
    ),
    _l(
        "local-business",
        "staff-greet-av",
        _L_PORT,
        "ez_svc_greet",
        "Staff greet AV 9:16",
        "A host steps forward from the start still. Room tone, a smile beat." + _NOSCORE,
        catalog="ltx_dialogue",
        audio="room tone, no score",
    ),
    _l(
        "local-business",
        "close-up-av",
        _L_PORT,
        "ez_svc_close",
        "Close-up service AV 9:16",
        "Macro of unmarked hands at work. Soft taps." + _NOSCORE,
        audio="soft taps, no score",
    ),
    _l(
        "local-business",
        "kitchen-pass-av",
        _L_LAND,
        "ez_svc_kpass",
        "Kitchen-pass AV ~5 s",
        "Plates slide an unmarked pass. Ceramic, steam, no score.",
        mode="t2v",
        catalog="ltx_broll",
        audio="ceramic, steam, no score",
    ),
    _l(
        "local-business",
        "class-in-session-av",
        _L_LAND,
        "ez_svc_class",
        "Class-in-session AV ~5 s",
        "Wide unmarked studio class. Breath, shoe squeak, no score.",
        mode="t2v",
        catalog="ltx_broll",
        audio="breath, shoe squeak, no score",
    ),
    # --- education (20) ---
    _k(
        "education",
        "course-thumb",
        _K_HERO,
        "ez_svc_crs_th",
        "Course thumbnail 16:9",
        "Subject large, readable at small sizes, quiet lower band." + _E,
        catalog="klein_identity",
        identity="creator",
    ),
    _k(
        "education",
        "module-card",
        _K_SQ,
        "ez_svc_mod",
        "Module card 1:1",
        "Square still, one prop story, quiet edges." + _E,
    ),
    _k(
        "education",
        "lesson-title",
        _K_HERO,
        "ez_svc_lesson",
        "Lesson title plate 16:9",
        "Quiet center for overlay type later." + _E,
    ),
    _w(
        "education",
        "instructor-still",
        _W_LAND,
        "ez_svc_instr",
        "Silent instructor motion ~5 s",
        "Gentle gesture from the start-image instructor. Locked identity." + _TAKE,
    ),
    _k(
        "education",
        "board-still",
        _K_HERO,
        "ez_svc_board",
        "Board still 16:9",
        "Unmarked slate or wall, quiet for diagrams later." + _E,
        catalog="klein_place",
        identity="interior",
    ),
    _w(
        "education",
        "slide-break",
        _W_LAND,
        "ez_svc_slide",
        "Silent slide-break ~5 s",
        "Soft light drift on a quiet unmarked set." + _TAKE,
    ),
    _k(
        "education",
        "certificate-bed",
        _K_HERO,
        "ez_svc_cert",
        "Certificate bed 16:9",
        "Quiet linen and oak, center empty for a later overlay." + _E,
        identity="desk",
    ),
    _k(
        "education",
        "cohort-announce",
        _K_WIDE,
        "ez_svc_cohort",
        "Cohort announce still ~1.91:1",
        "Wide still, subject left-weighted, quiet right third." + _E,
        catalog="klein_identity",
        identity="creator",
    ),
    _w(
        "education",
        "waitlist-cover",
        _W_PORT,
        "ez_svc_wait",
        "Silent waitlist cover 9:16",
        "Slow push-in on the start-image cover still." + _TAKE,
    ),
    _k(
        "education",
        "syllabus-header",
        _K_BANNER,
        "ez_svc_syl",
        "Syllabus header 16:9",
        "Ultra-wide quiet desk, empty sky band." + _E,
        identity="desk",
    ),
    _w(
        "education",
        "campus-wide",
        _W_LAND,
        "ez_svc_campus",
        "Silent campus-wide ~5 s",
        "Slow establishing of unmarked paths and glass. Keep identity." + _TAKE,
    ),
    _k(
        "education",
        "lab-bench",
        _K_HERO,
        "ez_svc_bench",
        "Lab-bench still 16:9",
        "Unmarked bench, glassware, no logos on tools." + _E,
        catalog="klein_place",
        identity="interior",
    ),
    _k(
        "education",
        "student-desk",
        _K_HERO,
        "ez_svc_desk_st",
        "Student-desk still 16:9",
        "Sunlit oak desk, unmarked notebook, empty screens." + _E,
        identity="desk",
    ),
    _w(
        "education",
        "screencast-loop",
        _W_LOOP,
        "ez_svc_screen",
        "Silent screencast-bed loop",
        "Soft screen glow and dust motes." + _LOOP,
        loop=True,
    ),
    _w(
        "education",
        "recap-sting",
        _W_LAND,
        "ez_svc_recap",
        "Silent recap sting ~5 s",
        "Short push-in toward the start-image mark. No lettering." + _TAKE,
    ),
    _l(
        "education",
        "lecture-av",
        _L_LAND,
        "ez_svc_lect",
        "Lecture AV ~5 s",
        "Locked lecture take from the start still. Room tone, a chair." + _NOSCORE,
        catalog="ltx_dialogue",
        audio="room tone, chair, no score",
    ),
    _l(
        "education",
        "office-hours-av",
        _L_LAND,
        "ez_svc_ohours",
        "Office-hours AV ~5 s",
        "Desk conversation from the start still. Soft voices as room tone." + _NOSCORE,
        catalog="ltx_dialogue",
        audio="room tone, no score",
    ),
    _l(
        "education",
        "lab-demo-av",
        _L_LAND,
        "ez_svc_labdm",
        "Lab-demo AV ~5 s",
        "Hands demo unmarked glassware. Soft clink." + _NOSCORE,
        audio="glass clink, no score",
    ),
    _l(
        "education",
        "course-trailer-av",
        _L_PORT,
        "ez_svc_ctrail",
        "Course-trailer AV 9:16",
        "Vertical trailer hook from the start still. World SFX only." + _NOSCORE,
        catalog="ltx_hook",
        audio="world SFX, no score",
    ),
    _l(
        "education",
        "graduation-av",
        _L_LAND,
        "ez_svc_grad",
        "Graduation AV ~5 s",
        "Slow walk in an unmarked hall. Footfalls, room tone." + _NOSCORE,
        audio="footfalls, room tone, no score",
    ),
    # --- podcast-clips (20) ---
    _k(
        "podcast-clips",
        "clip-wide",
        _K_HERO,
        "ez_svc_clip_w",
        "Podcast clip still 16:9",
        "Two unmarked mics on oak, quiet lower fifth for a waveform later." + _E,
        identity="desk",
    ),
    _k(
        "podcast-clips",
        "clip-vertical",
        _K_916,
        "ez_svc_clip_v",
        "Podcast clip still 9:16",
        "Vertical desk still. Quiet lower third for a waveform." + _E,
        identity="desk",
    ),
    _k(
        "podcast-clips",
        "quote-vert",
        _K_916,
        "ez_svc_qte_v",
        "Quote-card background 9:16",
        "Quiet center for overlay type later." + _E,
        identity="desk",
    ),
    _k(
        "podcast-clips",
        "quote-wide",
        _K_HERO,
        "ez_svc_qte_w",
        "Quote-card background 16:9",
        "Quiet center for overlay type later." + _E,
        identity="desk",
    ),
    _w(
        "podcast-clips",
        "guest-intro",
        _W_PORT,
        "ez_svc_guest",
        "Silent guest-intro 9:16",
        "Slow push-in on the start-image guest. Locked identity." + _TAKE,
    ),
    _k(
        "podcast-clips",
        "host-solo",
        _K_SQ,
        "ez_svc_host",
        "Host-solo still 1:1",
        "Square host still, unmarked mic, warm key." + _E,
        catalog="klein_identity",
        identity="creator",
    ),
    _k(
        "podcast-clips",
        "two-shot",
        _K_HERO,
        "ez_svc_twoshot",
        "Two-shot still 16:9",
        "Two people at unmarked mics, oak desk, empty screens." + _E,
        catalog="klein_identity",
        identity="creator",
    ),
    _k(
        "podcast-clips",
        "waveform-bed",
        _K_HERO,
        "ez_svc_wave",
        "Waveform bed 16:9",
        "Quiet lower fifth for a waveform overlay later." + _E,
        identity="desk",
    ),
    _k(
        "podcast-clips",
        "chapter-art",
        _K_SQ,
        "ez_svc_chapt",
        "Chapter art 1:1",
        "Square chapter still, one prop story, unmarked." + _E,
        identity="desk",
    ),
    _w(
        "podcast-clips",
        "live-badge-bed",
        _W_PORT,
        "ez_svc_live",
        "Silent live-badge bed 9:16",
        "Soft cyclic light on a quiet set. Tiny motion only." + _TAKE,
    ),
    _k(
        "podcast-clips",
        "end-slate",
        _K_HERO,
        "ez_svc_endsl",
        "End slate 16:9",
        "Quiet center for overlay type later." + _E,
        identity="desk",
    ),
    _w(
        "podcast-clips",
        "clip-push-loop",
        _W_LOOP,
        "ez_svc_cpush",
        "Silent clip-push loop",
        "Tiny cyclic push toward the start-image desk." + _LOOP,
        loop=True,
    ),
    _w(
        "podcast-clips",
        "lower-third-loop",
        _W_LOOP,
        "ez_svc_lthird",
        "Silent lower-third bed loop",
        "Soft light drift. Lower band stays simple." + _LOOP,
        loop=True,
    ),
    _l(
        "podcast-clips",
        "talk-clip-av",
        _L_PORT,
        "ez_svc_talk",
        "Talk-clip AV 9:16",
        "Talking take from the start still. Room tone. Mouths will not match." + _NOSCORE,
        catalog="ltx_dialogue",
        audio="room tone, no score",
    ),
    _l(
        "podcast-clips",
        "laugh-bed-av",
        _L_LAND,
        "ez_svc_laugh",
        "Laugh-bed AV ~5 s",
        "Quiet set, a distant laugh as world SFX, no score.",
        mode="t2v",
        catalog="ltx_broll",
        audio="distant laugh, room tone, no score",
    ),
    _l(
        "podcast-clips",
        "desk-mic-av",
        _L_LAND,
        "ez_svc_dmic",
        "Desk-mic AV ~5 s",
        "Locked desk. Soft keycaps, a mug set down." + _NOSCORE,
        audio="keycaps, mug, no score",
    ),
    _l(
        "podcast-clips",
        "remote-guest-av",
        _L_LAND,
        "ez_svc_remote",
        "Remote-guest AV ~5 s",
        "Laptop-and-mic take from the start still. Soft room tone." + _NOSCORE,
        catalog="ltx_dialogue",
        audio="room tone, no score",
    ),
    _l(
        "podcast-clips",
        "studio-walk-av",
        _L_LAND,
        "ez_svc_swalk",
        "Studio-walk AV ~5 s",
        "Slow walk through an unmarked studio. Footfalls, room tone." + _NOSCORE,
        mode="t2v",
        catalog="ltx_broll",
        audio="footfalls, room tone, no score",
    ),
    _l(
        "podcast-clips",
        "clip-montage-av",
        _L_PORT,
        "ez_svc_mont",
        "Clip-montage AV 9:16",
        "Fast energy from the start still. World SFX only." + _NOSCORE,
        catalog="ltx_hook",
        audio="world SFX, no score",
    ),
    _l(
        "podcast-clips",
        "season-trailer-av",
        _L_PORT,
        "ez_svc_strail",
        "Season-trailer AV 9:16",
        "Vertical trailer hook from the start still. Soft whoosh." + _NOSCORE,
        catalog="ltx_hook",
        audio="soft whoosh, no score",
    ),
    # --- real-estate (20) ---
    _w(
        "real-estate",
        "listing-hero",
        _W_LAND,
        "ez_svc_list_h",
        "Silent listing-hero ~5 s",
        "Slow push toward the start-image facade. Keep identity." + _TAKE,
    ),
    _k(
        "real-estate",
        "listing-kitchen",
        _K_HERO,
        "ez_svc_list_k",
        "Listing kitchen still 16:9",
        "Unmarked kitchen, pale stone and oak, empty of lettering." + _E,
        catalog="klein_place",
        identity="interior",
    ),
    _k(
        "real-estate",
        "listing-bath",
        _K_HERO,
        "ez_svc_list_b",
        "Listing bath still 16:9",
        "Unmarked wet room, stone and frosted glass." + _E,
        catalog="klein_place",
        identity="interior",
    ),
    _k(
        "real-estate",
        "listing-bedroom",
        _K_HERO,
        "ez_svc_list_br",
        "Listing bedroom still 16:9",
        "Unmarked bedroom, linen bedding, quiet window." + _E,
        catalog="klein_place",
        identity="interior",
    ),
    _w(
        "real-estate",
        "listing-yard",
        _W_LAND,
        "ez_svc_list_y",
        "Silent listing-yard ~5 s",
        "Breeze in unmarked grass and leaves. Keep the start image." + _TAKE,
    ),
    _k(
        "real-estate",
        "listing-twilight",
        _K_HERO,
        "ez_svc_list_tw",
        "Listing twilight still 16:9",
        "Warm interior glow, dusk sky, unmarked home." + _E,
        catalog="klein_place",
        identity="interior",
    ),
    _k(
        "real-estate",
        "aerial-still",
        _K_BANNER,
        "ez_svc_aerial",
        "Aerial listing still 16:9",
        "High unmarked neighborhood, no logos on roofs." + _E,
        catalog="klein_place",
        identity="interior",
    ),
    _k(
        "real-estate",
        "agent-headshot",
        _K_SQ,
        "ez_svc_agent",
        "Agent headshot 1:1",
        "Circle-safe headshot, plain wall, professional key." + _E,
        catalog="klein_identity",
        identity="creator",
    ),
    _w(
        "real-estate",
        "just-listed",
        _W_LAND,
        "ez_svc_jlist",
        "Silent just-listed ~5 s",
        "Gentle light lift on the start-image facade." + _TAKE,
    ),
    _k(
        "real-estate",
        "open-house-bed",
        _K_WIDE,
        "ez_svc_openh",
        "Open-house bed ~1.91:1",
        "Quiet wide interior, center empty for overlay type later." + _E,
        catalog="klein_place",
        identity="interior",
    ),
    _k(
        "real-estate",
        "sold-slate",
        _K_SQ,
        "ez_svc_sold",
        "Sold slate 1:1",
        "Quiet square still, center empty for overlay type later." + _E,
        catalog="klein_place",
        identity="interior",
    ),
    _k(
        "real-estate",
        "empty-room",
        _K_HERO,
        "ez_svc_empty",
        "Empty-room still 16:9",
        "Vacant unmarked room, plaster and oak, raking light." + _E,
        catalog="klein_place",
        identity="interior",
    ),
    _k(
        "real-estate",
        "dressed-room",
        _K_HERO,
        "ez_svc_dress",
        "Dressed-room still 16:9",
        "Staged unmarked living room, linen sofa, no logos." + _E,
        catalog="klein_place",
        identity="interior",
    ),
    _w(
        "real-estate",
        "amenity-loop",
        _W_LOOP,
        "ez_svc_amen",
        "Silent amenity loop",
        "Water shimmers in an unmarked pool. Tiny cyclic motion." + _LOOP,
        loop=True,
    ),
    _w(
        "real-estate",
        "key-turn-loop",
        _W_LOOP,
        "ez_svc_key",
        "Silent key-turn loop",
        "A key turns in an unmarked lock, then settles." + _LOOP,
        loop=True,
    ),
    _l(
        "real-estate",
        "walkthrough-av",
        _L_LAND,
        "ez_svc_walkth",
        "Walkthrough AV ~5 s",
        "Slow walk through the start-image interior. Footfalls, room tone." + _NOSCORE,
        audio="footfalls, room tone, no score",
    ),
    _l(
        "real-estate",
        "twilight-av",
        _L_LAND,
        "ez_svc_twil",
        "Twilight AV ~5 s",
        "Dusk hold on the start-image home. Distant traffic, crickets." + _NOSCORE,
        audio="distant traffic, crickets, no score",
    ),
    _l(
        "real-estate",
        "neighborhood-av",
        _L_LAND,
        "ez_svc_nhood",
        "Neighborhood AV ~5 s",
        "Slow street establishing. Birds, distant cars, no score.",
        mode="t2v",
        catalog="ltx_broll",
        audio="birds, distant cars, no score",
    ),
    _l(
        "real-estate",
        "aerial-push-av",
        _L_LAND,
        "ez_svc_apush",
        "Aerial-push AV ~5 s",
        "Slow aerial push over unmarked roofs. Wind, no score.",
        mode="t2v",
        catalog="ltx_broll",
        audio="wind, no score",
    ),
    _l(
        "real-estate",
        "handoff-av",
        _L_LAND,
        "ez_svc_handof",
        "Handoff AV ~5 s",
        "Keys pass on an unmarked porch. Metal clink, room tone." + _NOSCORE,
        catalog="ltx_dialogue",
        audio="key clink, room tone, no score",
    ),
    # --- fashion-beauty (20) ---
    _k(
        "fashion-beauty",
        "lookbook-cover",
        _K_45,
        "ez_svc_lookbk",
        "Lookbook cover 4:5",
        "Full-look still, unmarked garments, warm key." + _E,
        catalog="klein_identity",
        identity="creator",
    ),
    _w(
        "fashion-beauty",
        "look-full",
        _W_PORT,
        "ez_svc_look_f",
        "Silent full-look 9:16",
        "A warm breeze moves coat hem. Locked vertical identity." + _TAKE,
    ),
    _k(
        "fashion-beauty",
        "look-detail",
        _K_SQ,
        "ez_svc_look_d",
        "Look detail 1:1",
        "Seam and fabric macro, 85mm, unmarked." + _E,
        catalog="klein_product",
        identity="product",
    ),
    _k(
        "fashion-beauty",
        "look-back",
        _K_45,
        "ez_svc_look_b",
        "Look back 4:5",
        "Rear three-quarter of the same unmarked look." + _E,
        catalog="klein_identity",
        identity="creator",
    ),
    _k(
        "fashion-beauty",
        "campaign-hero",
        _K_HERO,
        "ez_svc_camp_h",
        "Campaign hero 16:9",
        "Wide fashion still, unmarked street, golden hour." + _E,
        catalog="klein_identity",
        identity="creator",
    ),
    _k(
        "fashion-beauty",
        "beauty-pack",
        _K_SQ,
        "ez_svc_bpack",
        "Beauty packshot 1:1",
        "Unmarked bottles on marble, soft beauty key." + _E,
        catalog="klein_product",
        identity="product",
    ),
    _k(
        "fashion-beauty",
        "swatch-macro",
        _K_SQ,
        "ez_svc_swatch",
        "Swatch macro 1:1",
        "Macro of unmarked cream on skin-tone ceramic, 85mm." + _E,
        catalog="klein_product",
        identity="product",
    ),
    _k(
        "fashion-beauty",
        "texture-fill",
        _K_SQ,
        "ez_svc_texfil",
        "Texture fill 1:1",
        "Full-frame fabric or cream texture, unmarked." + _E,
        catalog="klein_product",
        identity="product",
    ),
    _w(
        "fashion-beauty",
        "street-look",
        _W_PORT,
        "ez_svc_street",
        "Silent street-look 9:16",
        "Slow walk-hold from the start still. Fabric breeze." + _TAKE,
    ),
    _w(
        "fashion-beauty",
        "makeup-step",
        _W_PORT,
        "ez_svc_makeup",
        "Silent makeup-step 9:16",
        "A brush passes the start-image cheek. Locked identity." + _TAKE,
    ),
    _k(
        "fashion-beauty",
        "editorial-still",
        _K_45,
        "ez_svc_edit",
        "Editorial still 4:5",
        "Fashion editorial still, unmarked wardrobe, hard rim." + _E,
        catalog="klein_identity",
        identity="creator",
    ),
    _w(
        "fashion-beauty",
        "hair-loop",
        _W_PORT,
        "ez_svc_hair",
        "Silent hair loop 9:16",
        "Hair lifts in a tiny cycle." + _LOOP,
        loop=True,
    ),
    _w(
        "fashion-beauty",
        "glow-loop",
        _W_LOOP,
        "ez_svc_glow",
        "Silent glow loop",
        "Skin highlight shimmers, then settles." + _LOOP,
        loop=True,
    ),
    _w(
        "fashion-beauty",
        "nail-loop",
        _W_LOOP,
        "ez_svc_nail",
        "Silent nail loop",
        "A tiny light crawl across unmarked nails." + _LOOP,
        loop=True,
    ),
    _l(
        "fashion-beauty",
        "fabric-twirl-av",
        _L_PORT,
        "ez_svc_twirl",
        "Fabric-twirl AV 9:16",
        "Slow twirl from the start still. Cloth rustle." + _NOSCORE,
        audio="cloth rustle, no score",
    ),
    _l(
        "fashion-beauty",
        "walk-av",
        _L_PORT,
        "ez_svc_fwalk",
        "Fashion walk AV 9:16",
        "Slow walk from the start still. Heel, cloth." + _NOSCORE,
        audio="heel, cloth, no score",
    ),
    _l(
        "fashion-beauty",
        "get-ready-av",
        _L_PORT,
        "ez_svc_ready",
        "Get-ready AV 9:16",
        "Getting-ready take from the start still. Soft room tone." + _NOSCORE,
        catalog="ltx_hook",
        audio="room tone, no score",
    ),
    _l(
        "fashion-beauty",
        "beauty-unbox-av",
        _L_PORT,
        "ez_svc_bunbox",
        "Beauty unbox AV 9:16",
        "Hands ease an unmarked compact. Soft clicks." + _NOSCORE,
        audio="soft clicks, no score",
    ),
    _l(
        "fashion-beauty",
        "campaign-av",
        _L_LAND,
        "ez_svc_camp_v",
        "Campaign AV ~5 s",
        "Slow campaign take from the start still. Wind, cloth." + _NOSCORE,
        catalog="ltx_hook",
        audio="wind, cloth, no score",
    ),
    _l(
        "fashion-beauty",
        "fitting-av",
        _L_PORT,
        "ez_svc_fit",
        "Fitting AV 9:16",
        "Fitting-room take from the start still. Cloth, zipper hush." + _NOSCORE,
        audio="cloth, zipper, no score",
    ),
    # --- b2b-saas (20) ---
    _k(
        "b2b-saas",
        "ui-hero",
        _K_BANNER,
        "ez_svc_ui",
        "UI hero still 16:9",
        "Unmarked laptop with an empty screen on oak, wide banner." + _E,
        identity="desk",
    ),
    _k(
        "b2b-saas",
        "feature-card",
        _K_SQ,
        "ez_svc_feat",
        "Feature card 1:1",
        "Quiet square still, empty screen, center clear for type later." + _E,
        identity="desk",
    ),
    _k(
        "b2b-saas",
        "case-cover",
        _K_WIDE,
        "ez_svc_case",
        "Case-study cover ~1.91:1",
        "Wide still, subject left-weighted, quiet right third." + _E,
        catalog="klein_identity",
        identity="creator",
    ),
    _k(
        "b2b-saas",
        "webinar-thumb",
        _K_HERO,
        "ez_svc_webth",
        "Webinar thumbnail 16:9",
        "Subject large, readable at small sizes, empty screens." + _E,
        catalog="klein_identity",
        identity="creator",
    ),
    _k(
        "b2b-saas",
        "ebook-cover",
        _K_45,
        "ez_svc_ebook",
        "Ebook cover 4:5",
        "Quiet 4:5 still, center empty for overlay type later." + _E,
        identity="desk",
    ),
    _k(
        "b2b-saas",
        "report-cover",
        _K_WIDE,
        "ez_svc_report",
        "Report cover ~1.91:1",
        "Wide still, unmarked desk, quiet right third." + _E,
        identity="desk",
    ),
    _w(
        "b2b-saas",
        "founder-still",
        _W_LAND,
        "ez_svc_found",
        "Silent founder motion ~5 s",
        "Gentle gesture from the start-image founder. Locked identity." + _TAKE,
    ),
    _w(
        "b2b-saas",
        "office-wide",
        _W_LAND,
        "ez_svc_off_w",
        "Silent office-wide ~5 s",
        "Soft people-motion in an unmarked office. Empty screens." + _TAKE,
    ),
    _k(
        "b2b-saas",
        "culture-still",
        _K_HERO,
        "ez_svc_cult",
        "Culture still 16:9",
        "Team in an unmarked lounge, empty of logos." + _E,
        catalog="klein_identity",
        identity="creator",
    ),
    _k(
        "b2b-saas",
        "keynote-still",
        _K_HERO,
        "ez_svc_keynt",
        "Keynote still 16:9",
        "Speaker on an unmarked stage, empty screen behind." + _E,
        catalog="klein_identity",
        identity="creator",
    ),
    _w(
        "b2b-saas",
        "changelog-card",
        _W_LAND,
        "ez_svc_chglog",
        "Silent changelog card ~5 s",
        "Soft cursor-like light crawl on an empty unmarked screen." + _TAKE,
    ),
    _k(
        "b2b-saas",
        "pricing-bed",
        _K_HERO,
        "ez_svc_price",
        "Pricing bed 16:9",
        "Quiet center for overlay type later. Empty screens." + _E,
        identity="desk",
    ),
    _k(
        "b2b-saas",
        "launch-still",
        _K_HERO,
        "ez_svc_launch",
        "Launch still 16:9",
        "Quiet launch plate, unmarked desk, empty of lettering." + _E,
        identity="desk",
    ),
    _k(
        "b2b-saas",
        "diagram-bed",
        _K_HERO,
        "ez_svc_diag",
        "Diagram bed 16:9",
        "Quiet center for a diagram overlay later." + _E,
        identity="desk",
    ),
    _l(
        "b2b-saas",
        "cursor-demo-av",
        _L_LAND,
        "ez_svc_cursor",
        "Cursor-demo AV ~5 s",
        "Empty unmarked screen, a cursor crawls. Soft clicks." + _NOSCORE,
        audio="soft clicks, no score",
    ),
    _l(
        "b2b-saas",
        "explainer-av",
        _L_LAND,
        "ez_svc_expl",
        "Explainer AV ~5 s",
        "Talking explainer from the start still. Room tone." + _NOSCORE,
        catalog="ltx_hook",
        audio="room tone, no score",
    ),
    _l(
        "b2b-saas",
        "office-broll-av",
        _L_LAND,
        "ez_svc_offbr",
        "Office B-roll AV ~5 s",
        "Ambient unmarked office. Keycaps, HVAC hush, no score.",
        mode="t2v",
        catalog="ltx_broll",
        audio="keycaps, HVAC, no score",
    ),
    _l(
        "b2b-saas",
        "webinar-open-av",
        _L_LAND,
        "ez_svc_webop",
        "Webinar-open AV ~5 s",
        "Host sits down from the start still. Chair, room tone." + _NOSCORE,
        catalog="ltx_hook",
        audio="chair, room tone, no score",
    ),
    _l(
        "b2b-saas",
        "customer-story-av",
        _L_PORT,
        "ez_svc_cust",
        "Customer-story AV 9:16",
        "Talking take from the start still. Room tone. Mouths will not match." + _NOSCORE,
        catalog="ltx_dialogue",
        audio="room tone, no score",
    ),
    _l(
        "b2b-saas",
        "ship-day-av",
        _L_LAND,
        "ez_svc_ship",
        "Ship-day AV ~5 s",
        "Soft celebration on an unmarked desk. Paper motes, no flash." + _NOSCORE,
        catalog="ltx_hook",
        audio="paper motes, room tone, no score",
    ),
    # --- events-wedding (20) ---
    _k(
        "events-wedding",
        "save-the-date",
        _K_45,
        "ez_svc_std",
        "Save-the-date still 4:5",
        "Quiet 4:5 still, floral unmarked, center empty for type later." + _E,
        catalog="klein_place",
        identity="interior",
    ),
    _k(
        "events-wedding",
        "invite-bed",
        _K_45,
        "ez_svc_invite",
        "Invite bed 4:5",
        "Linen and unmarked stationery, center empty for type later." + _E,
        catalog="klein_product",
        identity="product",
    ),
    _k(
        "events-wedding",
        "program-cover",
        _K_45,
        "ez_svc_prog",
        "Program cover 4:5",
        "Quiet cover still, unmarked florals, empty of lettering." + _E,
        catalog="klein_place",
        identity="interior",
    ),
    _w(
        "events-wedding",
        "welcome-sign",
        _W_LAND,
        "ez_svc_welc",
        "Silent welcome-sign ~5 s",
        "Breeze on unmarked florals beside a blank board." + _TAKE,
    ),
    _k(
        "events-wedding",
        "table-bed",
        _K_HERO,
        "ez_svc_table",
        "Table bed 16:9",
        "Unmarked place setting, linen, quiet for overlay type later." + _E,
        catalog="klein_place",
        identity="interior",
    ),
    _k(
        "events-wedding",
        "highlight-still",
        _K_45,
        "ez_svc_hlite",
        "Highlight still 4:5",
        "Candid still, unmarked venue, warm practicals." + _E,
        catalog="klein_identity",
        identity="creator",
    ),
    _w(
        "events-wedding",
        "first-look",
        _W_PORT,
        "ez_svc_first",
        "Silent first-look 9:16",
        "Slow turn from the start still. Fabric breeze." + _TAKE,
    ),
    _w(
        "events-wedding",
        "venue-wide",
        _W_LAND,
        "ez_svc_venue",
        "Silent venue-wide ~5 s",
        "Gentle guest-motion in an unmarked hall. Keep identity." + _TAKE,
    ),
    _k(
        "events-wedding",
        "details-flatlay",
        _K_SQ,
        "ez_svc_detfl",
        "Details flatlay 1:1",
        "Overhead unmarked rings and florals on linen." + _E,
        catalog="klein_product",
        identity="product",
    ),
    _k(
        "events-wedding",
        "speaker-still",
        _K_45,
        "ez_svc_speak",
        "Speaker still 4:5",
        "Conference speaker, unmarked lectern, empty screen." + _E,
        catalog="klein_identity",
        identity="creator",
    ),
    _k(
        "events-wedding",
        "badge-bed",
        _K_SQ,
        "ez_svc_badge",
        "Badge bed 1:1",
        "Quiet square still, center empty for overlay type later." + _E,
    ),
    _k(
        "events-wedding",
        "sponsor-slate",
        _K_HERO,
        "ez_svc_spon",
        "Sponsor slate 16:9",
        "Quiet wide still, empty of logos and lettering." + _E,
    ),
    _l(
        "events-wedding",
        "processional-av",
        _L_LAND,
        "ez_svc_proc",
        "Processional AV ~5 s",
        "Slow aisle walk from the start still. Cloth, soft steps." + _NOSCORE,
        audio="soft steps, cloth, no score",
    ),
    _l(
        "events-wedding",
        "dance-floor-av",
        _L_LAND,
        "ez_svc_dance",
        "Dance-floor AV ~5 s",
        "Ambient unmarked dance floor. Murmur, no score.",
        mode="t2v",
        catalog="ltx_broll",
        audio="crowd murmur, no score",
    ),
    _l(
        "events-wedding",
        "sparkler-exit-av",
        _L_LAND,
        "ez_svc_spark",
        "Sparkler-exit AV ~5 s",
        "Warm spark trails, unmarked driveway. Soft fizz." + _NOSCORE,
        audio="soft fizz, no score",
    ),
    _l(
        "events-wedding",
        "conference-av",
        _L_LAND,
        "ez_svc_conf",
        "Conference AV ~5 s",
        "Ambient unmarked hall. Murmur, chair, no score.",
        mode="t2v",
        catalog="ltx_broll",
        audio="murmur, chair, no score",
    ),
    _l(
        "events-wedding",
        "recap-av",
        _L_LAND,
        "ez_svc_erecap",
        "Recap AV ~5 s",
        "Slow recap take from the start still. World SFX only." + _NOSCORE,
        catalog="ltx_hook",
        audio="world SFX, no score",
    ),
    _l(
        "events-wedding",
        "aftermovie-hook-av",
        _L_PORT,
        "ez_svc_after",
        "Aftermovie hook AV 9:16",
        "Vertical hook from the start still. Soft whoosh." + _NOSCORE,
        catalog="ltx_hook",
        audio="soft whoosh, no score",
    ),
    _l(
        "events-wedding",
        "rehearsal-av",
        _L_LAND,
        "ez_svc_rehr",
        "Rehearsal AV ~5 s",
        "Quiet rehearsal from the start still. Room tone, a laugh hush." + _NOSCORE,
        audio="room tone, no score",
    ),
    _l(
        "events-wedding",
        "trailer-av",
        _L_PORT,
        "ez_svc_trail",
        "Event trailer AV 9:16",
        "Vertical trailer from the start still. World SFX only." + _NOSCORE,
        catalog="ltx_hook",
        audio="world SFX, no score",
    ),
    # --- fitness-travel (20) ---
    _w(
        "fitness-travel",
        "coach-still",
        _W_PORT,
        "ez_svc_coach",
        "Silent coach motion 9:16",
        "One coaching gesture from the start still. Locked identity." + _TAKE,
    ),
    _k(
        "fitness-travel",
        "move-still",
        _K_45,
        "ez_svc_move",
        "Move still 4:5",
        "Athletic still, unmarked gym, empty of logos." + _E,
        catalog="klein_identity",
        identity="creator",
    ),
    _k(
        "fitness-travel",
        "gym-wide",
        _K_HERO,
        "ez_svc_gymw",
        "Gym wide still 16:9",
        "Wide unmarked gym, rubber floor, empty screens." + _E,
        catalog="klein_place",
        identity="interior",
    ),
    _k(
        "fitness-travel",
        "home-gym",
        _K_HERO,
        "ez_svc_hgym",
        "Home-gym still 16:9",
        "Unmarked spare room, a mat, morning window." + _E,
        catalog="klein_place",
        identity="interior",
    ),
    _k(
        "fitness-travel",
        "recovery-still",
        _K_45,
        "ez_svc_recov",
        "Recovery still 4:5",
        "Quiet recovery still, linen and a mug, unmarked." + _E,
        catalog="klein_identity",
        identity="creator",
    ),
    _k(
        "fitness-travel",
        "meal-prep",
        _K_45,
        "ez_svc_meal",
        "Meal-prep still 4:5",
        "Plated prep on unmarked crockery, oak, window light." + _E,
        catalog="klein_food",
        identity="food",
    ),
    _w(
        "fitness-travel",
        "resort-hero",
        _W_LAND,
        "ez_svc_resort",
        "Silent resort-hero ~5 s",
        "Palm breeze on the start-image terrace. Keep identity." + _TAKE,
    ),
    _k(
        "fitness-travel",
        "room-still",
        _K_HERO,
        "ez_svc_room",
        "Resort room still 16:9",
        "Unmarked guest room, linen, bright bay slot." + _E,
        catalog="klein_place",
        identity="interior",
    ),
    _k(
        "fitness-travel",
        "pool-still",
        _K_HERO,
        "ez_svc_pool",
        "Pool still 16:9",
        "Unmarked pool, palms, no lettering on tiles." + _E,
        catalog="klein_place",
        identity="interior",
    ),
    _w(
        "fitness-travel",
        "trail-still",
        _W_LAND,
        "ez_svc_trailf",
        "Silent trail ~5 s",
        "Leaves drift on the start-image path. Locked identity." + _TAKE,
    ),
    _w(
        "fitness-travel",
        "city-arrive",
        _W_LAND,
        "ez_svc_arrive",
        "Silent city-arrive ~5 s",
        "Slow dolly past unmarked glass towers. Keep identity." + _TAKE,
    ),
    _w(
        "fitness-travel",
        "rep-loop",
        _W_PORT,
        "ez_svc_rep",
        "Silent rep loop 9:16",
        "One athletic rep cycles. Ping-pong friendly." + _LOOP,
        loop=True,
    ),
    _w(
        "fitness-travel",
        "stretch-loop",
        _W_PORT,
        "ez_svc_strch",
        "Silent stretch loop 9:16",
        "A stretch settles and repeats." + _LOOP,
        loop=True,
    ),
    _w(
        "fitness-travel",
        "waves-loop",
        _W_LOOP,
        "ez_svc_waves",
        "Silent waves loop",
        "Unmarked shoreline, a small wave cycle." + _LOOP,
        loop=True,
    ),
    _l(
        "fitness-travel",
        "workout-av",
        _L_PORT,
        "ez_svc_work",
        "Workout AV 9:16",
        "One athletic take from the start still. Breath, shoe squeak." + _NOSCORE,
        audio="breath, shoe squeak, no score",
    ),
    _l(
        "fitness-travel",
        "class-av",
        _L_PORT,
        "ez_svc_fclass",
        "Fitness class AV 9:16",
        "Class take from the start still. Breath, room tone." + _NOSCORE,
        audio="breath, room tone, no score",
    ),
    _l(
        "fitness-travel",
        "check-in-av",
        _L_LAND,
        "ez_svc_check",
        "Check-in AV ~5 s",
        "Lobby check-in from the start still. Soft voices as room tone." + _NOSCORE,
        audio="room tone, no score",
    ),
    _l(
        "fitness-travel",
        "tour-av",
        _L_LAND,
        "ez_svc_tour",
        "Tour AV ~5 s",
        "Slow resort tour. Wind, distant surf, no score.",
        mode="t2v",
        catalog="ltx_broll",
        audio="wind, distant surf, no score",
    ),
    _l(
        "fitness-travel",
        "sunset-av",
        _L_LAND,
        "ez_svc_sun",
        "Sunset AV ~5 s",
        "Locked sunset hold. Wind, distant surf, no score.",
        mode="t2v",
        catalog="ltx_broll",
        audio="wind, distant surf, no score",
    ),
    _l(
        "fitness-travel",
        "packing-av",
        _L_PORT,
        "ez_svc_pack",
        "Packing AV 9:16",
        "Hands pack unmarked clothes. Soft fabric, zipper." + _NOSCORE,
        audio="fabric, zipper, no score",
    ),
)

if len(SERVICES) != 200:
    raise RuntimeError(f"SERVICES must have 200 specs, got {len(SERVICES)}")


def services_pin_off() -> frozenset[str]:
    """Return lab_rel ids that pin Prompt Enhance off."""
    return frozenset(spec.rel for spec in SERVICES if spec.enhance_pin)


def services_stamp_rows() -> tuple[tuple[str, str, tuple[str, ...], bool], ...]:
    """Return (rel, occupancy, handoff, enhance_off_identity) for STAMP_SPECS."""
    from _lab_ids import rel_id

    return tuple(
        (
            rel_id(spec.rel),
            spec.occupancy,
            (),
            spec.enhance_pin,
        )
        for spec in SERVICES
    )
