"""Drive-through 180s rave DJ-set takes.

Fictional act. Original dance arrangements. No living-artist names.
Live-set flow: unique shape per take, heavy drops, vocals rare.
"""

from __future__ import annotations

from .edm_examples import (
    EDM_DURATION_S,
    EdmExample,
    _desc,
    drive_tags,
    format_edm_score,
)


def _ex(
    slug: str,
    title: str,
    bpm: int,
    seed: int,
    prefix: str,
    take: str,
    lyrics: str,
    *tag_parts: str,
    treat: bool = False,
) -> EdmExample:
    return {
        "stem": f"music-edm-drive-through-{slug}-lab-example",
        "series": "drive-through",
        "title": title,
        "tags": drive_tags(*tag_parts, bpm=bpm, treat=treat),
        "bpm": bpm,
        "duration": EDM_DURATION_S,
        "seed": seed,
        "prefix": prefix,
        "description": _desc(take, treat=treat),
        "lyrics": lyrics,
        "ace_mode": "vocal" if treat else "instrumental",
    }


NIGHT_WINDOW_LYRICS = format_edm_score(
    ("intro", "kick in\nDrive-through\nblend open"),
    ("inst", "four on the floor\nrolling bass house\noffbeat hats"),
    ("inst", "heavy kick drop\nstacked bass house\nclap on two"),
    ("inst", "hats skip\nfilter ride\nbass rolls"),
    ("inst", "harder kick drop\nstacked rolling bass\nmainstage punch"),
    ("outro", "filter down\nkick holds\nblend next"),
)

OPEN_LANE_LYRICS = format_edm_score(
    ("inst", "full send drop\nfestival bass in\nstacked supersaw"),
    ("inst", "hats only\nbass cut\nair"),
    ("inst", "harder stacked drop\n808 punch\nsupersaw wreck"),
    ("outro", "blend out\nDrive-through"),
)

EXIT_SEVEN_LYRICS = format_edm_score(
    ("intro", "filter mix-in\nDrive-through\nexit seven"),
    ("inst", "analog bass\narp climb\nclap count"),
    ("inst", "stacked electro drop\ncomplextro wreck\nhard clap"),
    ("inst", "harder analog drop\narp wreck\nfull send"),
    ("outro", "filter blend\nkick into next"),
)

SKYLINE_PASS_LYRICS = format_edm_score(
    ("intro", "gated air\nDrive-through"),
    ("inst", "trance pads\nrolling bass\nno vocal"),
    ("inst", "snare climb\npickup fill\ngate tight"),
    ("inst", "heavy trance drop\nstacked supersaw\nkick drive"),
    ("inst", "pads thin\nbass out\nair"),
    ("inst", "harder trance drop\nmainstage saw wreck\nrolling bass wall"),
    ("outro", "gate close\nblend next"),
)

ON_RAMP_LYRICS = format_edm_score(
    ("intro", "reverse swell\nDrive-through"),
    ("inst", "kick split tease\nscreech wind"),
    ("inst", "heavy reverse-bass drop\nkick split wreck\nscreech stack"),
    ("inst", "hats iron\nbass cut"),
    ("inst", "roll louder\nscreech scream"),
    ("inst", "harder reverse drop\ndouble kick split\nstacked screech wreck"),
    ("inst", "screech tail\nhats iron"),
    ("outro", "kick out\nblend next"),
)

TUNNEL_BASS_LYRICS = format_edm_score(
    ("inst", "kick in\nacid line\noffbeat hats"),
    ("inst", "heavy techno drop\nindustrial bass wreck\nmetal hats"),
    ("inst", "acid closer\nkick meaner"),
    ("inst", "harder techno drop\nstacked industrial wreck"),
    ("inst", "full send techno drop\nmainstage rumble wreck"),
    ("outro", "kick out\nDrive-through\nblend next"),
)

WIDE_OPEN_LYRICS = format_edm_score(
    ("intro", "mainstage air\nDrive-through"),
    ("chorus", "hands up\nDrive-through"),
    ("inst", "tom run\nsaw swell"),
    ("inst", "heavy big-room drop\nstacked supersaw wreck\nmainstage kick"),
    ("inst", "harder festival drop\ndouble saw wreck\nfull send clap"),
    ("outro", "kick holds\nblend next"),
)

OVERPASS_LYRICS = format_edm_score(
    ("intro", "half-time knock\nDrive-through"),
    ("inst", "wobble tease\nspace"),
    ("inst", "heavy riddim drop\nwobble wreck\nsub crush"),
    ("inst", "hats metal\nbass cut"),
    ("inst", "four on the floor\nkick up"),
    ("inst", "stacked four-floor drop\nharder kick wreck"),
    ("inst", "hats ride\nbass growl"),
    ("inst", "full send bass drop\nmainstage wobble wreck"),
    ("outro", "span out\nblend next"),
)

SECOND_WAVE_LYRICS = format_edm_score(
    ("intro", "remix in\nDrive-through"),
    ("inst", "growl tease\nfake-out"),
    ("chorus", "one more\nDrive-through"),
    ("inst", "heavy remix drop\nstacked growl wreck"),
    ("inst", "harder double drop\nfull send bass wreck"),
    ("outro", "process out\nblend next"),
)

FREIGHT_PULSE_LYRICS = format_edm_score(
    ("inst", "amen in\nreese tease\nDrive-through"),
    ("inst", "heavy neuro drop\namen wreck\nreese stack"),
    ("inst", "break chops\nglitch"),
    ("inst", "harder neuro drop\ndouble amen wreck"),
    ("inst", "razor hats\nreese wind"),
    ("inst", "full send neuro drop\nstacked amen wreck"),
    ("outro", "amen stop\nblend next"),
)

KEEP_GOING_LYRICS = format_edm_score(
    ("inst", "hat roll\nriser\nDrive-through"),
    ("inst", "heavy hardcore drop\nstacked kick wreck"),
    ("inst", "hats only\nair"),
    ("inst", "harder hard-dance drop\nfull send 170 wreck"),
    ("inst", "riser scream\nhats denser"),
    ("inst", "mainstage hardcore drop\nstacked kick wreck"),
    ("inst", "kick ride\nhats still"),
    ("outro", "still going\nblend next"),
)

HORIZON_KICK_LYRICS = format_edm_score(
    ("inst", "heavy rawstyle drop\nkick split wreck\nreverse bass"),
    ("inst", "screech wind\nhats razor"),
    ("inst", "harder raw drop\nstacked reverse wreck\ndouble split"),
    ("inst", "screech tail\nkick rest"),
    ("outro", "kick rest\nDrive-through\nblend next"),
)

CLEAN_WRECKAGE_LYRICS = format_edm_score(
    ("intro", "bits gather\nDrive-through"),
    ("inst", "bass coils\nhats complex"),
    ("inst", "heavy hard-dance drop\nstacked kick wreck\nlayered lead"),
    ("inst", "bits denser\ncoil tighter"),
    ("inst", "harder wreck drop\nlead and kick stack"),
    ("inst", "full send wreck drop\nmainstage crash"),
    ("outro", "dust rest\nblend next"),
)

HEART_LANE_LYRICS = format_edm_score(
    ("intro", "rolling kick\nDrive-through"),
    ("inst", "melodic techno\nfour on the floor\nchord bed"),
    ("inst", "heavy techno drop\nstacked rolling bass\nhard kick"),
    ("inst", "groove returns\npads thin"),
    ("inst", "harder encore drop\nfull send kick wreck"),
    ("outro", "kick rest\nblend next"),
)

DAWN_RECEIPT_LYRICS = format_edm_score(
    ("intro", "sunrise mix-in\nDrive-through"),
    ("inst", "heavy peak-time drop\nstacked house kick\nwarm bass wreck"),
    ("inst", "harder closer drop\nmainstage gold wreck"),
    ("outro", "blend out\nsky paid"),
)

EDM_DRIVE_THROUGH: tuple[EdmExample, ...] = (
    _ex(
        "night-window",
        "night window",
        145,
        193,
        "ez_edm_drive_night",
        "night-window peak bass house",
        NIGHT_WINDOW_LYRICS,
        "bass house",
        "four on the floor",
        "rolling bass",
        "offbeat hats",
        "rave",
        "heavy kick",
    ),
    _ex(
        "open-lane",
        "open lane",
        152,
        191,
        "ez_edm_drive_openlane",
        "open-lane festival bass",
        OPEN_LANE_LYRICS,
        "festival bass",
        "four on the floor",
        "supersaw",
        "stacked 808",
        "rave",
        "heavy drop",
    ),
    _ex(
        "exit-seven",
        "exit seven",
        142,
        233,
        "ez_edm_drive_exit",
        "exit-seven electro house",
        EXIT_SEVEN_LYRICS,
        "electro house",
        "four on the floor",
        "analog bass",
        "complex arp",
        "rave",
        "heavy drop",
    ),
    _ex(
        "skyline-pass",
        "skyline pass",
        145,
        199,
        "ez_edm_drive_skyline",
        "skyline-pass uplifting trance",
        SKYLINE_PASS_LYRICS,
        "uplifting trance",
        "four on the floor",
        "gated pads",
        "rolling bass",
        "rave",
        "supersaw",
    ),
    _ex(
        "on-ramp",
        "on-ramp",
        155,
        197,
        "ez_edm_drive_onramp",
        "on-ramp hardstyle",
        ON_RAMP_LYRICS,
        "hardstyle",
        "hard dance",
        "reverse bass",
        "kick split",
        "rave",
        "heavy drop",
    ),
    _ex(
        "tunnel-bass",
        "tunnel bass",
        150,
        257,
        "ez_edm_drive_tunnel",
        "tunnel-bass hard techno",
        TUNNEL_BASS_LYRICS,
        "hard techno",
        "four on the floor",
        "industrial bass",
        "acid line",
        "rave",
        "heavy kick",
    ),
    _ex(
        "wide-open",
        "wide open",
        150,
        239,
        "ez_edm_drive_wide",
        "wide-open big room DJ shout",
        WIDE_OPEN_LYRICS,
        "big room",
        "festival",
        "four on the floor",
        "supersaw",
        "rave",
        "heavy kick",
        treat=True,
    ),
    _ex(
        "overpass",
        "overpass",
        150,
        227,
        "ez_edm_drive_overpass",
        "overpass rave bass switch",
        OVERPASS_LYRICS,
        "riddim",
        "rave bass",
        "four on the floor",
        "wobble bass",
        "hard dance",
        "heavy sub",
    ),
    _ex(
        "second-wave",
        "second wave",
        150,
        241,
        "ez_edm_drive_second",
        "second-wave festival remix",
        SECOND_WAVE_LYRICS,
        "festival remix",
        "rave",
        "bass growl",
        "hard dance",
        "heavy drop",
        treat=True,
    ),
    _ex(
        "freight-pulse",
        "freight pulse",
        176,
        211,
        "ez_edm_drive_freight",
        "freight-pulse drum and bass",
        FREIGHT_PULSE_LYRICS,
        "drum and bass",
        "neurofunk",
        "amen break",
        "reese bass",
        "rave",
        "complex edits",
    ),
    _ex(
        "keep-going",
        "keep going",
        170,
        251,
        "ez_edm_drive_keep",
        "keep-going uk hardcore",
        KEEP_GOING_LYRICS,
        "uk hardcore",
        "hard dance",
        "four on the floor",
        "festival",
        "rave",
        "heavy kick",
    ),
    _ex(
        "horizon-kick",
        "horizon kick",
        165,
        263,
        "ez_edm_drive_horizon",
        "horizon-kick rawstyle",
        HORIZON_KICK_LYRICS,
        "rawstyle",
        "hard dance",
        "kick split",
        "reverse bass",
        "rave",
        "heavy drop",
    ),
    _ex(
        "clean-wreckage",
        "clean wreckage",
        150,
        269,
        "ez_edm_drive_wreck",
        "clean-wreckage hard dance",
        CLEAN_WRECKAGE_LYRICS,
        "hard dance",
        "four on the floor",
        "layered kick",
        "rave",
        "heavy sub",
    ),
    _ex(
        "heart-lane",
        "heart lane",
        145,
        223,
        "ez_edm_drive_heart",
        "heart-lane melodic techno",
        HEART_LANE_LYRICS,
        "melodic techno",
        "four on the floor",
        "rolling bass",
        "rave",
        "hard kick",
    ),
    _ex(
        "dawn-receipt",
        "dawn receipt",
        140,
        229,
        "ez_edm_drive_dawn",
        "dawn-receipt peak-time closer",
        DAWN_RECEIPT_LYRICS,
        "peak time house",
        "four on the floor",
        "progressive",
        "rave",
        "heavy kick",
    ),
)
