"""Drive-through 180s rave DJ-set takes (Secret Homage album).

Fictional act. Original dance arrangements. No living-artist names.
American festival EDM: drop early, dirty pyro on every drop, all instrumental.
Early dirty-bass hour: half-time dubstep, brostep, riddim, tearout, drumstep,
hybrid trap. Harder chest-sub bass, fast section changes.
"""

from __future__ import annotations

from .edm_examples import EdmExample, _ex, format_edm_score

SECRET_HOMAGE_PHASE = 4


HUSH_LANE_LYRICS = format_edm_score(
    ("intro", "hush in\nDrive-through"),
    ("inst", "heavy half-time drop\nwobble wreck\nfireworks crash"),
    ("inst", "hats skip\nbass cut"),
    ("inst", "harder dirty drop\nlow rumble wreck\nmainstage pyro"),
    ("inst", "full send drop\nchest sub wreck\nfestival pyro"),
    ("outro", "hush out\nblend next"),
)

CIPHER_LOCK_LYRICS = format_edm_score(
    ("inst", "heavy growl drop\nbrostep wreck\nDrive-through\nfireworks crash"),
    ("inst", "hats metal\nbass cut"),
    ("inst", "harder dirty drop\nsub crush\nchest pyro"),
    ("inst", "hats skip\ngrowl cut"),
    ("inst", "full send drop\nstacked growl wreck\nmainstage pyro"),
    ("outro", "lock out\nblend next"),
)

GHOST_DOCK_LYRICS = format_edm_score(
    ("intro", "dock fog\nDrive-through"),
    ("inst", "heavy riddim drop\nwobble wreck\nfireworks crash"),
    ("inst", "harder dirty drop\nchest growl wreck\nmainstage pyro"),
    ("inst", "full send drop\nlow rumble wreck\nfestival pyro"),
    ("outro", "dock out\nblend next"),
)

SEALED_RAMP_LYRICS = format_edm_score(
    ("inst", "heavy tearout drop\ngrowl wreck\nDrive-through\nfireworks crash"),
    ("inst", "hats metal\nbass cut"),
    ("inst", "harder dirty drop\nsub crush\nchest pyro"),
    ("inst", "hats skip\ngrowl cut"),
    ("inst", "full send drop\nstacked tearout wreck\nmainstage pyro"),
    ("inst", "harder stacked drop\nlow rumble wreck\nfestival pyro"),
    ("outro", "seal out\nblend next"),
)

FOG_VAULT_LYRICS = format_edm_score(
    ("intro", "fog in\nDrive-through"),
    ("inst", "heavy dirty drop\nelectro 808 wreck\nfireworks crash"),
    ("inst", "hats analog\nbass cut"),
    ("inst", "harder dirty drop\nchest analog wreck\nmainstage pyro"),
    ("inst", "hats skip\n808 cut"),
    ("inst", "full send drop\ndirty electro wreck\nfestival pyro"),
    ("outro", "vault out\nblend next"),
)

DUMMY_LIGHT_LYRICS = format_edm_score(
    ("inst", "heavy dirty drop\nstacked 808 wreck\nDrive-through\nfireworks crash"),
    ("inst", "hats skip\nbass cut"),
    ("inst", "harder stacked drop\nchest sub wall\nmainstage pyro"),
    ("inst", "full send drop\nlow 808 wreck\nfestival pyro"),
    ("outro", "light out\nblend next"),
)

QUIET_WRECK_LYRICS = format_edm_score(
    ("inst", "heavy half-time drop\ndirty bass wreck\nDrive-through\nfireworks crash"),
    ("inst", "hats skip\nbass cut"),
    ("inst", "harder dirty drop\nlow rumble wreck\nchest pyro"),
    ("inst", "hats roll\nsub cut"),
    ("inst", "full send drop\nchest sub wreck\nmainstage pyro"),
    ("inst", "hats denser\nbass cut"),
    ("inst", "harder stacked drop\nquiet wreck slam\nfestival pyro"),
    ("outro", "quiet out\nblend next"),
)

OFF_LEDGER_LYRICS = format_edm_score(
    ("intro", "ledger in\nDrive-through"),
    ("inst", "heavy amen drop\nreese wreck\nfireworks crash"),
    ("inst", "amen chops\nhats cut"),
    ("inst", "harder dirty drop\nreese stack\nchest pyro"),
    ("inst", "hats razor\nbass wind"),
    ("inst", "full send drop\nstacked amen wreck\nmainstage pyro"),
    ("inst", "harder dirty drop\nchest 808 wreck\nfestival pyro"),
    ("outro", "ledger out\nblend next"),
)

BACK_ALLEY_LYRICS = format_edm_score(
    ("inst", "heavy neuro drop\nreese 808 wreck\nDrive-through\nfireworks crash"),
    ("inst", "hats razor\nbass cut"),
    ("inst", "harder stacked drop\nchest reese wreck\nmainstage pyro"),
    ("inst", "hats skip\nsub cut"),
    ("inst", "full send drop\nneuro 808 wreck\nchest pyro"),
    ("inst", "harder dirty drop\nstacked reese wreck\nfestival pyro"),
    ("outro", "alley out\nblend next"),
)

CELLAR_KICK_LYRICS = format_edm_score(
    ("intro", "cellar in\nDrive-through"),
    ("inst", "heavy dirty drop\nwobble wreck\nfireworks crash"),
    ("inst", "hats skip\nbass cut"),
    ("inst", "harder dirty drop\nlow rumble wreck\nmainstage pyro"),
    ("inst", "full send drop\nchest sub wreck\nfestival pyro"),
    ("outro", "cellar out\nblend next"),
)

HIDDEN_BOOTH_LYRICS = format_edm_score(
    ("inst", "heavy dirty drop\ntrap 808 wreck\nDrive-through\nfireworks crash"),
    ("inst", "hats roll\nbass cut"),
    ("inst", "harder dirty drop\nstacked trap bass\nmainstage pyro"),
    ("inst", "hats skip\nchest cut"),
    ("inst", "full send drop\nchest 808 wall\nfestival pyro"),
    ("outro", "booth out\nblend next"),
)

CODED_SUB_LYRICS = format_edm_score(
    ("intro", "code in\nDrive-through"),
    ("inst", "heavy dirty drop\ndual-action pedal bass\nchest punch\nfireworks crash"),
    ("inst", "pedal swell\nhats cut"),
    ("inst", "harder dirty drop\nrolling 808 wall\nmainstage pyro"),
    ("inst", "hats skip\nbass cut"),
    ("inst", "full send drop\nchest sub wreck\nfestival pyro"),
    ("outro", "code out\nblend next"),
)

SHADOW_COIL_LYRICS = format_edm_score(
    ("inst", "heavy neuro drop\nreese coil wreck\nDrive-through\nfireworks crash"),
    ("inst", "hats razor\nbass wind"),
    ("inst", "harder stacked drop\nchest reese wreck\nmainstage pyro"),
    ("inst", "hats skip\nsub cut"),
    ("inst", "full send drop\ncoiled 808 wreck\nchest pyro"),
    ("inst", "harder dirty drop\nstacked reese wreck\nfestival pyro"),
    ("outro", "coil out\nblend next"),
)

MUTE_PYRO_LYRICS = format_edm_score(
    ("intro", "mute in\nDrive-through"),
    ("inst", "heavy dirty drop\nanalog 808 wreck\nfireworks crash"),
    ("inst", "harder dirty drop\nchest analog wreck\nmainstage pyro"),
    ("inst", "full send drop\ndirty electro wreck\nfestival pyro"),
    ("outro", "mute out\nblend next"),
)

UNLISTED_ROW_LYRICS = format_edm_score(
    ("inst", "heavy amen drop\nreese wreck\nDrive-through\nfireworks crash"),
    ("inst", "amen chops\nhats cut"),
    ("inst", "harder stacked drop\nchest reese wreck\nchest pyro"),
    ("inst", "hats razor\nbass wind"),
    ("inst", "full send drop\nstacked amen wreck\nmainstage pyro"),
    ("inst", "hats skip\n808 cut"),
    ("inst", "harder dirty drop\nchest 808 wreck\nfestival pyro"),
    ("outro", "row out\nblend next"),
)

NIGHT_CIPHER_LYRICS = format_edm_score(
    ("intro", "cipher in\nDrive-through"),
    ("inst", "heavy dirty drop\nwave bass wreck\nfireworks crash"),
    ("inst", "hats skip\nbass cut"),
    ("inst", "harder dirty drop\nchest 808 wall\nmainstage pyro"),
    ("inst", "full send drop\nlow swell wreck\nfestival pyro"),
    ("outro", "cipher out\nblend next"),
)

BLANK_STENCIL_LYRICS = format_edm_score(
    ("inst", "heavy dirty drop\nstencil 808 wreck\nDrive-through\nfireworks crash"),
    ("inst", "hats stamp\nbass cut"),
    ("inst", "harder stacked drop\ntrap wall wreck\nmainstage pyro"),
    ("inst", "full send drop\nlow 808 wreck\nfestival pyro"),
    ("outro", "stencil out\nblend next"),
)

BLIND_STAMP_LYRICS = format_edm_score(
    ("intro", "stamp in\nDrive-through"),
    ("inst", "heavy riddim drop\nwobble wreck\nfireworks crash"),
    ("inst", "hats metal\nbass cut"),
    ("inst", "harder dirty drop\nchest growl wreck\nmainstage pyro"),
    ("inst", "hats skip\nwobble cut"),
    ("inst", "full send drop\nsub crush wreck\nfestival pyro"),
    ("outro", "stamp out\nblend next"),
)

COLD_CACHE_LYRICS = format_edm_score(
    ("inst", "heavy dirty drop\nhybrid 808 wreck\nDrive-through\nfireworks crash"),
    ("inst", "hats skip\nbass rolls"),
    ("inst", "harder dirty drop\ntrap bass wall\nmainstage pyro"),
    ("inst", "hats roll\n808 cut"),
    ("inst", "full send drop\nchest sub wreck\nfestival pyro"),
    ("outro", "cache out\nblend next"),
)

SECRET_HOMAGE_LYRICS = format_edm_score(
    ("intro", "secret homage\nDrive-through"),
    ("inst", "heavy half-time drop\nwobble 808 wreck\nfireworks crash"),
    ("inst", "hats skip\nbass cut"),
    ("inst", "harder stacked drop\nchest sub wall\nmainstage pyro"),
    ("inst", "full send drop\nlow rumble wreck\nfestival pyro"),
    ("outro", "homage out\nsky paid"),
)


EDM_DRIVE_THROUGH_SECRET_HOMAGE: tuple[EdmExample, ...] = (
    _ex(
        "hush-lane",
        "hush lane",
        140,
        593,
        SECRET_HOMAGE_PHASE,
        "hush-lane dirty dubstep",
        HUSH_LANE_LYRICS,
        "dirty dubstep",
        "half-time",
        "wobble bass",
        "heavy sub",
        "rave",
        "festival pyro",
        layout="column",
    ),
    _ex(
        "cipher-lock",
        "cipher lock",
        140,
        599,
        SECRET_HOMAGE_PHASE,
        "cipher-lock dirty brostep",
        CIPHER_LOCK_LYRICS,
        "brostep",
        "dirty dubstep",
        "bass growl",
        "heavy sub",
        "rave",
        "festival pyro",
        layout="wide-stage",
    ),
    _ex(
        "ghost-dock",
        "ghost dock",
        140,
        601,
        SECRET_HOMAGE_PHASE,
        "ghost-dock riddim",
        GHOST_DOCK_LYRICS,
        "riddim",
        "wobble bass",
        "heavy sub",
        "chest 808",
        "rave",
        "festival pyro",
        layout="stacked-tower",
    ),
    _ex(
        "sealed-ramp",
        "sealed ramp",
        145,
        607,
        SECRET_HOMAGE_PHASE,
        "sealed-ramp tearout",
        SEALED_RAMP_LYRICS,
        "tearout",
        "bass growl",
        "heavy sub",
        "dirty 808",
        "rave",
        "festival pyro",
        layout="prompt-left",
    ),
    _ex(
        "fog-vault",
        "fog vault",
        142,
        613,
        SECRET_HOMAGE_PHASE,
        "fog-vault dirty electro",
        FOG_VAULT_LYRICS,
        "electro house",
        "dirty 808",
        "chest sub",
        "analog bass",
        "rave",
        "festival pyro",
        layout="output-rail",
    ),
    _ex(
        "dummy-light",
        "dummy light",
        145,
        617,
        SECRET_HOMAGE_PHASE,
        "dummy-light festival bass",
        DUMMY_LIGHT_LYRICS,
        "festival bass",
        "four on the floor",
        "stacked 808",
        "chest sub",
        "rave",
        "festival pyro",
        layout="column",
    ),
    _ex(
        "quiet-wreck",
        "quiet wreck",
        140,
        619,
        SECRET_HOMAGE_PHASE,
        "quiet-wreck dirty bass",
        QUIET_WRECK_LYRICS,
        "dirty bass",
        "half-time",
        "low rumble",
        "chest sub",
        "rave",
        "festival pyro",
        layout="wide-stage",
    ),
    _ex(
        "off-ledger",
        "off ledger",
        174,
        631,
        SECRET_HOMAGE_PHASE,
        "off-ledger drumstep",
        OFF_LEDGER_LYRICS,
        "drumstep",
        "festival",
        "amen break",
        "reese bass",
        "chest sub",
        "rave",
        "dirty pyro",
        layout="stacked-tower",
    ),
    _ex(
        "back-alley",
        "back alley",
        172,
        641,
        SECRET_HOMAGE_PHASE,
        "back-alley neuro bass",
        BACK_ALLEY_LYRICS,
        "neuro bass",
        "drumstep",
        "reese bass",
        "chest sub",
        "rave",
        "festival pyro",
        layout="prompt-left",
    ),
    _ex(
        "cellar-kick",
        "cellar kick",
        148,
        643,
        SECRET_HOMAGE_PHASE,
        "cellar-kick dirty dubstep",
        CELLAR_KICK_LYRICS,
        "dirty dubstep",
        "wobble bass",
        "heavy sub",
        "chest 808",
        "rave",
        "festival pyro",
        layout="output-rail",
    ),
    _ex(
        "hidden-booth",
        "hidden booth",
        140,
        647,
        SECRET_HOMAGE_PHASE,
        "hidden-booth hybrid trap",
        HIDDEN_BOOTH_LYRICS,
        "hybrid trap",
        "festival trap",
        "trap 808",
        "dirty bass",
        "rave",
        "festival pyro",
        layout="column",
    ),
    _ex(
        "coded-sub",
        "coded sub",
        140,
        653,
        SECRET_HOMAGE_PHASE,
        "coded-sub chest bass",
        CODED_SUB_LYRICS,
        "chest bass",
        "dual-action pedal bass",
        "heavy sub",
        "dirty 808",
        "rave",
        "festival pyro",
        layout="wide-stage",
    ),
    _ex(
        "shadow-coil",
        "shadow coil",
        150,
        659,
        SECRET_HOMAGE_PHASE,
        "shadow-coil neuro bass",
        SHADOW_COIL_LYRICS,
        "neuro bass",
        "reese bass",
        "heavy sub",
        "chest 808",
        "rave",
        "festival pyro",
        layout="stacked-tower",
    ),
    _ex(
        "mute-pyro",
        "mute pyro",
        150,
        661,
        SECRET_HOMAGE_PHASE,
        "mute-pyro dirty electro",
        MUTE_PYRO_LYRICS,
        "dirty electro",
        "analog bass",
        "dirty 808",
        "chest sub",
        "rave",
        "festival pyro",
        layout="prompt-left",
    ),
    _ex(
        "unlisted-row",
        "unlisted row",
        176,
        673,
        SECRET_HOMAGE_PHASE,
        "unlisted-row drumstep",
        UNLISTED_ROW_LYRICS,
        "drumstep",
        "festival",
        "amen break",
        "reese bass",
        "chest sub",
        "rave",
        "dirty pyro",
        layout="output-rail",
    ),
    _ex(
        "night-cipher",
        "night cipher",
        140,
        677,
        SECRET_HOMAGE_PHASE,
        "night-cipher wave bass",
        NIGHT_CIPHER_LYRICS,
        "wave bass",
        "chest 808",
        "low rumble",
        "dirty bass",
        "rave",
        "festival pyro",
        layout="column",
    ),
    _ex(
        "blank-stencil",
        "blank stencil",
        140,
        683,
        SECRET_HOMAGE_PHASE,
        "blank-stencil festival trap",
        BLANK_STENCIL_LYRICS,
        "festival trap",
        "trap 808",
        "dirty bass",
        "chest sub",
        "rave",
        "festival pyro",
        layout="wide-stage",
    ),
    _ex(
        "blind-stamp",
        "blind stamp",
        150,
        691,
        SECRET_HOMAGE_PHASE,
        "blind-stamp riddim",
        BLIND_STAMP_LYRICS,
        "riddim",
        "wobble bass",
        "heavy sub",
        "chest 808",
        "rave",
        "festival pyro",
        layout="stacked-tower",
    ),
    _ex(
        "cold-cache",
        "cold cache",
        142,
        701,
        SECRET_HOMAGE_PHASE,
        "cold-cache hybrid bass",
        COLD_CACHE_LYRICS,
        "hybrid bass",
        "dirty 808",
        "chest sub",
        "trap bass",
        "rave",
        "festival pyro",
        layout="prompt-left",
    ),
    _ex(
        "secret-homage",
        "secret homage",
        140,
        709,
        SECRET_HOMAGE_PHASE,
        "secret-homage dirty dubstep closer",
        SECRET_HOMAGE_LYRICS,
        "dirty dubstep",
        "half-time",
        "stacked 808",
        "chest sub",
        "rave",
        "festival pyro",
        layout="output-rail",
    ),
)
