"""Drive-through 180s bass-set takes (hour 1).

Fictional act. Original dance arrangements. No living-artist names.
Warped hybrid-trap EDM: drop first, hard warpy drops, trap drums, no quiet
dips, vocals rare.
"""

from __future__ import annotations

from .edm_examples import EdmExample, _ex, format_edm_score

# Track scores and catalog rows.
NIGHT_WINDOW_LYRICS = format_edm_score(
    ("inst", "heavy warped drop\nhybrid trap 808 wreck\nformant grind"),
    ("inst", "trap hats roll\n808 slide"),
    ("inst", "harder growl drop\nchest sub warp\nstacked reese"),
    ("inst", "snare roll\nchest 808 punch"),
    ("inst", "full send drop\nwarped 808 wall\nlow rumble wreck"),
    ("outro", "kick holds\ntrap hats roll\nwarp bass ride"),
)

OPEN_LANE_LYRICS = format_edm_score(
    ("inst", "full send drop\nriddim wobble wreck\nsub crush"),
    ("inst", "harder stacked drop\ngrowl 808 punch\nwarped wall"),
    ("inst", "trap hats denser\nwobble sustain"),
    ("inst", "heavy warped drop\nlow sub wobble\nchest 808 wreck"),
    ("outro", "kick holds\nhats denser\nwobble ride"),
)

EXIT_SEVEN_LYRICS = format_edm_score(
    ("inst", "heavy tearout drop\ngrowl wreck\nformant scrape"),
    ("inst", "metal hats roll\n808 grind hold"),
    ("inst", "harder warped drop\nsub crush 808\nchest growl"),
    ("inst", "snare roll\ntearout 808 sustain"),
    ("inst", "full send drop\nstacked growl wreck\nlow rumble"),
    ("inst", "trap hats denser\nmid growl hold"),
    ("inst", "harder growl drop\nchest 808 warp\ntearout wreck"),
    ("outro", "kick holds\ntrap hats roll\ngrowl ride"),
)

SKYLINE_PASS_LYRICS = format_edm_score(
    ("inst", "heavy brostep drop\nmid growl wreck\nwarped 808"),
    ("inst", "trap hats roll\ngrowl sustain"),
    ("inst", "harder reese drop\nstacked 808 wall\nformant bend"),
    ("inst", "full send drop\nchest sub growl\nbrostep wreck"),
    ("inst", "snare roll\nreese hold"),
    ("inst", "harder warped drop\nlow rumble wreck\n808 punch"),
    ("outro", "kick holds\nhats denser\nreese ride"),
)

ON_RAMP_LYRICS = format_edm_score(
    ("inst", "heavy wave drop\nwarped 808 wreck\nfold bass"),
    ("inst", "trap hats roll\nwave 808 sustain"),
    ("inst", "harder formant drop\ndouble 808 split\nchest warp"),
    ("inst", "snare roll\n808 slide"),
    ("inst", "full send drop\nstacked wave wreck\nwarped sub"),
    ("outro", "kick holds\ntrap hats roll\nwave ride"),
)

TUNNEL_BASS_LYRICS = format_edm_score(
    ("inst", "heavy dirty drop\nindustrial 808 warp\nformant wreck"),
    ("inst", "harder growl drop\ndual-action pedal bass\nchest punch"),
    ("inst", "trap hats roll\npedal 808 hold"),
    ("inst", "full send drop\nchest sub wreck\nwarped rumble"),
    ("outro", "kick holds\nhats denser\npedal ride"),
)

WIDE_OPEN_LYRICS = format_edm_score(
    ("inst", "heavy color drop\nwarped 808 wreck\nformant stack"),
    ("chorus", "hey"),
    ("inst", "harder growl drop\nchest sub warp\ncolor bass wreck"),
    ("inst", "trap hats roll\n808 slide"),
    ("inst", "full send drop\nlow 808 wall\nwarped color"),
    ("outro", "kick holds\ntrap hats roll\ncolor ride"),
)

OVERPASS_LYRICS = format_edm_score(
    ("inst", "heavy wobble drop\ndirty dubstep wreck\nsub crush"),
    ("inst", "metal hats roll\nwobble sustain"),
    ("inst", "harder growl drop\nstacked 808 warp\nchest rumble"),
    ("inst", "trap hats denser\n808 punch hold"),
    ("inst", "full send drop\nwarped wobble wreck\nlow sub"),
    ("inst", "snare roll\ngrowl hold"),
    ("inst", "harder warped drop\nchest 808 wreck\ndubstep grind"),
    ("outro", "kick holds\nhats denser\nwobble ride"),
)

SECOND_WAVE_LYRICS = format_edm_score(
    ("inst", "heavy warped drop\nhybrid trap growl wreck\n808 stack"),
    ("inst", "trap hats roll\n808 slide"),
    ("chorus", "go"),
    ("inst", "harder double drop\nfull send bass warp\nformant wreck"),
    ("inst", "full send drop\nchest 808 wreck\nwarped trap"),
    ("outro", "kick holds\ntrap hats roll\ngrowl ride"),
)

FREIGHT_PULSE_LYRICS = format_edm_score(
    ("inst", "heavy amen drop\nreese stack wreck\nwarped 808"),
    ("inst", "amen chops\ntrap hats 808 freight"),
    ("inst", "harder growl drop\ndouble amen wreck\nformant grind"),
    ("inst", "hats denser\nreese hold"),
    ("inst", "full send drop\nstacked amen wreck\nwarped chest sub"),
    ("inst", "snare roll\n808 punch"),
    ("inst", "harder warped drop\nchest 808 wreck\nreese wall"),
    ("outro", "kick holds\namen keep\nreese ride"),
)

KEEP_GOING_LYRICS = format_edm_score(
    ("inst", "heavy neuro drop\nreese 808 wreck\nwarped coil"),
    ("inst", "trap hats denser\nreese sustain"),
    ("inst", "harder formant drop\nfull send 170 wreck\nchest sub"),
    ("inst", "snare roll\n808 slide"),
    ("inst", "full send drop\nchest sub wreck\nneuro warp"),
    ("outro", "kick holds\nhats denser\nreese ride"),
)

HORIZON_KICK_LYRICS = format_edm_score(
    ("inst", "heavy tearout drop\nkick split wreck\nwarped growl"),
    ("inst", "trap hats roll\ngrowl sustain"),
    ("inst", "harder stacked drop\nformant reverse wreck\nchest 808"),
    ("inst", "808 triplets\nhats denser"),
    ("inst", "full send drop\nchest sub wreck\ntearout warp"),
    ("inst", "harder growl drop\nlow rumble wreck\n808 punch"),
    ("outro", "kick holds\ntrap hats roll\ngrowl ride"),
)

CLEAN_WRECKAGE_LYRICS = format_edm_score(
    ("inst", "heavy brostep drop\nstacked 808 warp\ngrowl wreck"),
    ("inst", "harder reese drop\nkick stack wreck\nchest formant"),
    ("inst", "trap hats roll\n808 punch hold"),
    ("inst", "full send drop\nmid growl crash\nwarped wall"),
    ("outro", "kick holds\nhats denser\nbrostep ride"),
)

HEART_LANE_LYRICS = format_edm_score(
    ("inst", "heavy wave drop\nchest 808 warp\nfold wreck"),
    ("inst", "trap hats roll\nwave 808 sustain lane"),
    ("inst", "harder formant drop\nfull send kick wreck\n808 slide"),
    ("inst", "snare roll\nchest 808"),
    ("inst", "full send drop\nstacked wave bass\nwarped rumble"),
    ("outro", "kick holds\ntrap hats roll\nwave ride"),
)

DAWN_RECEIPT_LYRICS = format_edm_score(
    ("inst", "heavy chest drop\nwarped 808 wreck\nsub grind"),
    ("inst", "trap hats denser\n808 hold"),
    ("inst", "harder growl drop\nchest wall wreck\nformant punch"),
    ("inst", "full send drop\nlow sub wreck\nwarped 808"),
    ("outro", "kick holds\nhats denser\nchest ride"),
)

EDM_DRIVE_THROUGH: tuple[EdmExample, ...] = (
    _ex(
        "night-window",
        "night window",
        145,
        193,
        0,
        "night-window hybrid trap warp",
        NIGHT_WINDOW_LYRICS,
        "hybrid trap",
        "warped bass",
        "trap hats",
        "formant bass",
        "chest sub",
        "rave",
    ),
    _ex(
        "open-lane",
        "open lane",
        152,
        191,
        0,
        "open-lane riddim warp",
        OPEN_LANE_LYRICS,
        "riddim",
        "warped bass",
        "trap hats",
        "wobble bass",
        "chest sub",
        "rave",
    ),
    _ex(
        "exit-seven",
        "exit seven",
        142,
        233,
        0,
        "exit-seven tearout warp",
        EXIT_SEVEN_LYRICS,
        "tearout",
        "warped bass",
        "trap hats",
        "bass growl",
        "chest sub",
        "rave",
    ),
    _ex(
        "skyline-pass",
        "skyline pass",
        145,
        199,
        0,
        "skyline-pass brostep warp",
        SKYLINE_PASS_LYRICS,
        "brostep",
        "warped bass",
        "trap hats",
        "reese bass",
        "chest sub",
        "rave",
    ),
    _ex(
        "on-ramp",
        "on-ramp",
        155,
        197,
        0,
        "on-ramp wave bass warp",
        ON_RAMP_LYRICS,
        "wave bass",
        "warped bass",
        "trap hats",
        "808 punch",
        "chest sub",
        "rave",
    ),
    _ex(
        "tunnel-bass",
        "tunnel bass",
        150,
        257,
        0,
        "tunnel-bass dirty warp",
        TUNNEL_BASS_LYRICS,
        "dirty bass",
        "warped bass",
        "trap hats",
        "dual-action pedal bass",
        "chest sub",
        "rave",
    ),
    _ex(
        "wide-open",
        "wide open",
        150,
        239,
        0,
        "wide-open color bass DJ shout",
        WIDE_OPEN_LYRICS,
        "color bass",
        "warped bass",
        "trap hats",
        "stacked 808",
        "chest sub",
        "rave",
        treat=True,
    ),
    _ex(
        "overpass",
        "overpass",
        150,
        227,
        0,
        "overpass dirty dubstep warp",
        OVERPASS_LYRICS,
        "dirty dubstep",
        "warped bass",
        "trap hats",
        "wobble bass",
        "heavy sub",
        "rave",
    ),
    _ex(
        "second-wave",
        "second wave",
        150,
        241,
        0,
        "second-wave hybrid trap chop",
        SECOND_WAVE_LYRICS,
        "hybrid trap",
        "warped bass",
        "trap hats",
        "bass growl",
        "chest sub",
        "rave",
        treat=True,
    ),
    _ex(
        "freight-pulse",
        "freight pulse",
        176,
        211,
        0,
        "freight-pulse drumstep warp",
        FREIGHT_PULSE_LYRICS,
        "drumstep",
        "warped bass",
        "trap hats",
        "amen break",
        "reese bass",
        "chest sub",
        "rave",
    ),
    _ex(
        "keep-going",
        "keep going",
        170,
        251,
        0,
        "keep-going neuro warp",
        KEEP_GOING_LYRICS,
        "neuro bass",
        "warped bass",
        "trap hats",
        "reese bass",
        "heavy sub",
        "rave",
    ),
    _ex(
        "horizon-kick",
        "horizon kick",
        165,
        263,
        0,
        "horizon-kick tearout warp",
        HORIZON_KICK_LYRICS,
        "tearout",
        "warped bass",
        "trap hats",
        "bass growl",
        "chest sub",
        "rave",
    ),
    _ex(
        "clean-wreckage",
        "clean wreckage",
        150,
        269,
        0,
        "clean-wreckage brostep warp",
        CLEAN_WRECKAGE_LYRICS,
        "brostep",
        "warped bass",
        "trap hats",
        "chest 808",
        "heavy sub",
        "rave",
    ),
    _ex(
        "heart-lane",
        "heart lane",
        145,
        223,
        0,
        "heart-lane wave bass warp",
        HEART_LANE_LYRICS,
        "wave bass",
        "warped bass",
        "trap hats",
        "chest 808",
        "chest sub",
        "rave",
    ),
    _ex(
        "dawn-receipt",
        "dawn receipt",
        140,
        229,
        0,
        "dawn-receipt chest bass warp",
        DAWN_RECEIPT_LYRICS,
        "chest bass",
        "warped bass",
        "trap hats",
        "chest sub",
        "rave",
    ),
)
