"""Drive-through 180s rave DJ-set takes (hour 4, afterparty).

Fictional act. Original dance arrangements. No living-artist names.
American festival EDM: drop early, dirty pyro on every drop, all instrumental.
Harder chest-sub bass, dual-action pedal bass on some takes, fast section changes.
"""

from __future__ import annotations

from .edm_examples import EdmExample, _ex, format_edm_score

AFTERPARTY_PHASE = 3


BRAKE_FADE_LYRICS = format_edm_score(
    ("inst", "heavy dirty drop\nchest 808 wreck\nDrive-through\nfireworks crash"),
    ("inst", "hats skip\nbass cut"),
    ("inst", "harder dirty drop\nstacked 808 wall\nmainstage pyro"),
    ("inst", "hats roll\nsub cut"),
    ("inst", "full send drop\nlow rumble wreck\nfestival pyro"),
    ("outro", "brake out\nblend next"),
)

DIESEL_HUM_LYRICS = format_edm_score(
    ("intro", "diesel in\nDrive-through"),
    ("inst", "heavy dirty drop\ndual-action pedal bass\nchest punch\nfireworks crash"),
    ("inst", "pedal swell\nhats cut"),
    ("inst", "harder dirty drop\nrolling 808 wall\nmainstage pyro"),
    ("inst", "full send drop\nchest sub wreck\nfestival pyro"),
    ("outro", "hum out\nblend next"),
)

AXLE_GRIND_LYRICS = format_edm_score(
    ("inst", "heavy dirty drop\ntearout wreck\nDrive-through\nfireworks crash"),
    ("inst", "hats metal\nbass cut"),
    ("inst", "harder dirty drop\nsub crush\nchest pyro"),
    ("inst", "hats skip\ngrowl cut"),
    ("inst", "full send drop\nstacked growl wreck\nmainstage pyro"),
    ("inst", "harder dirty drop\nlow 808 wreck\nfestival pyro"),
    ("outro", "axle out\nblend next"),
)

WEIGH_STATION_LYRICS = format_edm_score(
    ("intro", "weigh in\nDrive-through"),
    ("inst", "heavy dirty drop\nstacked 808 wreck\nfireworks crash"),
    ("inst", "hats skip\nbass cut"),
    ("inst", "harder dirty drop\nchest sub wall\nmainstage pyro"),
    ("inst", "hats roll\n808 cut"),
    ("inst", "full send drop\nbody bass wreck\nfestival pyro"),
    ("outro", "stamp out\nblend next"),
)

BLACK_ICE_LYRICS = format_edm_score(
    ("inst", "heavy dirty drop\nwobble wreck\nDrive-through\nfireworks crash"),
    ("inst", "hats metal\nbass cut"),
    ("inst", "harder dirty drop\nchest growl wreck\nmainstage pyro"),
    ("inst", "hats skip\nwobble cut"),
    ("inst", "full send drop\nsub crush wreck\nchest pyro"),
    ("inst", "hats ride\nbass growl"),
    ("inst", "harder dirty drop\nlow rumble wreck\nfestival pyro"),
    ("outro", "ice out\nblend next"),
)

HIGH_BEAMS_LYRICS = format_edm_score(
    ("intro", "beams in\nDrive-through"),
    ("inst", "heavy dirty drop\ndual-action pedal bass\nchest 808 wreck\nfireworks crash"),
    ("inst", "pedal swell\nhats cut"),
    ("inst", "harder stacked drop\nhybrid 808 wall\nmainstage pyro"),
    ("inst", "hats skip\nbass cut"),
    ("inst", "full send drop\nbody sub wreck\nchest pyro"),
    ("inst", "harder dirty drop\nstacked 808 wreck\nfestival pyro"),
    ("outro", "beams out\nblend next"),
)

CHAIN_HOOK_LYRICS = format_edm_score(
    ("inst", "heavy dirty drop\ngrowl wreck\nDrive-through\nfireworks crash"),
    ("inst", "harder dirty drop\nbrostep wreck\nchest pyro"),
    ("inst", "full send drop\nstacked 808 wreck\nmainstage pyro"),
    ("outro", "hook out\nblend next"),
)

GRIT_PLATE_LYRICS = format_edm_score(
    ("intro", "grit in\nDrive-through"),
    ("inst", "heavy dirty drop\nslap bass wreck\nfireworks crash"),
    ("inst", "harder dirty drop\nstacked 808 bounce\nchest pyro"),
    ("inst", "full send drop\nbody bass wreck\nmainstage pyro"),
    ("outro", "plate out\nblend next"),
)

STEEL_GRATE_LYRICS = format_edm_score(
    ("inst", "heavy dirty drop\namen wreck\nDrive-through\nfireworks crash"),
    ("inst", "amen chops\nhats cut"),
    ("inst", "harder dirty drop\nreese stack\nchest pyro"),
    ("inst", "hats razor\nbass wind"),
    ("inst", "full send drop\nstacked amen wreck\nmainstage pyro"),
    ("inst", "hats skip\n808 cut"),
    ("inst", "harder dirty drop\nchest 808 wreck\nchest pyro"),
    ("inst", "hats bounce\nbass cut"),
    ("inst", "full send drop\nlow rumble wreck\nfestival pyro"),
    ("outro", "grate out\nblend next"),
)

REST_BAY_LYRICS = format_edm_score(
    ("intro", "bay in\nDrive-through"),
    ("inst", "heavy dirty drop\ndual-action pedal bass\nchest sub wreck\nfireworks crash"),
    ("inst", "pedal swell\nhats cut"),
    ("inst", "harder dirty drop\nstacked 808 wall\nmainstage pyro"),
    ("inst", "hats skip\nbass cut"),
    ("inst", "full send drop\nbody chest wreck\nchest pyro"),
    ("inst", "harder stacked drop\nlow 808 wreck\nfestival pyro"),
    ("inst", "hats roll\nsub cut"),
    ("outro", "bay out\nblend next"),
)

HAUL_CRATE_LYRICS = format_edm_score(
    ("inst", "heavy dirty drop\ntrap 808 wreck\nDrive-through\nfireworks crash"),
    ("inst", "hats roll\nbass cut"),
    ("inst", "harder dirty drop\nstacked trap bass\nmainstage pyro"),
    ("inst", "hats skip\nchest cut"),
    ("inst", "full send drop\nchest 808 wall\nfestival pyro"),
    ("outro", "crate out\nblend next"),
)

NIGHT_SPLICE_LYRICS = format_edm_score(
    ("intro", "splice in\nDrive-through"),
    ("inst", "heavy dirty drop\nwave bass wreck\nfireworks crash"),
    ("inst", "hats skip\nbass cut"),
    ("inst", "harder dirty drop\nchest 808 wall\nmainstage pyro"),
    ("inst", "full send drop\nlow swell wreck\nfestival pyro"),
    ("outro", "splice out\nblend next"),
)

TORQUE_BAY_LYRICS = format_edm_score(
    ("inst", "heavy dirty drop\nreese 808 wreck\nDrive-through\nfireworks crash"),
    ("inst", "hats razor\nbass cut"),
    ("inst", "harder stacked drop\nchest reese wreck\nmainstage pyro"),
    ("inst", "hats skip\nsub cut"),
    ("inst", "full send drop\nneuro 808 wreck\nchest pyro"),
    ("inst", "harder dirty drop\nstacked reese wreck\nfestival pyro"),
    ("outro", "torque out\nblend next"),
)

SPARE_DRUM_LYRICS = format_edm_score(
    ("intro", "spare in\nDrive-through"),
    ("inst", "heavy dirty drop\ndual-action pedal bass\nchest 808 wreck\nfireworks crash"),
    ("inst", "pedal swell\nhats cut"),
    ("inst", "harder stacked drop\nbounce 808 wall\nmainstage pyro"),
    ("inst", "hats skip\nbass cut"),
    ("inst", "full send drop\nbody bass wreck\nfestival pyro"),
    ("outro", "drum out\nblend next"),
)

OIL_PAN_LYRICS = format_edm_score(
    ("inst", "heavy dirty drop\nbounce 808 wreck\nDrive-through\nfireworks crash"),
    ("inst", "hats bounce\nbass cut"),
    ("inst", "harder dirty drop\nstacked bounce 808\nchest pyro"),
    ("inst", "hats skip\n808 cut"),
    ("inst", "full send drop\nbody bass wreck\nmainstage pyro"),
    ("inst", "harder stacked drop\nchest sub wreck\nfestival pyro"),
    ("inst", "hats roll\nbass cut"),
    ("outro", "pan out\nblend next"),
)

CURB_CHECK_LYRICS = format_edm_score(
    ("intro", "curb in\nDrive-through"),
    ("inst", "heavy dirty drop\namen 808 wreck\nfireworks crash"),
    ("inst", "amen chops\nhats cut"),
    ("inst", "harder stacked drop\nreese 808 wreck\nchest pyro"),
    ("inst", "hats razor\nbass wind"),
    ("inst", "full send drop\nstacked amen wreck\nmainstage pyro"),
    ("inst", "harder dirty drop\nchest bounce wreck\nfestival pyro"),
    ("outro", "curb out\nblend next"),
)

LAST_EXIT_LYRICS = format_edm_score(
    ("inst", "heavy dirty drop\ndual-action pedal bass\nDrive-through\nfireworks crash"),
    ("inst", "pedal swell\nhats cut"),
    ("inst", "harder dirty drop\nchest 808 wall\nmainstage pyro"),
    ("inst", "full send drop\nlow rumble wreck\nfestival pyro"),
    ("outro", "exit out\nblend next"),
)

ASPHALT_HEART_LYRICS = format_edm_score(
    ("intro", "asphalt in\nDrive-through"),
    ("inst", "heavy dirty drop\nchest sub wreck\nfireworks crash"),
    ("inst", "full send drop\nbody chest wreck\nfestival pyro"),
    ("outro", "heart out\nblend next"),
)

CLUTCH_SLAM_LYRICS = format_edm_score(
    ("inst", "heavy dirty drop\ndual-action pedal bass\ntearout wreck\nDrive-through\nfireworks crash"),
    ("inst", "hats metal\nbass cut"),
    ("inst", "harder dirty drop\nsub crush\nchest pyro"),
    ("inst", "pedal swell\nhats cut"),
    ("inst", "full send drop\nstacked growl wreck\nmainstage pyro"),
    ("inst", "hats skip\n808 cut"),
    ("inst", "harder stacked drop\nchest 808 wreck\nfestival pyro"),
    ("inst", "full send drop\nlow rumble wreck\nchest pyro"),
    ("outro", "clutch out\nblend next"),
)

TRAILER_HITCH_LYRICS = format_edm_score(
    ("intro", "hitch in\nDrive-through"),
    ("inst", "heavy dirty drop\nchest 808 wreck\nfireworks crash"),
    ("inst", "hats skip\nbass cut"),
    ("inst", "harder stacked drop\nrolling 808 wall\nmainstage pyro"),
    ("inst", "hats roll\nsub cut"),
    ("inst", "full send drop\nbody bass wreck\nchest pyro"),
    ("inst", "harder dirty drop\nstacked 808 wreck\nmainstage pyro"),
    ("inst", "hats bounce\n808 cut"),
    ("inst", "full send drop\nchest sub wreck\nfestival pyro"),
    ("outro", "hitch out\nsky paid"),
)


EDM_DRIVE_THROUGH_AFTERPARTY: tuple[EdmExample, ...] = (
    _ex(
        "brake-fade",
        "brake fade",
        150,
        457,
        AFTERPARTY_PHASE,
        "brake-fade dirty bass",
        BRAKE_FADE_LYRICS,
        "dirty bass",
        "four on the floor",
        "chest sub",
        "stacked 808",
        "rave",
        "festival pyro",
        layout="column",
    ),
    _ex(
        "diesel-hum",
        "diesel hum",
        152,
        461,
        AFTERPARTY_PHASE,
        "diesel-hum bass house",
        DIESEL_HUM_LYRICS,
        "bass house",
        "four on the floor",
        "dual-action pedal bass",
        "chest sub",
        "rave",
        "festival pyro",
        layout="wide-stage",
    ),
    _ex(
        "axle-grind",
        "axle grind",
        155,
        463,
        AFTERPARTY_PHASE,
        "axle-grind tearout",
        AXLE_GRIND_LYRICS,
        "tearout",
        "bass growl",
        "heavy sub",
        "dirty 808",
        "rave",
        "festival pyro",
        layout="stacked-tower",
    ),
    _ex(
        "weigh-station",
        "weigh station",
        158,
        467,
        AFTERPARTY_PHASE,
        "weigh-station festival bass",
        WEIGH_STATION_LYRICS,
        "festival bass",
        "four on the floor",
        "stacked 808",
        "chest sub",
        "rave",
        "festival pyro",
        layout="prompt-left",
    ),
    _ex(
        "black-ice",
        "black ice",
        160,
        479,
        AFTERPARTY_PHASE,
        "black-ice riddim",
        BLACK_ICE_LYRICS,
        "riddim",
        "wobble bass",
        "heavy sub",
        "chest 808",
        "rave",
        "festival pyro",
        layout="output-rail",
    ),
    _ex(
        "high-beams",
        "high beams",
        165,
        487,
        AFTERPARTY_PHASE,
        "high-beams hybrid bass",
        HIGH_BEAMS_LYRICS,
        "hybrid bass",
        "four on the floor",
        "dual-action pedal bass",
        "chest sub",
        "rave",
        "festival pyro",
        layout="column",
    ),
    _ex(
        "chain-hook",
        "chain hook",
        168,
        491,
        AFTERPARTY_PHASE,
        "chain-hook dirty brostep",
        CHAIN_HOOK_LYRICS,
        "brostep",
        "dirty dubstep",
        "bass growl",
        "heavy sub",
        "rave",
        "festival pyro",
        layout="wide-stage",
    ),
    _ex(
        "grit-plate",
        "grit plate",
        150,
        499,
        AFTERPARTY_PHASE,
        "grit-plate slap house",
        GRIT_PLATE_LYRICS,
        "slap house",
        "four on the floor",
        "bounce bass",
        "dirty 808",
        "rave",
        "festival pyro",
        layout="stacked-tower",
    ),
    _ex(
        "steel-grate",
        "steel grate",
        172,
        503,
        AFTERPARTY_PHASE,
        "steel-grate drumstep",
        STEEL_GRATE_LYRICS,
        "drumstep",
        "festival",
        "amen break",
        "reese bass",
        "chest sub",
        "rave",
        "dirty pyro",
        layout="prompt-left",
    ),
    _ex(
        "rest-bay",
        "rest bay",
        155,
        509,
        AFTERPARTY_PHASE,
        "rest-bay chest bass",
        REST_BAY_LYRICS,
        "chest bass",
        "four on the floor",
        "dual-action pedal bass",
        "body bass",
        "rave",
        "festival pyro",
        layout="output-rail",
    ),
    _ex(
        "haul-crate",
        "haul crate",
        170,
        521,
        AFTERPARTY_PHASE,
        "haul-crate hybrid trap",
        HAUL_CRATE_LYRICS,
        "hybrid trap",
        "festival trap",
        "trap 808",
        "dirty bass",
        "rave",
        "festival pyro",
        layout="column",
    ),
    _ex(
        "night-splice",
        "night splice",
        152,
        523,
        AFTERPARTY_PHASE,
        "night-splice wave bass",
        NIGHT_SPLICE_LYRICS,
        "wave bass",
        "four on the floor",
        "chest 808",
        "low rumble",
        "rave",
        "festival pyro",
        layout="wide-stage",
    ),
    _ex(
        "torque-bay",
        "torque bay",
        176,
        541,
        AFTERPARTY_PHASE,
        "torque-bay neuro bass",
        TORQUE_BAY_LYRICS,
        "neuro bass",
        "drumstep",
        "reese bass",
        "chest sub",
        "rave",
        "festival pyro",
        layout="stacked-tower",
    ),
    _ex(
        "spare-drum",
        "spare drum",
        165,
        547,
        AFTERPARTY_PHASE,
        "spare-drum festival bass",
        SPARE_DRUM_LYRICS,
        "festival bass",
        "four on the floor",
        "dual-action pedal bass",
        "chest sub",
        "rave",
        "festival pyro",
        layout="prompt-left",
    ),
    _ex(
        "oil-pan",
        "oil pan",
        150,
        557,
        AFTERPARTY_PHASE,
        "oil-pan bounce house",
        OIL_PAN_LYRICS,
        "bounce house",
        "four on the floor",
        "bounce 808",
        "chest sub",
        "rave",
        "festival pyro",
        layout="output-rail",
    ),
    _ex(
        "curb-check",
        "curb check",
        174,
        563,
        AFTERPARTY_PHASE,
        "curb-check drumstep",
        CURB_CHECK_LYRICS,
        "drumstep",
        "festival",
        "amen break",
        "bounce 808",
        "chest sub",
        "rave",
        "dirty pyro",
        layout="column",
    ),
    _ex(
        "last-exit",
        "last exit",
        160,
        569,
        AFTERPARTY_PHASE,
        "last-exit dirty bass",
        LAST_EXIT_LYRICS,
        "dirty bass",
        "four on the floor",
        "dual-action pedal bass",
        "chest sub",
        "rave",
        "festival pyro",
        layout="wide-stage",
    ),
    _ex(
        "asphalt-heart",
        "asphalt heart",
        155,
        571,
        AFTERPARTY_PHASE,
        "asphalt-heart chest bass",
        ASPHALT_HEART_LYRICS,
        "chest bass",
        "four on the floor",
        "stacked 808",
        "body bass",
        "rave",
        "festival pyro",
        layout="stacked-tower",
    ),
    _ex(
        "clutch-slam",
        "clutch slam",
        168,
        577,
        AFTERPARTY_PHASE,
        "clutch-slam dirty tearout",
        CLUTCH_SLAM_LYRICS,
        "tearout",
        "dirty dubstep",
        "dual-action pedal bass",
        "heavy sub",
        "rave",
        "festival pyro",
        layout="prompt-left",
    ),
    _ex(
        "trailer-hitch",
        "trailer hitch",
        165,
        587,
        AFTERPARTY_PHASE,
        "trailer-hitch festival bass",
        TRAILER_HITCH_LYRICS,
        "festival bass",
        "four on the floor",
        "stacked 808",
        "chest sub",
        "rave",
        "festival pyro",
        layout="output-rail",
    ),
)
