"""Drive-through 180s bass-set takes (hour 3, headliner).

Fictional act. Original dance arrangements. No living-artist names.
Warped hybrid-trap EDM: drop first, hard warpy drops, trap drums, high-BPM
headliner energy, all instrumental.
"""

from __future__ import annotations

from .edm_examples import EdmExample, _ex, format_edm_score

HEADLINER_PHASE = 2


LANTERN_MERGE_LYRICS = format_edm_score(
    ("inst", "heavy warped drop\ntrap 808 wreck\nchest formant"),
    ("inst", "trap hats roll\n808 slide"),
    ("inst", "harder growl drop\nstacked trap 808\nchest warp"),
    ("inst", "snare roll\nchest 808 punch"),
    ("inst", "full send drop\nbody bass wreck\nwarped trap"),
    ("outro", "kick holds\ntrap hats roll\nchest ride"),
)

FIREFLY_LANE_LYRICS = format_edm_score(
    ("inst", "heavy color drop\ntrap 808 warp\nchest wreck"),
    ("inst", "trap hats denser\ncolor 808 sustain firefly"),
    ("inst", "harder stacked drop\nchest color wreck\nwarped 808"),
    ("inst", "full send drop\ndirty trap 808\nformant wall"),
    ("outro", "kick holds\nhats denser\ncolor ride"),
)

CANOPY_BOUNCE_LYRICS = format_edm_score(
    ("inst", "heavy chest drop\ntrap 808 warp\ncanopy wreck"),
    ("inst", "trap hats roll\nchest 808 hold"),
    ("inst", "harder growl drop\nstacked body 808\nwarped chest"),
    ("inst", "snare roll\n808 punch"),
    ("inst", "full send drop\nchest bass wreck\ntrap warp"),
    ("outro", "kick holds\ntrap hats roll\nchest ride"),
)

GROVE_WRECK_LYRICS = format_edm_score(
    ("inst", "heavy riddim drop\nwobble trap 808\nchest wreck"),
    ("inst", "metal hats roll\nwarp 808 sustain grove"),
    ("inst", "harder stacked drop\nchest growl wreck\ntrap 808"),
    ("inst", "trap hats denser\nwobble hold"),
    ("inst", "full send drop\nchest sub wreck\nwarped riddim"),
    ("inst", "harder warped drop\nchest 808 wreck\ntrap growl"),
    ("outro", "kick holds\nhats denser\nwobble ride"),
)

MOSS_SUB_LYRICS = format_edm_score(
    ("inst", "heavy dirty drop\nchest sub warp\ntrap 808 wreck"),
    ("inst", "trap hats roll\npedal 808 hold"),
    ("inst", "harder growl drop\ndual-action pedal bass\nrolling 808 wall"),
    ("inst", "hats denser\nchest 808"),
    ("inst", "full send drop\nbody 808 wreck\nwarped trap"),
    ("outro", "kick holds\ntrap hats roll\npedal ride"),
)

FERN_STACK_LYRICS = format_edm_score(
    ("inst", "heavy hybrid drop\nstacked trap 808\nchest warp wreck"),
    ("inst", "trap hats roll\n808 slide"),
    ("inst", "harder stacked drop\nchest trap wreck\nwarped 808"),
    ("inst", "snare roll\nchest 808 punch"),
    ("inst", "full send drop\nbody 808 stack\nformant trap"),
    ("inst", "harder growl drop\ntrap bass wreck\nchest warp"),
    ("outro", "kick holds\nhats denser\n808 ride"),
)

POLLEN_KICK_LYRICS = format_edm_score(
    ("inst", "heavy amen drop\ntrap 808 warp\nchest wreck"),
    ("inst", "amen chops\ntrap hats 808 pollen"),
    ("inst", "harder stacked drop\nreese 808 wreck\nchest formant"),
    ("inst", "hats denser\nreese hold"),
    ("inst", "full send drop\nstacked amen 808 wreck\nwarped trap"),
    ("inst", "snare roll\n808 punch"),
    ("inst", "harder growl drop\nchest trap wreck\nreese wall"),
    ("outro", "kick holds\namen keep\nreese ride"),
)

CEDAR_GROWL_LYRICS = format_edm_score(
    ("inst", "heavy tearout drop\ntrap growl wreck\nchest 808 warp"),
    ("inst", "metal hats roll\ngrowl sustain"),
    ("inst", "harder stacked drop\nchest 808 wreck\nwarped trap"),
    ("inst", "full send drop\nchest sub wreck\ntearout warp"),
    ("outro", "kick holds\ntrap hats roll\ngrowl ride"),
)

MOON_RAMP_LYRICS = format_edm_score(
    ("inst", "heavy wave drop\ntrap 808 warp\nchest fold wreck"),
    ("inst", "trap hats denser\nwave 808 hold moon"),
    ("inst", "harder growl drop\nchest 808 wall\nwarped wave"),
    ("inst", "snare roll\n808 slide"),
    ("inst", "full send drop\nbody wave wreck\ntrap formant"),
    ("outro", "kick holds\nhats denser\nwave ride"),
)

TRAIL_BOUNCE_LYRICS = format_edm_score(
    ("inst", "heavy color drop\ntrap 808 warp\nchest trail wreck"),
    ("inst", "trap hats roll\n808 punch hold"),
    ("inst", "harder stacked drop\nchest color wreck\nwarped 808"),
    ("inst", "snare roll\nchest 808"),
    ("inst", "full send drop\nbody 808 wreck\ncolor warp"),
    ("inst", "harder growl drop\ntrap bass wall\nchest formant"),
    ("outro", "kick holds\ntrap hats roll\ncolor ride"),
)

DEW_WRECK_LYRICS = format_edm_score(
    ("inst", "heavy neuro drop\nreese trap 808\nchest warp wreck"),
    ("inst", "amen chops\ntrap hats 808 dew"),
    ("inst", "harder stacked drop\nchest reese wreck\nwarped 808"),
    ("inst", "hats denser\nreese hold"),
    ("inst", "full send drop\ntrap 808 wreck\nchest formant"),
    ("inst", "snare roll\n808 punch"),
    ("inst", "harder growl drop\nstacked neuro 808 wreck\ntrap warp"),
    ("inst", "full send drop\nbody reese wreck\nchest 808"),
    ("outro", "kick holds\namen keep\nreese ride"),
)

SAP_STACK_LYRICS = format_edm_score(
    ("inst", "heavy brostep drop\nchest trap 808\nwarped wreck"),
    ("inst", "trap hats denser\ngrowl hold"),
    ("inst", "harder stacked drop\ntrap 808 wall\nchest formant"),
    ("inst", "snare roll\n808 punch"),
    ("inst", "full send drop\nbody bass wreck\nwarped trap"),
    ("inst", "harder growl drop\nstacked 808 wreck\nchest warp"),
    ("outro", "kick holds\nhats denser\nbrostep ride"),
)

GLADE_SPLIT_LYRICS = format_edm_score(
    ("inst", "heavy dubstep drop\ntrap 808 warp\nchest split wreck"),
    ("inst", "trap hats roll\nwobble hold"),
    ("inst", "harder stacked drop\nchest analog wreck\nwarped 808"),
    ("inst", "snare roll\nchest 808"),
    ("inst", "full send drop\ndouble 808 wreck\ntrap formant"),
    ("inst", "hats denser\n808 punch"),
    ("inst", "harder growl drop\nbody dubstep wreck\nchest warp"),
    ("outro", "kick holds\ntrap hats roll\nwobble ride"),
)

ROOT_CHEST_LYRICS = format_edm_score(
    ("inst", "heavy chest drop\ntrap sub wreck\nwarped 808"),
    ("inst", "trap hats denser\nchest 808 hold"),
    ("inst", "harder chest drop\ndual-action pedal bass\nstacked 808 warp"),
    ("inst", "pedal 808 hold\nhats roll"),
    ("inst", "full send drop\nbody chest wreck\ntrap warp"),
    ("inst", "hats denser\n808 punch"),
    ("inst", "harder stacked drop\ntrap 808 wreck\nchest formant"),
    ("inst", "full send drop\nchest sub wreck\nwarped pedal"),
    ("outro", "kick holds\ntrap hats roll\npedal ride"),
)

EMBER_CREST_LYRICS = format_edm_score(
    ("inst", "heavy warped drop\ntrap 808 wreck\nchest crest grind"),
    ("inst", "trap hats roll\n808 slide"),
    ("inst", "harder stacked drop\nchest 808 wall\ntrap formant"),
    ("inst", "snare roll\nchest 808 punch"),
    ("inst", "full send drop\nbody bass wreck\nwarped trap"),
    ("inst", "harder growl drop\nstacked trap wreck\nchest 808"),
    ("inst", "full send drop\nchest sub wreck\nwarp wall"),
    ("outro", "kick holds\nhats denser\n808 ride"),
)


EDM_DRIVE_THROUGH_HEADLINER: tuple[EdmExample, ...] = (
    _ex(
        "lantern-merge",
        "lantern merge",
        150,
        367,
        HEADLINER_PHASE,
        "lantern-merge hybrid trap warp",
        LANTERN_MERGE_LYRICS,
        "hybrid trap",
        "warped bass",
        "trap hats",
        "chest sub",
        "rave",
        layout="wide-stage",
    ),
    _ex(
        "firefly-lane",
        "firefly lane",
        152,
        373,
        HEADLINER_PHASE,
        "firefly-lane color bass warp",
        FIREFLY_LANE_LYRICS,
        "color bass",
        "warped bass",
        "trap hats",
        "dirty 808",
        "chest sub",
        "rave",
        layout="stacked-tower",
    ),
    _ex(
        "canopy-bounce",
        "canopy bounce",
        148,
        379,
        HEADLINER_PHASE,
        "canopy-bounce chest bass warp",
        CANOPY_BOUNCE_LYRICS,
        "chest bass",
        "warped bass",
        "trap hats",
        "body bass",
        "rave",
        layout="prompt-left",
    ),
    _ex(
        "grove-wreck",
        "grove wreck",
        150,
        383,
        HEADLINER_PHASE,
        "grove-wreck riddim warp",
        GROVE_WRECK_LYRICS,
        "riddim",
        "warped bass",
        "trap hats",
        "wobble bass",
        "heavy sub",
        "rave",
        layout="output-rail",
    ),
    _ex(
        "moss-sub",
        "moss sub",
        150,
        389,
        HEADLINER_PHASE,
        "moss-sub dirty bass warp",
        MOSS_SUB_LYRICS,
        "dirty bass",
        "warped bass",
        "trap hats",
        "chest sub",
        "dual-action pedal bass",
        "rolling 808",
        "rave",
        layout="column",
    ),
    _ex(
        "fern-stack",
        "fern stack",
        155,
        397,
        HEADLINER_PHASE,
        "fern-stack hybrid trap warp",
        FERN_STACK_LYRICS,
        "hybrid trap",
        "warped bass",
        "trap hats",
        "stacked 808",
        "rave",
        layout="wide-stage",
    ),
    _ex(
        "pollen-kick",
        "pollen kick",
        174,
        401,
        HEADLINER_PHASE,
        "pollen-kick drumstep warp",
        POLLEN_KICK_LYRICS,
        "drumstep",
        "warped bass",
        "trap hats",
        "amen break",
        "chest sub",
        "rave",
        layout="stacked-tower",
    ),
    _ex(
        "cedar-growl",
        "cedar growl",
        150,
        409,
        HEADLINER_PHASE,
        "cedar-growl tearout warp",
        CEDAR_GROWL_LYRICS,
        "tearout",
        "warped bass",
        "trap hats",
        "bass growl",
        "heavy sub",
        "rave",
        layout="prompt-left",
    ),
    _ex(
        "moon-ramp",
        "moon ramp",
        148,
        419,
        HEADLINER_PHASE,
        "moon-ramp wave bass warp",
        MOON_RAMP_LYRICS,
        "wave bass",
        "warped bass",
        "trap hats",
        "chest 808",
        "rave",
        layout="output-rail",
    ),
    _ex(
        "trail-bounce",
        "trail bounce",
        150,
        421,
        HEADLINER_PHASE,
        "trail-bounce color bass warp",
        TRAIL_BOUNCE_LYRICS,
        "color bass",
        "warped bass",
        "trap hats",
        "body bass",
        "chest sub",
        "rave",
        layout="column",
    ),
    _ex(
        "dew-wreck",
        "dew wreck",
        172,
        431,
        HEADLINER_PHASE,
        "dew-wreck neuro bass warp",
        DEW_WRECK_LYRICS,
        "neuro bass",
        "warped bass",
        "trap hats",
        "drumstep",
        "reese bass",
        "chest sub",
        "rave",
        layout="wide-stage",
    ),
    _ex(
        "sap-stack",
        "sap stack",
        165,
        433,
        HEADLINER_PHASE,
        "sap-stack brostep warp",
        SAP_STACK_LYRICS,
        "brostep",
        "warped bass",
        "trap hats",
        "stacked 808",
        "chest sub",
        "rave",
        layout="stacked-tower",
    ),
    _ex(
        "glade-split",
        "glade split",
        150,
        439,
        HEADLINER_PHASE,
        "glade-split dirty dubstep warp",
        GLADE_SPLIT_LYRICS,
        "dirty dubstep",
        "warped bass",
        "trap hats",
        "wobble bass",
        "chest sub",
        "rave",
        layout="prompt-left",
    ),
    _ex(
        "root-chest",
        "root chest",
        148,
        443,
        HEADLINER_PHASE,
        "root-chest chest bass warp",
        ROOT_CHEST_LYRICS,
        "chest bass",
        "warped bass",
        "trap hats",
        "dual-action pedal bass",
        "body bass",
        "rave",
        layout="output-rail",
    ),
    _ex(
        "ember-crest",
        "ember crest",
        165,
        449,
        HEADLINER_PHASE,
        "ember-crest hybrid trap warp",
        EMBER_CREST_LYRICS,
        "hybrid trap",
        "warped bass",
        "trap hats",
        "heavy sub",
        "rave",
        layout="column",
    ),
)
