"""Drive-through 180s rave DJ-set takes (hour 3, headliner).

Fictional act. Original dance arrangements. No living-artist names.
American festival EDM: drop early, dirty pyro on every drop, all instrumental.
Deeper bounce bass, heavier stacked drops, high-BPM headliner energy.
"""

from __future__ import annotations

from .edm_examples import EdmExample, _ex, format_edm_score

HEADLINER_PHASE = 2


LANTERN_MERGE_LYRICS = format_edm_score(
    ("inst", "heavy bounce drop\nchest 808 wreck\nDrive-through\nfireworks crash"),
    ("inst", "harder bounce drop\nstacked 808 bounce\nmainstage pyro"),
    ("inst", "full send drop\nbody bass wreck\nfestival pyro"),
    ("outro", "filter down\nblend next"),
)

FIREFLY_LANE_LYRICS = format_edm_score(
    ("intro", "spark in\nDrive-through"),
    ("inst", "heavy color drop\nbounce 808 wreck\nfireworks crash"),
    ("inst", "harder stacked drop\nchest color wreck\nmainstage pyro"),
    ("inst", "full send drop\ndirty bounce 808\nfestival pyro"),
    ("outro", "spark out\nblend next"),
)

CANOPY_BOUNCE_LYRICS = format_edm_score(
    ("inst", "heavy bounce drop\nchest 808 wreck\nDrive-through\nfireworks crash"),
    ("inst", "hats bounce\nbass cut"),
    ("inst", "harder bounce drop\nstacked body 808\nchest pyro"),
    ("inst", "hats skip\nair"),
    ("inst", "full send drop\nbounce bass wreck\nmainstage pyro"),
    ("outro", "canopy out\nblend next"),
)

GROVE_WRECK_LYRICS = format_edm_score(
    ("inst", "heavy riddim drop\nwobble 808 wreck\nDrive-through\nfireworks crash"),
    ("inst", "hats metal\nbass cut"),
    ("inst", "harder stacked drop\nchest growl wreck\nmainstage pyro"),
    ("inst", "full send drop\nbounce sub wreck\nfestival pyro"),
    ("outro", "grove out\nblend next"),
)

MOSS_SUB_LYRICS = format_edm_score(
    ("inst", "heavy space drop\nchest sub wreck\nDrive-through\nfireworks crash"),
    ("inst", "harder bounce drop\nrolling 808 wall\nmainstage pyro"),
    ("outro", "moss out\nblend next"),
)

FERN_STACK_LYRICS = format_edm_score(
    ("inst", "heavy hybrid drop\nstacked 808 wreck\nDrive-through\nfireworks crash"),
    ("inst", "hats bounce\nbass cut"),
    ("inst", "harder stacked drop\nchest bounce wreck\nmainstage pyro"),
    ("inst", "filter ride\nair"),
    ("inst", "full send drop\nbody 808 stack\nchest pyro"),
    ("inst", "harder dirty drop\nbounce bass wreck\nfestival pyro"),
    ("outro", "fern out\nblend next"),
)

POLLEN_KICK_LYRICS = format_edm_score(
    ("inst", "heavy amen drop\nbounce 808 wreck\nDrive-through\nfireworks crash"),
    ("inst", "amen chops\nair"),
    ("inst", "harder stacked drop\nreese 808 wreck\nchest pyro"),
    ("inst", "hats razor\nbass wind"),
    ("inst", "full send drop\nstacked amen 808 wreck\nmainstage pyro"),
    ("inst", "hats bounce\n808 punch"),
    ("inst", "harder dirty drop\nchest bounce wreck\nfestival pyro"),
    ("outro", "amen stop\nblend next"),
)

CEDAR_GROWL_LYRICS = format_edm_score(
    ("intro", "growl tease\nDrive-through"),
    ("inst", "heavy riddim drop\nbounce growl wreck\nfireworks crash"),
    ("inst", "hats metal\nbass cut"),
    ("inst", "harder stacked drop\nchest 808 wreck\nmainstage pyro"),
    ("inst", "full send drop\nbounce sub wreck\nfestival pyro"),
    ("outro", "cedar out\nblend next"),
)

MOON_RAMP_LYRICS = format_edm_score(
    ("intro", "wave in\nDrive-through"),
    ("inst", "heavy wave drop\nbounce 808 wreck\nfireworks crash"),
    ("inst", "hats skip\nbass cut"),
    ("inst", "harder bounce drop\nchest 808 wall\nmainstage pyro"),
    ("inst", "filter ride\nair"),
    ("inst", "full send drop\nbody wave wreck\nfestival pyro"),
    ("outro", "wave out\nblend next"),
)

TRAIL_BOUNCE_LYRICS = format_edm_score(
    ("intro", "trail in\nDrive-through"),
    ("inst", "heavy bounce drop\nslap 808 wreck\nfireworks crash"),
    ("inst", "hats bounce\nair"),
    ("inst", "harder stacked drop\nchest bounce wreck\nmainstage pyro"),
    ("inst", "bass cut\nhats skip"),
    ("inst", "full send drop\nbody 808 wreck\nchest pyro"),
    ("inst", "harder dirty drop\nbounce bass wall\nfestival pyro"),
    ("outro", "trail out\nblend next"),
)

DEW_WRECK_LYRICS = format_edm_score(
    ("inst", "heavy neuro drop\nreese 808 wreck\nDrive-through\nfireworks crash"),
    ("inst", "amen chops\nglitch"),
    ("inst", "harder stacked drop\nchest reese wreck\nmainstage pyro"),
    ("inst", "hats razor\nbass wind"),
    ("inst", "full send drop\nbounce 808 wreck\nchest pyro"),
    ("inst", "break chops\nair"),
    ("inst", "harder dirty drop\nstacked neuro 808 wreck\nmainstage pyro"),
    ("inst", "full send drop\nbody reese wreck\nfestival pyro"),
    ("outro", "dew out\nblend next"),
)

SAP_STACK_LYRICS = format_edm_score(
    ("intro", "sap in\nDrive-through"),
    ("inst", "heavy stacked drop\nchest 808 wreck\nfireworks crash"),
    ("inst", "hats skip\nbass cut"),
    ("inst", "harder stacked drop\nbounce 808 wall\nmainstage pyro"),
    ("inst", "filter ride\nair"),
    ("inst", "full send drop\nbody bass wreck\nchest pyro"),
    ("inst", "harder dirty drop\nstacked 808 wreck\nfestival pyro"),
    ("outro", "sap out\nblend next"),
)

GLADE_SPLIT_LYRICS = format_edm_score(
    ("intro", "split in\nDrive-through"),
    ("inst", "heavy electro drop\nbounce 808 wreck\nfireworks crash"),
    ("inst", "hats analog\nbass cut"),
    ("inst", "harder stacked drop\nchest analog wreck\nmainstage pyro"),
    ("inst", "filter ride\nair"),
    ("inst", "full send drop\ndouble 808 wreck\nchest pyro"),
    ("inst", "hats bounce\nspace"),
    ("inst", "harder dirty drop\nbody electro wreck\nfestival pyro"),
    ("outro", "glade out\nblend next"),
)

ROOT_CHEST_LYRICS = format_edm_score(
    ("inst", "heavy chest drop\nbounce sub wreck\nDrive-through\nfireworks crash"),
    ("inst", "hats only\nair"),
    ("inst", "harder chest drop\nstacked 808 wall\nmainstage pyro"),
    ("inst", "bass cut\nhats skip"),
    ("inst", "full send drop\nbody chest wreck\nchest pyro"),
    ("inst", "filter ride\nair"),
    ("inst", "harder stacked drop\nbounce 808 wreck\nmainstage pyro"),
    ("inst", "hats bounce\nspace"),
    ("inst", "full send drop\nchest sub wreck\nfestival pyro"),
    ("outro", "root out\nblend next"),
)

EMBER_CREST_LYRICS = format_edm_score(
    ("intro", "crest in\nDrive-through"),
    ("inst", "heavy festival drop\nbounce 808 wreck\nfireworks crash"),
    ("inst", "hats skip\nbass cut"),
    ("inst", "harder stacked drop\nchest 808 wall\nmainstage pyro"),
    ("inst", "filter ride\nair"),
    ("inst", "full send drop\nbody bass wreck\nchest pyro"),
    ("inst", "hats bounce\nspace"),
    ("inst", "harder dirty drop\nstacked bounce wreck\nmainstage pyro"),
    ("inst", "full send drop\nchest sub wreck\nfestival pyro"),
    ("outro", "crest out\nsky paid"),
)


EDM_DRIVE_THROUGH_HEADLINER: tuple[EdmExample, ...] = (
    _ex(
        "lantern-merge",
        "lantern merge",
        150,
        367,
        HEADLINER_PHASE,
        "lantern-merge bounce house",
        LANTERN_MERGE_LYRICS,
        "bounce house",
        "four on the floor",
        "bounce 808",
        "chest sub",
        "rave",
        "festival pyro",
        layout="wide-stage",
    ),
    _ex(
        "firefly-lane",
        "firefly lane",
        152,
        373,
        HEADLINER_PHASE,
        "firefly-lane color bass",
        FIREFLY_LANE_LYRICS,
        "color bass",
        "four on the floor",
        "bounce bass",
        "dirty 808",
        "rave",
        "festival pyro",
        layout="stacked-tower",
    ),
    _ex(
        "canopy-bounce",
        "canopy bounce",
        148,
        379,
        HEADLINER_PHASE,
        "canopy-bounce bass house",
        CANOPY_BOUNCE_LYRICS,
        "bass house",
        "four on the floor",
        "bounce 808",
        "body bass",
        "rave",
        "festival pyro",
        layout="prompt-left",
    ),
    _ex(
        "grove-wreck",
        "grove wreck",
        150,
        383,
        HEADLINER_PHASE,
        "grove-wreck future riddim",
        GROVE_WRECK_LYRICS,
        "future riddim",
        "wobble bass",
        "heavy sub",
        "bounce 808",
        "rave",
        "festival pyro",
        layout="output-rail",
    ),
    _ex(
        "moss-sub",
        "moss sub",
        150,
        389,
        HEADLINER_PHASE,
        "moss-sub space bass",
        MOSS_SUB_LYRICS,
        "space bass",
        "four on the floor",
        "chest sub",
        "rolling 808",
        "rave",
        "festival pyro",
        layout="column",
    ),
    _ex(
        "fern-stack",
        "fern stack",
        155,
        397,
        HEADLINER_PHASE,
        "fern-stack hybrid bass",
        FERN_STACK_LYRICS,
        "hybrid bass",
        "four on the floor",
        "stacked 808",
        "bounce bass",
        "rave",
        "festival pyro",
        layout="wide-stage",
    ),
    _ex(
        "pollen-kick",
        "pollen kick",
        174,
        401,
        HEADLINER_PHASE,
        "pollen-kick drumstep",
        POLLEN_KICK_LYRICS,
        "drumstep",
        "festival",
        "amen break",
        "bounce 808",
        "rave",
        "dirty pyro",
        layout="stacked-tower",
    ),
    _ex(
        "cedar-growl",
        "cedar growl",
        150,
        409,
        HEADLINER_PHASE,
        "cedar-growl riddim",
        CEDAR_GROWL_LYRICS,
        "riddim",
        "bass growl",
        "bounce 808",
        "heavy sub",
        "rave",
        "festival pyro",
        layout="prompt-left",
    ),
    _ex(
        "moon-ramp",
        "moon ramp",
        148,
        419,
        HEADLINER_PHASE,
        "moon-ramp wave bass",
        MOON_RAMP_LYRICS,
        "wave bass",
        "four on the floor",
        "bounce bass",
        "chest 808",
        "rave",
        "festival pyro",
        layout="output-rail",
    ),
    _ex(
        "trail-bounce",
        "trail bounce",
        150,
        421,
        HEADLINER_PHASE,
        "trail-bounce slap house",
        TRAIL_BOUNCE_LYRICS,
        "slap house",
        "four on the floor",
        "bounce 808",
        "body bass",
        "rave",
        "festival pyro",
        layout="column",
    ),
    _ex(
        "dew-wreck",
        "dew wreck",
        172,
        431,
        HEADLINER_PHASE,
        "dew-wreck neuro bass",
        DEW_WRECK_LYRICS,
        "neuro bass",
        "drumstep",
        "reese bass",
        "bounce 808",
        "rave",
        "festival pyro",
        layout="wide-stage",
    ),
    _ex(
        "sap-stack",
        "sap stack",
        165,
        433,
        HEADLINER_PHASE,
        "sap-stack festival bass",
        SAP_STACK_LYRICS,
        "festival bass",
        "four on the floor",
        "stacked 808",
        "chest sub",
        "rave",
        "festival pyro",
        layout="stacked-tower",
    ),
    _ex(
        "glade-split",
        "glade split",
        150,
        439,
        HEADLINER_PHASE,
        "glade-split dirty electro",
        GLADE_SPLIT_LYRICS,
        "dirty electro",
        "four on the floor",
        "bounce 808",
        "analog bass",
        "rave",
        "festival pyro",
        layout="prompt-left",
    ),
    _ex(
        "root-chest",
        "root chest",
        148,
        443,
        HEADLINER_PHASE,
        "root-chest chest bass",
        ROOT_CHEST_LYRICS,
        "chest bass",
        "four on the floor",
        "bounce 808",
        "body bass",
        "rave",
        "festival pyro",
        layout="output-rail",
    ),
    _ex(
        "ember-crest",
        "ember crest",
        165,
        449,
        HEADLINER_PHASE,
        "ember-crest festival bass",
        EMBER_CREST_LYRICS,
        "festival bass",
        "four on the floor",
        "bounce 808",
        "heavy sub",
        "rave",
        "festival pyro",
        layout="column",
    ),
)
