"""Drive-through 180s bass-set takes (hour 2).

Fictional act. Original dance arrangements. No living-artist names.
Warped hybrid-trap EDM: drop first, hard warpy drops, trap drums, no quiet
dips, all instrumental.
"""

from __future__ import annotations

from .edm_examples import EdmExample, _ex, format_edm_score

# Track scores and catalog rows.
RUMBLE_STRIP_LYRICS = format_edm_score(
    ("inst", "heavy warped drop\nhybrid trap 808 wreck\nrumble grind"),
    ("inst", "trap hats roll\n808 slide"),
    ("inst", "harder growl drop\ndual-action pedal bass\nstacked warp"),
    ("inst", "pedal 808 hold\nhats denser"),
    ("inst", "full send drop\nlow rumble wreck\nchest formant"),
    ("outro", "kick holds\ntrap hats roll\npedal ride"),
)

LOW_LANE_LYRICS = format_edm_score(
    ("inst", "heavy riddim drop\nchest sub wobble\nwarped wreck"),
    ("inst", "harder growl drop\nrolling 808 wall\nformant crush"),
    ("inst", "trap hats denser\nwobble sustain"),
    ("inst", "snare roll\nchest 808"),
    ("inst", "808 triplets\nriddim growl hold"),
    ("inst", "full send drop\nwarped sub stack\nriddim wreck"),
    ("outro", "kick holds\nhats denser\nwobble ride"),
)

WARM_MERGE_LYRICS = format_edm_score(
    ("inst", "heavy wave drop\nwarped 808 wreck\nfold grind"),
    ("inst", "trap hats roll\nwave 808 hold merge"),
    ("inst", "harder formant drop\nstacked wave bass\nchest 808"),
    ("inst", "snare roll\n808 slide"),
    ("inst", "full send drop\nlow 808 wall\nwarped fold"),
    ("outro", "kick holds\ntrap hats roll\nwave ride"),
)

COLOUR_SPAN_LYRICS = format_edm_score(
    ("inst", "heavy color drop\nchest 808 warp\nformant wreck"),
    ("inst", "harder growl drop\nanalog 808 stack\nwarped color"),
    ("inst", "trap hats denser\ncolor 808 sustain span"),
    ("inst", "full send drop\nstacked color wreck\nwarped sub"),
    ("outro", "kick holds\nhats denser\ncolor ride"),
)

GARAGE_TICKET_LYRICS = format_edm_score(
    ("inst", "heavy trap drop\nwarped 808 wreck\nformant stamp"),
    ("inst", "trap hats roll\n808 slide"),
    ("inst", "harder growl drop\nstacked trap bass\nchest warp"),
    ("inst", "snare roll\nchest 808 punch"),
    ("inst", "full send drop\nchest 808 wall\nwarped trap"),
    ("outro", "kick holds\ntrap hats roll\n808 ride"),
)

LIQUID_GRADE_LYRICS = format_edm_score(
    ("inst", "heavy drumstep drop\nreese wreck\nwarped amen"),
    ("inst", "amen chops\ntrap hats 808 liquid"),
    ("inst", "harder growl drop\nreese stack\nchest formant"),
    ("inst", "hats denser\nreese hold"),
    ("inst", "full send drop\nstacked amen wreck\nwarped 808 punch"),
    ("inst", "harder warped drop\nchest 808 wreck\ndrumstep grind"),
    ("outro", "kick holds\namen keep\nreese ride"),
)

JUMP_BAY_LYRICS = format_edm_score(
    ("inst", "heavy brostep drop\ngrowl wreck\nwarped 808"),
    ("inst", "metal hats roll\ngrowl sustain"),
    ("inst", "harder formant drop\nsub crush\nchest 808"),
    ("inst", "trap hats denser\nwobble hold"),
    ("inst", "full send drop\nbrostep wreck\nstacked growl"),
    ("inst", "snare roll\nbass growl hold"),
    ("inst", "harder warped drop\nstacked 808 wreck\nmid growl"),
    ("outro", "kick holds\nhats denser\ngrowl ride"),
)

PSY_MEDIAN_LYRICS = format_edm_score(
    ("inst", "heavy neuro drop\nreese 808 wreck\nwarped coil"),
    ("inst", "trap hats roll\nreese sustain"),
    ("inst", "harder stacked drop\nformant 808 wall\nchest sub"),
    ("inst", "full send drop\nchest sub wreck\nneuro warp"),
    ("outro", "kick holds\ntrap hats roll\nreese ride"),
)

GROOVE_MILE_LYRICS = format_edm_score(
    ("inst", "heavy warped drop\nhybrid trap 808 wreck\nmile grind"),
    ("inst", "trap hats roll\n808 bounce hold"),
    ("inst", "harder growl drop\nstacked 808 warp\nchest punch"),
    ("inst", "snare roll\nchest 808"),
    ("inst", "full send drop\nbody bass wreck\nwarped trap"),
    ("outro", "kick holds\nhats denser\n808 ride"),
)

DONK_RAMP_LYRICS = format_edm_score(
    ("inst", "heavy tearout drop\ngrowl 808 wreck\nformant ramp"),
    ("inst", "harder warped drop\nchest 808 stack\ntearout grind"),
    ("inst", "trap hats denser\ngrowl sustain"),
    ("inst", "full send drop\ndirty analog wreck\nwarped 808"),
    ("outro", "kick holds\ntrap hats roll\ngrowl ride"),
)

BOUNCE_BOOTH_LYRICS = format_edm_score(
    ("inst", "heavy chest drop\nwarped 808 wreck\nbooth grind"),
    ("inst", "trap hats roll\n808 punch hold"),
    ("inst", "harder growl drop\nstacked chest 808\nformant wall"),
    ("inst", "snare roll\nchest sub hold"),
    ("inst", "full send drop\nlow 808 wreck\nwarped chest"),
    ("outro", "kick holds\nhats denser\nchest ride"),
)

TOLL_GROWL_LYRICS = format_edm_score(
    ("inst", "heavy riddim drop\ntearout growl wreck\nwarped toll"),
    ("inst", "metal hats roll\ngrowl sustain"),
    ("inst", "harder formant drop\nsub crush\nchest 808"),
    ("inst", "trap hats denser\ngrowl hold"),
    ("inst", "full send drop\nstacked growl wreck\nwobble wall"),
    ("inst", "snare roll\nbass growl hold"),
    ("inst", "harder warped drop\nstacked growl wreck\nlow rumble"),
    ("outro", "kick holds\nhats denser\ngrowl ride"),
)

NIGHT_OIL_LYRICS = format_edm_score(
    ("inst", "heavy hybrid drop\nwarped 808 wreck\noil grind"),
    ("inst", "trap hats roll\n808 slide"),
    ("inst", "harder growl drop\ntrap bass wall\nformant crush"),
    ("inst", "full send drop\nchest sub wreck\nhybrid warp"),
    ("outro", "kick holds\ntrap hats roll\n808 ride"),
)

CHEST_PASS_LYRICS = format_edm_score(
    ("inst", "heavy chest drop\nsub warp wreck\npass grind"),
    ("inst", "trap hats denser\n808 hold"),
    ("inst", "harder growl drop\ndual-action pedal bass\nstacked 808 wall"),
    ("inst", "pedal 808 hold\nhats roll"),
    ("inst", "full send drop\nbody bass wreck\nwarped chest"),
    ("outro", "kick holds\nhats denser\npedal ride"),
)

SUNRISE_SUB_LYRICS = format_edm_score(
    ("inst", "heavy wave drop\nwarped sub wreck\nfold 808"),
    ("inst", "trap hats roll\nwave 808 sustain dawn"),
    ("inst", "harder formant drop\nchest gold wreck\n808 punch"),
    ("inst", "full send drop\nlow 808 wreck\nwave warp"),
    ("outro", "kick holds\ntrap hats roll\nwave ride"),
)

EDM_DRIVE_THROUGH_BASS: tuple[EdmExample, ...] = (
    _ex(
        "rumble-strip",
        "rumble strip",
        140,
        271,
        1,
        "rumble-strip hybrid trap warp",
        RUMBLE_STRIP_LYRICS,
        "hybrid trap",
        "warped bass",
        "trap hats",
        "chest sub",
        "dual-action pedal bass",
        "rave",
    ),
    _ex(
        "low-lane",
        "low lane",
        144,
        277,
        1,
        "low-lane riddim warp",
        LOW_LANE_LYRICS,
        "riddim",
        "warped bass",
        "trap hats",
        "chest sub",
        "rolling 808",
        "rave",
    ),
    _ex(
        "warm-merge",
        "warm merge",
        148,
        281,
        1,
        "warm-merge wave bass warp",
        WARM_MERGE_LYRICS,
        "wave bass",
        "warped bass",
        "trap hats",
        "chest 808",
        "chest sub",
        "rave",
    ),
    _ex(
        "colour-span",
        "colour span",
        150,
        283,
        1,
        "colour-span color bass warp",
        COLOUR_SPAN_LYRICS,
        "color bass",
        "warped bass",
        "trap hats",
        "chest sub",
        "dirty 808",
        "rave",
    ),
    _ex(
        "garage-ticket",
        "garage ticket",
        140,
        293,
        1,
        "garage-ticket festival trap warp",
        GARAGE_TICKET_LYRICS,
        "festival trap",
        "warped bass",
        "trap hats",
        "trap 808",
        "dirty bass",
        "rave",
    ),
    _ex(
        "liquid-grade",
        "liquid grade",
        174,
        307,
        1,
        "liquid-grade drumstep warp",
        LIQUID_GRADE_LYRICS,
        "drumstep",
        "warped bass",
        "trap hats",
        "amen break",
        "reese bass",
        "chest sub",
        "rave",
    ),
    _ex(
        "jump-bay",
        "jump bay",
        150,
        311,
        1,
        "jump-bay brostep warp",
        JUMP_BAY_LYRICS,
        "brostep",
        "warped bass",
        "trap hats",
        "dirty dubstep",
        "bass growl",
        "heavy sub",
        "rave",
    ),
    _ex(
        "psy-median",
        "psy median",
        145,
        313,
        1,
        "psy-median neuro warp",
        PSY_MEDIAN_LYRICS,
        "neuro bass",
        "warped bass",
        "trap hats",
        "reese bass",
        "stacked 808",
        "chest sub",
        "rave",
    ),
    _ex(
        "groove-mile",
        "groove mile",
        144,
        317,
        1,
        "groove-mile hybrid trap warp",
        GROOVE_MILE_LYRICS,
        "hybrid trap",
        "warped bass",
        "trap hats",
        "dirty 808",
        "chest sub",
        "rave",
    ),
    _ex(
        "donk-ramp",
        "donk ramp",
        150,
        331,
        1,
        "donk-ramp tearout warp",
        DONK_RAMP_LYRICS,
        "tearout",
        "warped bass",
        "trap hats",
        "chest 808",
        "bass growl",
        "rave",
    ),
    _ex(
        "bounce-booth",
        "bounce booth",
        140,
        337,
        1,
        "bounce-booth chest bass warp",
        BOUNCE_BOOTH_LYRICS,
        "chest bass",
        "warped bass",
        "trap hats",
        "dirty 808",
        "chest sub",
        "rave",
    ),
    _ex(
        "toll-growl",
        "toll growl",
        150,
        347,
        1,
        "toll-growl riddim warp",
        TOLL_GROWL_LYRICS,
        "riddim",
        "warped bass",
        "trap hats",
        "tearout",
        "bass growl",
        "heavy sub",
        "rave",
    ),
    _ex(
        "night-oil",
        "night oil",
        142,
        349,
        1,
        "night-oil hybrid trap warp",
        NIGHT_OIL_LYRICS,
        "hybrid trap",
        "warped bass",
        "trap hats",
        "festival trap",
        "trap 808",
        "chest sub",
        "rave",
    ),
    _ex(
        "chest-pass",
        "chest pass",
        150,
        353,
        1,
        "chest-pass dirty bass warp",
        CHEST_PASS_LYRICS,
        "dirty bass",
        "warped bass",
        "trap hats",
        "chest sub",
        "dual-action pedal bass",
        "dirty 808",
        "rave",
    ),
    _ex(
        "sunrise-sub",
        "sunrise sub",
        140,
        359,
        1,
        "sunrise-sub wave bass warp",
        SUNRISE_SUB_LYRICS,
        "wave bass",
        "warped bass",
        "trap hats",
        "chest sub",
        "rave",
    ),
)
